### PR TITLE
Adding fly plugin (Concourse CI)

### PR DESCRIPTION
**Pull request by mamercad**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Add completions from `fly completion --shell=zsh`

## Other comments:

N/A

### CODE REVIEW

**Comment by mamercad** [comment]
What needs to happen to get this moved along?

**Comment by mamercad** [comment]
Just checking in again on this, could I get some 👀 please?

**Comment by carlosala** [comment]
Could you check `gh` plugin? Try to create a similar one, now it's the standard in omz.

**Comment by mamercad** [comment]
@carlosala Mind giving this another look (provided CI passed) please?

**Comment by mamercad** [comment]
👋 Hello @carlosala, could this get another review please?

**Review by carlosala — APPROVED** [review]
👏🏻

**Comment by mamercad** [comment]
What needs to happen to get this merged?

**Comment by mamercad** [comment]
I give up, thanks 👋

**Comment by rwmitchell** [comment]
I feel your pain.  There are plenty of backlogged PRs getting ignored, but the maintainers have time to enter a stupid hackathon competition just to be inundated with TPs making idiotic changes to readme files.

**Comment by mamercad** [comment]
> inundated with TPs making idiotic changes to readme files

Do you have a basis for this statement? [This](https://github.com/ohmyzsh/ohmyzsh/pulls?q=is%3Apr+is%3Aopen+label%3A%22Type%3A+documentation%22+created%3A%3E2022-10-01) doesn't appear to be the case.

**Comment by rwmitchell** [comment]
Sorry, I completely mistook your "I give up, thanks" statement.  I thought you were giving up getting your change added because it was taking a long time.

As for my next comment, the fact OMZ has since pulled out of the hackathon because of the garbage number of PRs submitted should speak for itself.  What an incredibly smart decision on their part!

**Comment by mamercad** [comment]
> Sorry, I completely mistook your "I give up, thanks" statement.

Nope, you got it right, I'm giving up on trying to get it merged.

**Pull request closed without merging**
