### PR TITLE
fix(docker-compose): support Compose V2 `docker compose` command

### PR DESCRIPTION
**Pull request by mcornella**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Tests if `docker compose` runs successfully and uses that to decide whether to use `docker-compose` or `docker compose` in the aliases.

## Other comments:

Fixes #10231 #10241

### CODE REVIEW

**Comment by Frederick888** [comment]
Sorry I know I should've reported this earlier, but running `docker compose` to check if it's available can block the initialisation for a long time in case of using a remote Docker context.

I've configured a context to connect to a remote Docker host via SSH, and `docker compose` command blocks for ~20s if the Docker host is down. In fact even `docker --help` / `docker --version` block. If there's no good way to work around this, I'm wondering if it's easier to simply allow overriding the auto-detection via an environment variable?

**Comment by mcornella** [comment]
I consider that a configuration error. I don't know how to do that, but [according to this page](https://blog.mikesir87.io/2019/08/using-ssh-connections-in-docker-contexts/) you could set up the context via an env variable after OMZ has loaded:
```sh
# OR use the DOCKER_CONTEXT env var
DOCKER_CONTEXT=ssh-box docker ps
```

Either way I don't see why a simple `docker compose` command should wait for an external host before displaying the help message 😐

**Comment by Frederick888** [comment]
@mcaserta Just guessing, perhaps when there are new subcommands, it needs to check if it's supported by remote Docker host and then decides whether to show the subcommand or not? (But yeah, even this is pretty weird, printing an error message only when such subcommands get called is much simpler.) Anyway, I think this is a bit off-topic here.

And thanks for the info about `DOCKER_CONTEXT`. Instead of setting it after omz (it'll be tricky to apply this environment variable to non-interactive scripts if we do this), I can try applying it to omz initialisation only. I'll give it a shot tomorrow on my work machine. But tbh I don't think this is a very clean solution.

**Comment by mcornella** [comment]
Oh, we could do that in the plugin. Does this work?
```
DOCKER_CONTEXT= docker compose
```

**Comment by Frederick888** [comment]
@mcornella It should be `DOCKER_CONTEXT=default docker compose` I think. I used `docker context use ssh-box` make sure the context was applied globally, so here it needs to switch back to the default one temporarily. Not sure if the default context can be deleted or not though...

**Comment by Frederick888** [comment]
@mcornella Something like
```sh
[[ -n "$DOCKER_CONTEXT" ]] && _DOCKER_CONTEXT="$DOCKER_CONTEXT" || _DOCKER_CONTEXT="default"
/usr/bin/env DOCKER_CONTEXT="$_DOCKER_CONTEXT" docker compose
```
?

**Comment by mcornella** [comment]
You don't need all that, when you set the env variable in the same line you call the command it only applies to that command. So as you said this should work
```sh
DOCKER_CONTEXT=default docker compose
```
Let me know when you test it if it stops taking so long.

**Comment by Frederick888** [comment]
@mcornella Yup that works! And I can confirm that the default context cannot be deleted (tested on mac):
```sh
$ docker context rm default
Error: context "default": forbidden
```

**Comment by mcornella** [comment]
OK should be fixed in 49bc55f966d91b2a407c883cf1d0f21d0cdd9f4a. Try `omz update`. Thanks for the help!

**Pull request merged**
