### PR TITLE
cache thefuck aliases

### PR DESCRIPTION
**Pull request by untoreh**

### CODE REVIEW

**Comment by Marcholio** [comment]
This could be either merged or closed

**Review by robbyrussell — APPROVED** [review]

**Comment by Noah-CompozeLabs** [comment]
@robbyrussell @untoreh I don't know if it's related, but since this was merged, whenever I `source ~/.zshrc`, I now get:
```
[oh-my-zsh] plugin 'thefuck,' not found
```
🤔 

I had last successfully loaded the plugin 4 hours ago.

**Comment by ZeddG93** [comment]
Hi there, I have problem with this merge request, I'm not using oh-my-zsh to management my zsh plugins, I just use some of the oh-my-zsh's plugins via antigen. And in this merge request, it's used an environment variable `$ZSH_CACHE_DIR` which is empty in my case. When I startup zsh, I've got an error: `permission denied: /thefuck`.

So, what can I do to make it work? e.g. create a path for  `$ZSH_CACHE_DIR`?

**Comment by TheTechRobo** [comment]
I would ask in the discord server, or in the Discussions tab

**Comment by denkristoffer** [comment]
Does this PR seem to break the `fuck` alias for anyone else? It seems like thefuck doesn't detect itself as installed anymore and tries to add the eval to `~/.zshrc`.

Before
```
$ fuck
No fucks given
```

after

```
$ fuck
Seems like fuck alias isn't configured!
Please put eval $(thefuck --alias) in your ~/.zshrc and apply changes with source ~/.zshrc or restart your shell.
Or run fuck a second time to configure it automatically.
More details - https://github.com/nvbn/thefuck#manual-installation
```

And next run:
```
$ fuck
Traceback (most recent call last):
  File "/usr/local/bin/fuck", line 13, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/thefuck/3.31/libexec/lib/python3.9/site-packages/thefuck/entrypoints/not_configured.py", line 108, in main
    _configure(configuration_details)
  File "/usr/local/Cellar/thefuck/3.31/libexec/lib/python3.9/site-packages/thefuck/entrypoints/not_configured.py", line 85, in _configure
    with path.open('a') as shell_config:
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1242, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1110, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: '/Users/user/.zshrc'
```

**Comment by TheTechRobo** [comment]
you'd be better off asking on the discord server, creating an Issue, or creating a Discussion

**Pull request merged**
