### PR TITLE
feat(git): add aliases for `worktree`

### PR DESCRIPTION
**Pull request by hoang-himself**
Replaces #8817

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

Title

## Other comments:

...

### CODE REVIEW

**Comment by fmalcher** [comment]
Could you please add the new aliases to the table in the README, too? 😊 Thanks!

**Comment by Smithienious** [comment]
Hello @fmalcher. Aliases are already added to the table. Maybe because I refactored the file that GitHub takes that this diff is too large to show by default.

<details><summary>Image</summary>
Screenshot 2021-08-13 193626
</details>

Or do you mean something else?

**Comment by fmalcher** [comment]
Ah sorry, didn't see this properly 😊 all fine!

**Comment by carlosala** [comment]
HI! I'd be in to merge this, but taking into account the new [contributing guidelines](https://github.com/ohmyzsh/ohmyzsh/blob/master/CONTRIBUTING.md#new-plugin-aliases) I'd only add the `alias gwt="git worktree". It's probably enough for most uses and you save some chars typing.
We are trying to bundle less aliases these days on!
What do you think? If you agree, could remove the others?
Thanks!

**Comment by hoang-himself** [comment]
Hello. I use worktree on a daily basis and I believe a few aliases are common tasks because they manage the life cycle of a worktree. I have since stripped lesser used aliases. Does this look good for you?

**Comment by carlosala** [comment]
I totally understand that! Let's go for it, thanks for your contribution! 😊

**Pull request merged**
