### PR TITLE
fix(git): silently fail in `git_main_branch` if not in a git repo

### PR DESCRIPTION
**Pull request by jdheyburn**
## Standards checklist:

- [X] The PR title is descriptive.
- [X] The PR doesn't replicate another PR which is already open.
- [X] I have read the contribution guide and followed all the instructions.
- [X] The code follows the code style guide detailed in the wiki.
- [X] The code is mine or it's from somewhere with an MIT-compatible license.
- [X] The code is efficient, to the best of my ability, and does not waste computer resources.
- [X] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- `git_main_branch` silently returns when executed outside of a git repo. 

## Other comments:

Mimics the same behaviour as `git_current_branch`
...

### CODE REVIEW

**Comment by mcornella** [comment]
Would silencing stderr on the `git show-ref` command be enough?

**Comment by jdheyburn** [comment]
@mcornella fair point - but if we're running the command in a legit git repo you may want the stderr for debugging. I only took the approach another function had for consistency.

**Comment by mcornella** [comment]
Changed it to [`git rev-parse --git-dir`](https://stackoverflow.com/a/2180367/5798232) which is the proper way to do it. Works for me but test it first before merging.

**Comment by jdheyburn** [comment]
> Changed it to [`git rev-parse --git-dir`](https://stackoverflow.com/a/2180367/5798232) which is the proper way to do it. Works for me but test it first before merging.

Nice one 👍  Confirmed it works as expected on my end

**Pull request merged**
