### PR TITLE
show ahead and behind numbers

### PR DESCRIPTION
**Pull request by fmauch**
I like to have the number of ahead and behind commits in the prompt, as well. I added this feature to the bureau theme. Maybe you want this merged?

### CODE REVIEW

**Comment by fmauch** [comment]
I updated this merge request to run with the current master. Any comments on this?

**Comment by TheTechRobo** [comment]
You don't have to close it if it isn't merged. They have a backlog of 532 other pull requests. Please be patient with them.

_cc @mcornella_

**Comment by fmauch** [comment]
Maybe I should drop a comment about this... I decided that the cleaner thing would be to add my own zsh theme and use the `ZSH_CUSTOM` meachanism to get this into my env. See https://github.com/fmauch/dotfiles/tree/master/zsh for details.

**Comment by TheTechRobo** [comment]
Oh, that makes sense I thought you had just closed it due to inactivity

**Pull request closed without merging**
