### PR TITLE
Added a new plugin for fnm autocompletion

### PR DESCRIPTION
**Pull request by AdamGS**
## Standards checklist:

- [X] The PR title is descriptive.
- [X] The PR doesn't replicate another PR which is already open.
- [X] I have read the contribution guide and followed all the instructions.
- [X] The code follows the code style guide detailed in the wiki.
- [X] The code is mine or it's from somewhere with an MIT-compatible license.
- [X] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Add a new plugin for [fnm](https://github.com/Schniz/fnm), a fast and simple node.js version manager.

### CODE REVIEW

**Comment by AdamGS** [comment]
Hi @bartekpacia, is there anything else I should do to get this merged?

**Comment by bartekpacia** [comment]
To me, everything looks okay. We need to wait for @mcornella

**Review by 53jk1 — APPROVED** [review]

**Comment by sebenik** [comment]
This PR is outdated so new one was created at #9864

**Comment by TheTechRobo** [comment]
Why did you close it? If it was inactivity, it's because of the huge backlog of PRs

**Comment by AdamGS** [comment]
The PR was obsolete and a new up to date PR was created (#9864), so I though that closing it myself will help the maintainers

**Comment by TheTechRobo** [comment]
Oh, that makes sense

**Pull request closed without merging**
