### PR TITLE
feat(archlinux)!: remove deprecated commands `aur` and `abs`

### PR DESCRIPTION
**Pull request by jeffmhubbard**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Remove calls to aur and abs commands

## Other comments:

See #8591

### CODE REVIEW

**Comment by ratijas** [comment]
haha, I was about to do it too. Actually, there's no need to remove them completely.  According to Arch Linux news, `abs` was superseded by `asp`: [Deprecation of ABS tool and rsync endpoint](https://archlinux.org/news/deprecation-of-abs/). Relevant [discussion](https://bbs.archlinux.org/viewtopic.php?id=226693) on forum.

**Comment by ratijas** [comment]
> Other comments:
> See #859

That links to something completely irrelevant. Probably a typo or just a template leftover?

**Comment by jeffmhubbard** [comment]
Even is `asp` is a dropin replacement for `abs`, the fact that it was broken for so long with no issues raised, indicates that no one was using it. I'm in favor dropping it, until someone who needs it comes along.

As for `aur`, I believe this was an older tool that is no longer maintained. `aurutils` provides a `aur` command, which is why I opened #8591. I asked Alad on IRC, but he was unaware of any other current tools also providing `aur`.

**Comment by ratijas** [comment]
> it was broken for so long with no issues raised

Either no one gives a damn about raising an issue, or no one really uses such complicated aliases. The whole concept of conditional combination is strange enough.

But on the other hand, sets of aliases are a valuable source of educational material. If I were a n00bish Arch Linux wannabe, I'd probably be happy to learn about `asp` and its role in the whole ecosystem just by looking at the README of this plugin.

So, in the end, I'm voting to replace them with `asp update` or something. And to make them unconditional, to reduce confusion.

**Comment by jeffmhubbard** [comment]
I think I'd like this PR to be just about removing what doesn't work. If you want to add support for other tools and support those changes, that would be great. I'm not using `asp`, so I don't want to take on that responsibility.

**Comment by ratijas** [comment]
OK then.  Please, make sure to update ² and ³ references in README.

**Review by ratijas — APPROVED** [review]

**Comment by mcornella** [comment]
Thank you both!

**Pull request merged**
