### PR TITLE
feat(kubectl): show labels in aliases `kgpsl` (get pod) and `kgnosl` (get node)

### PR DESCRIPTION
**Pull request by PixiBixi**
## Standards checklist:

- [ x ] The PR title is descriptive.
- [ x ] The PR doesn't replicate another PR which is already open.
- [ x ] I have read the contribution guide and followed all the instructions.
- [ x ] The code follows the code style guide detailed in the wiki.
- [ x ] The code is mine or it's from somewhere with an MIT-compatible license.
- [ x ] The code is efficient, to the best of my ability, and does not waste computer resources.
- [ x ] The code is stable and I have tested it myself, to the best of my abilities.
- [ x ] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

Add 2 new kubectl aliases

## Other comments:

...

### CODE REVIEW

**Comment by mcornella** [comment]
Hi, what's the use case for this, instead of completing the argument whenever you need it?

**Comment by PixiBixi** [comment]
To be honest I'm just lazy, but we can say the same for all alias? :D

**Comment by mcornella** [comment]
What I meant to say is how often do you use this command, and more generally how often would you say it's needed for k8s users?

**Comment by PixiBixi** [comment]
Labels are very useful on K8S to get taint... and its usually often used

**Comment by mcornella** [comment]
Thanks for providing reasoning, I agree these are useful. Please add them to the plugin README as well, then I'll merge the PR. Thanks!

**Comment by PixiBixi** [comment]
Fixed.

It was an already kgpl alias (which was in fact not useful), i've deleted it.

**Review by mcornella — CHANGES_REQUESTED** [review]
The `kgpl` alias was introduced in #6636 to filter out pods by label. That is something that's very common in k8s, and removing an alias is considered a breaking change and will have many people affected.

If you want to keep yours, it'd be better to rename it to something else, such as `kgpsl`, `kgplb` or something similar.

**Comment by PixiBixi** [comment]
you right! i've re-introduced the old kgpl and add mine as kgpsl

**Pull request merged**
