### PR TITLE
docs(bazel): improve plugin README

### PR DESCRIPTION
**Pull request by alealv**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Update bazel completion link

### CODE REVIEW

**Comment by carlosala** [comment]
Hi Alejandro! I think it's better to let that line as is! Probably users would take more advantadge of understanding what basel is that just redirecting to a zsh file. Thanks for your contribution!

**Comment by mcornella** [comment]
Link should be https://github.com/bazelbuild/bazel/blob/master/scripts/zsh_completion/_bazel though.

**Comment by alealv** [comment]
Yes, link was broken, that's why I created the PR. Although, I should have pointed to the zsh file instead.

**Comment by carlosala** [comment]
But the previous link was working. Why do you want to change it?

**Comment by mcornella** [comment]
> But the previous link was working. Why do you want to change it?

It's missing `blob/` before `master`.

**Comment by carlosala** [comment]
I was talking about the one bundled now with omz. The link to bazel website

**Comment by carlosala** [comment]
Ough I messed up the `diff`. I thought that he was changing from bazel.build to github.com, so reversed to reality. Sorry guys 😅

**Pull request merged**
