### PR TITLE
feat(git): add bisect aliases `gbsn` and `gbso`

### PR DESCRIPTION
**Pull request by adamchainz**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

Add two aliases for the [`git bisect` subcommands](https://git-scm.com/docs/git-bisect) `old` and `new`. These are alternative labels to the original `good` and `bad`, which are applicable in more situations. For example, when searching for a commit that accidentally *fixed* a bug, the meanings of “good” and “bad“ are confusingly reversed, whilst “old“ and “new“ remain clear.

## Other comments:

NOne.

### CODE REVIEW

**Comment by carlosala** [comment]
I'm not quite sure that these aliases are quite relevant, actually. They are exactly the same as `good/bad`, and it's already kind of a standard to use `good/bad`, even though it makes complete sense what you say.
Taking it into account, it makes much more sense to me to have these kinds of aliases in your personal config, in case the semantics of `gbsg` and `gbsb` are not enough for you, or anyone in the same situation.
What do you kind about it?

**Comment by adamchainz** [comment]
I think that if `git bisect` were created from scratch, there would only be `old` and `new`. There’d be no need for `good` and `bad`, since they’re specific only to finding new bugs.

I’m hoping to encourage using `old` and `new` by default by teaching them first in my new book. I also thought this PR could help “spread the word”.

**Comment by carlosala** [comment]
Could you update the README accordingly?

**Comment by carlosala** [comment]
Thanks for your contribution!

**Comment by adamchainz** [comment]
Brilliant, thanks!

**Pull request merged**
