### PR TITLE
add alias plugin: cheatsheat your alias.

### PR DESCRIPTION
**Pull request by hqingyi**
with lots of 3rd-party amazing aliases installed, just need something to explore it quickly.

 **acs: alias cheatsheet**
1. `acs`: group all alias
2. `acs $keyword`quickly filter alias & highlight

### CODE REVIEW

**Comment by HQingYi** [comment]
image

like this

**Comment by ensonik** [comment]
I like this; I've been slowly learning the aliases with "alias-tips", but this would be a great addition.

**Review by robbyrussell — APPROVED** [review]
Did some testing today and it appears to be working nicely. Given how long this has been lingering, I'm going to allow this to go out!

**Comment by juanitoddd** [comment]
How can I "group" my alias so when I run `acs` it shows:
`[custom_group]`
       `alias foo=bar`

**Pull request merged**
