### PR TITLE
Add alias for git merge --signoff

### PR DESCRIPTION
**Pull request by MrSkwiggs**
## Standards checklist:
- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:
- Added a `gms` alias for `git merge --signoff`

### CODE REVIEW

**Comment by MrSkwiggs** [comment]
Hello, is there any update on when this PR could be merged?

**Review by jmeridth — CHANGES_REQUESTED** [review]
Need to also update README

**Comment by MrSkwiggs** [comment]
@jmeridth Sorry somehow I completely missed your comment. Have done so (and updated the branch as it was _way_ out of date 🤓)

**Comment by adamchainz** [comment]
I think `--signoff` is too specific to include an alias for. The only project I’ve ever seen using it is Git itself. Also `git commit --signoff` would be much more common.
I think this should fit

**Comment by carlosala** [comment]
Nowadays with the most used git workflows (based on PRs, MRs, or the equivalent in your system) makes not much sense to signoff the commits, even more taking into account that is the merge commit.
Closing then, thanks for the contribution to everyone!

**Pull request closed without merging**
