### PR TITLE
fix(dirhistory): make sure to call built-in zle widgets

### PR DESCRIPTION
**Pull request by stephane-caron**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Make sure built-in widgets are used for `kill-buffer` and `accept-line`

## Other comments:

Fixes https://github.com/ohmyzsh/ohmyzsh/issues/9770

### CODE REVIEW

**Comment by mcornella** [comment]
I can't reproduce #9770 so I can't verify this works. Are you sure that's the problem? It would look like there's a binding to `.dirhistory_zle_dirhistory_back` instead of `dirhistory_zle_dirhistory_back`.

**Comment by stephane-caron** [comment]
> I can't reproduce #9770 so I can't verify this works. Are you sure that's the problem? It would look like there's a binding to `.dirhistory_zle_dirhistory_back` instead of `dirhistory_zle_dirhistory_back`.

I agree, but there's no mention of `.dirhistory_zle_dirhistory_back` in the code of the plugin :thinking: Although without the dot there definitely is:

```bash
~/.oh-my-zsh/plugins/dirhistory$ grep ".dirhistory_zle_dirhistory_back" dirhistory.plugin.zsh | wc -l
0
~/.oh-my-zsh/plugins/dirhistory$ grep "dirhistory_zle_dirhistory_back" dirhistory.plugin.zsh | wc -l
7
```

Sorry I'm not fluent enough with the zsh line editor to understand what's going on here.

**Comment by stephane-caron** [comment]
Oh my bad! I found the guilty function in my `~/.oh-my-zsh/custom/redo.zsh` bindings (I totally forgot about that :sweat_smile:):

```zsh
#!/bin/zsh

# Redefine default Enter command so it inserts last command if the buffer is
# empty. Source: https://stackoverflow.com/a/46525918

function accept-line() {
    [ -z "$BUFFER" ] && zle up-history
    zle ".$WIDGET"
}

zle -N accept-line
```

Explains the dot :wink: 

This PR only makes the plugin robust against being messed up with like this :grin: I see that the `per-directory-history` plugin does it as well.

**Comment by mcornella** [comment]
Thanks @stephane-caron, great explanation!

**Pull request merged**
