### PR TITLE
feat(archlinux): fix keyring update function

### PR DESCRIPTION
**Pull request by deimosian**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

- Fixed Arch Linux upgrade's keyring update function.

## Other comments:

...

### CODE REVIEW

**Comment by deimosian** [comment]
Fixes bug introduced in https://github.com/ohmyzsh/ohmyzsh/pull/11597

**Comment by carlosala** [comment]
Sorry for that, you're right! I changed that to keep track what's omz and what's the CLI used to upgrade, I think it's great to have it like that.

**Comment by deimosian** [comment]
I just dislike how it looks compared to making it blend in. I also don't think the Arch user who's calling an OMZ plugin function needs their hand held like that. 

For example, the two different versions with `Yay` installed.



Vs

**Comment by carlosala** [comment]
Let's change that then! Maybe removing those `::` at the beginning, but let's go for it! It's not a big deal, could you open a PR?

**Comment by deimosian** [comment]
I'd like to keep the `::`. They are used for section headers for Pacman and Pacman helpers. 

Without OMZ is starts with the `:: Synchronizing package databases...` line. 

The blue `::` are for Pacman while the green `::` are for Yay, so the `::` without color applied do subtly differentiate it.

I'll open another PR, do with it what you will.

**Pull request merged**
