### PR TITLE
Add git alias to remove all merged exclude master|develop|main

### PR DESCRIPTION
**Pull request by rogoit**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- In the git file for alias and add to readme file

## Other comments:

This command helps me so much and i want to give it to the community

### CODE REVIEW

**Comment by rogoit** [comment]
Can anybody give me feedback for the spell checking. Its for an alais ;)

**Comment by jsoref** [comment]
If #10475 is merged, then you could just rebase and it wouldn't complain. Otherwise, you can select the last line of the bot's comment and choose the three dots at the top right of the comment and select `Quote reply`.

**Comment by rogoit** [comment]
Hi @jsoref i do not get it and do not know what i exactly can do. Now i go out with my kids and try in evening.

See you and thy for your passion

**Comment by mcornella** [comment]
The `gbda` alias does the same thing, but thanks for the contribution!

**Pull request closed without merging**
