### PR TITLE
fix(npm): ignore `rm` alias

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

- npm plugin: disregard `rm` alias if set.

## Other comments:

See also: #11156.

### CODE REVIEW

**Review by LunarWatcher — APPROVED** [review]
Looks reasonable to me (even though I don't understand why anyone would make an alias that shadows an existing base command; this has to cause problems beyond OMZ if it's aliased to the right thing:tm: -- aside the point, however)

**Comment by rwmitchell** [comment]
People used to alias rm to rm -I
as a safety net, which is great up until the alias isn’t there.

**Comment by ZhongRuoyu** [comment]
Thanks for reviewing!

Personally I've been aliasing `rm` to something like...

```zsh
alias rm="echo 'Think again and type: command rm'"
```

... ever since I had an unpleasant experience of executing `rm -rf $SOMETHING/` while forgetting to set variable `$SOMETHING`, and ended up executing `rm -rf /`. With the aliased `rm`, the above would instead print this out, with variables and wildcards properly evaluated:

```plaintext
Think again and type: command rm -rf /
```

So I can see clearly what's going on.

While this reason may not be justifiable enough, it has not brought me much trouble thus far, because aliases are not evaluated by shell scripts by default (but not if they are `source`d, like the npm plugin). There are other `rm` invocations in my OMZ, but they are unshadowed with `command rm`. So I believe it's justifiable to bring this to the npm plugin as well.

**Comment by ZhongRuoyu** [comment]
Sorry for pinging, but I wonder if it would be possible to land this? @mcornella

**Review by mcornella — APPROVED** [review]

**Comment by ZhongRuoyu** [comment]
Thanks!

**Comment by mcornella** [comment]
Thank you! 😊

**Pull request merged**
