### PR TITLE
Add Ag completion

### PR DESCRIPTION
**Pull request by eipipuz**
A replacement for ack/grep https://github.com/ggreer/the_silver_searcher

### CODE REVIEW

**Comment by robbyrussell** [comment]
Hi @eipipuz, could you include a README for the plugin per #2640?

**Comment by apjanke** [comment]
Note there may be a conflict of sorts with the ubuntu plugin #3601 which defines an `ag` alias and its own completions for it (per #3633).

**Comment by oryband** [comment]
:+1:

**Comment by oryband** [comment]
another conflict duplicate, opened by me (was unaware of the other ones) at #3844

**Comment by gmile** [comment]
@robbyrussell any chance to get this merged?

**Comment by eipipuz** [comment]
Sorry it took me forever to get back to this. Let me know if there's more I need to do.

**Review by 53jk1 — APPROVED** [review]

**Pull request merged**
