### PR TITLE
Add plugin for bazel completion

### PR DESCRIPTION
**Pull request by israelfaria**
Hi, I have created a new plugin to add bazel zsh completion copied from their repo.

### CODE REVIEW

**Comment by willdzeng** [comment]
Nice, this is very helpful but, no one is reviewing this?

**Comment by israelfaria** [comment]
Rebased and updated from bazel upstream. Still hoping someday this will get merged!

**Comment by jackwish** [comment]
FYI: you may try out a *custom* plugin https://github.com/jackwish/bazel

**Comment by diwu1989** [comment]
can we have this merged please?
it's much easier to use this as an official plugin vs third party customization

**Comment by larson-carter** [comment]
I'm going to leave this here for reference: https://github.com/bazelbuild/bazel/blob/master/scripts/zsh_completion/_bazel

We will have to find a way to automate the script from bazel, also we will have to actively maintain the zsh completion.

**Pull request merged**
