### PR TITLE
feat(tmux): add option for detached mode

### PR DESCRIPTION
**Pull request by MoonDusk1996**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [X] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

- I honestly don't know why this wasn't added earlier. It's a feature I use frequently because it compels me to keep only one section active and adjust the screen size accordingly.

## Other comments:

- I also took the liberty of defining the README.md list of features and aliases in alphabetical order, improving the pattern and organization.

### CODE REVIEW

**Review by carlosala — APPROVED** [review]
LGTM 🚀

**Comment by carlosala** [comment]
Thanks for your contribution!

**Comment by momolemo** [comment]
this introduce a bug, the var defined at the top of the file break the test which output always -d because the var is defined.

we can't disable the feature and the session il always detach even if we don't want.

**Comment by carlosala** [comment]
@momolemo oh shit, what a mistake from my side! This was fixed in 0008534147a28eeeea52cfd92154ae2e801678ae

**Comment by momolemo** [comment]
no problem it happens :) thank for the reactivity and the patch :)

**Pull request merged**
