### PR TITLE
feat(CLI): add `plugin info` subcommand

### PR DESCRIPTION
**Pull request by fcrespo82**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

Extend omz cli (#8876) with a `plugin info <name>` subcommand that shows the plugin README.md

## Other comments:

This is a WIP with enhanced functionality to help improve `omz cli`.
This should not be considered final and is open for feedback.

### CODE REVIEW

**Comment by fcrespo82** [comment]
Hi @robbyrussell, do you like this approach?

Maybe a better way is to convert the README to a manpage?

Let's talk.

**Comment by mcornella** [comment]
Hey @fcrespo82, thanks for the contribution! I fixed some stuff in the logic, please have a look and let me know what you think.

**Comment by fcrespo82** [comment]
Glad I was able to help.

LGTM

**Comment by mcornella** [comment]
Thanks!

**Pull request merged**
