### PR TITLE
Allow waiting dots customization

### PR DESCRIPTION
**Pull request by mortezadadgar**
Signed-off-by: mortezadadgar <mortezadadgar97@gmail.com>

## Standards checklist:

- [x] The PR title is descriptive.
- [ ] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

### CODE REVIEW

**Review by TheTechRobo — COMMENTED** [review]
Does it default to the normal mode? This looks like if you don't uncomment the lines there will be no dots

**Comment by mortezadadgar** [comment]
> Does it default to the normal mode? This looks like if you don't uncomment the lines there will be no dots

yes you're right, rebased

**Comment by mortezadadgar** [comment]
@mcornella Is there any reason you don't merge this pull

**Comment by mcornella** [comment]
This can be simplified to a single setting that includes the whole color + symbol sequence which also makes it more customizable.

**Comment by TheTechRobo** [comment]
@mortezadadgar They get a lot of PRs, be patient. :)

**Comment by mortezadadgar** [comment]
CC @mcornella

**Comment by mcornella** [comment]
Pushed 16de51404773a5e849c25a95e7612e212e7256a7 which uses the same `COMPLETION_WAITING_DOTS` variable to change the default red dots string, while turning off line wrapping.

**Pull request closed without merging**
