### PR TITLE
Plugins: vi-mode: extra vi-like bindings, vi-like commands clipboard 

### PR DESCRIPTION
**Pull request by alx741**
- Added standard `ctrl-r` for incremental history searching
- Added `G` `gg` `u` `^-R` vim commands behavior
- Added X clipboard interaction with standard vim commands ( y/p/d/c )
- From zsh wiki vim bindings [examples|suggestions?]

### CODE REVIEW

**Comment by regagain** [comment]
ctrl-r for history searching & the extra vim-like bindings work well and are much appreciated (I have not tested the copy/paste from the clipboard).

**Comment by alx741** [comment]
A way copy/paste can be used/tested (that is actually useful) is by copy an URL from the browser and then in the terminal (<ESC> is used to get into normal mode -of course-):

    $ wget <ESC>p

Another example for youtube video downloading:

    $ youtube-dl <ESC>p

**Comment by regagain** [comment]
OK! I've tested it now and it's really cool. One strange thing, though: it seems `yy` cease to properly update the vi-like buffer once something has been copied from the clipboard.
For example:
`ctrl+c` from the browser or anything else, then:
```
$ <ESC>p
```
results in
```
$ from_browser
```
But after this:
```
$ from_zsh<ESC>yy
$ <ESC>p
```
still results in
```
$ from_browser
```
(but `ctrl+v` is still working as expected, i.e. gives `from_zsh`).

**Comment by alx741** [comment]
Thank you very much for testing,

I didn't notice that, it's strange indeed... I'll check it out!

**Comment by djpresent** [comment]
Excelente ... +1

**Comment by Alibru** [comment]
Interesting and useful! +1

**Comment by alx741** [comment]
@0arthur  Added in pull request message, but.. do you mean inside the file?

**Comment by 0arthur** [comment]
Daniel,
This is fine.

Cheers,
Arthur

On Sun, Mar 29, 2015 at 16:33 -0700, Daniel Campoverde Carri�n wrote:
>@0arthur  Added in pull request message, but.. do you mean inside the file?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/robbyrussell/oh-my-zsh/pull/3616#issuecomment-87497578

-- 
Arthur Noel
 arthur@0compute.net
 +44 (0)7967 385514

**Comment by regagain** [comment]
Hello there!

I've been using this for almost two months now, and find it useful & reliable. Can we please merge it?

Thanks,

**Comment by rosshadden** [comment]
The X clipboard functionality should be broken out into a separate merge request, so as not to prevent this one from being merged.  There are many things that need to be discussed and ironed out.

For instance, it is unexpected that `y, p, d, c` would alter the system clipboard.  For one thing this adds an `xclip` dependency, but more importantly that's just not how `vim` itself works.  When you use these operations in `vim`, it uses the internal register just like `zsh`'s vi-mode does natively.  To get X integration you tell it to use the `"` register (for example).  Having `vim` use the system clipboard for all change/delete operations does not sound like a good idea, as you would be unnecessarily polluting the clipboard.

Now that being said, it would be very useful to make `vicmd` commands that yank/put with the system clipboard, which users could bind themselves, or this project could bind to a different set of keys.

**Comment by afwlehmann** [comment]
The latest changes seem to have happened quite some time ago. Since I'm very much interested in vim-like copy/paste functionality, may I ask whether there's any progress or related solution?

**Comment by felipe-vieira0** [comment]
@alx741  ,

Unfortunately, this is interfering with navigation (the up and down keys do not search correctly anymore). I would love to see this implemented.

Thanks!

**Comment by alx741** [comment]
@felipe-vieira0   yeah... I suppose at this point its impossible to make it work without pretty much re-implementing it, I stopped using oh-my-zh years ago though and went with just a personal .zshrc for improved performance. So I guess there will not be further progress from my side on this... sorry about that.

**Pull request closed without merging**
