### PR TITLE
mkcd plugin - create directory and change into it

### PR DESCRIPTION
**Pull request by KrzysztofHajdamowicz**
## Standards checklist:

- [X] The PR title is descriptive.
- [X] The PR doesn't replicate another PR which is already open.
- [X] I have read the contribution guide and followed all the instructions.
- [X] The code follows the code style guide detailed in the wiki.
- [X] The code is mine or it's from somewhere with an MIT-compatible license.
- [X] The code is efficient, to the best of my ability, and does not waste computer resources.
- [X] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- This plugin creates directory and changes into it, it's exactly `mkdir foo && cd foo`

### CODE REVIEW

**Review by TheTechRobo — COMMENTED** [review]
Maybe add a bit more documentation in the readme (say the command and its usage) and maybe make the -p flag optional?

I like this. I think itd be very good for my workflow.

**Comment by jeffmhubbard** [comment]
Why not just use `take` that's included in `lib/functions.zsh`?

```
function take() {
  mkdir -p $@ && cd ${@:$#}
}
```

**Comment by rwmitchell** [comment]
mkcd is a logical combination of mkdir  and cd - what does take mean?

**Comment by TheTechRobo** [comment]
Oh - the take command seems to have the exact same functionality with a different name. :thinking:

image

**Comment by KrzysztofHajdamowicz** [comment]
> Oh - the take command seems to have the exact same functionality with a different name. 🤔
> 
> image

Maybe we should rename `take` into `mkcd` as new name will be more self-explanatory to users? This issue already contains 3 of them.

**Comment by jeffmhubbard** [comment]
> > Oh - the take command seems to have the exact same functionality with a different name. thinking
> > image
> 
> Maybe we should rename `take` into `mkcd` as new name will be more self-explanatory to users? This issue already contains 3 of them.

Renaming it would be break existing workflows. `take()`  was added 12 years ago... Also it's documented on the [cheatsheet](https://github.com/ohmyzsh/ohmyzsh/wiki/Cheatsheet) pretty clearly.

**Comment by rwmitchell** [comment]
maybe so, but it is still a poor name.  going from mkdir to mkcd makes a lot of sense.  'take' is meaningless.

**Comment by rwmitchell** [comment]
i'm not 'take'ing anything.  A directory is being created and then cd'd into.

**Comment by KrzysztofHajdamowicz** [comment]
Instead of renaming `take`, we can add an alias `mkcd` -> `take` or implement this as a plugin.

**Comment by rwmitchell** [comment]
if anything, it should be the opposite with a note that take is being depricated.
clean things up instead of adding more junk.  'take' is junk.

**Comment by jeffmhubbard** [comment]
> Instead of renaming `take`, we can add an alias `mkcd` -> `take` or implement this as a plugin.

An alias is preferable to adding a plugin for an existing feature.

**Comment by rwmitchell** [comment]
it isn't a plugin, it's a 1 line function:
take is a shell function from /Users//.oh-my-zsh/lib/functions.zsh

take () {
	mkdir -p $@ && cd ${@:$#}
}

certainly no one is using it a script and anyone needing it can alias take to the new mkcd

**Comment by jeffmhubbard** [comment]
> it isn't a plugin, it's a 1 line function:
> take is a shell function from /Users//.oh-my-zsh/lib/functions.zsh
> 
> take () {
> mkdir -p $@ && cd ${@:$#}
> }
> 
> certainly no one is using it a script and anyone needing it can alias take to the new mkcd

This PR is for a plugin.

**Comment by rwmitchell** [comment]
I agree this should not be added as a plugin, but 'take' should be renamed.

`mk[TAB]` allows someone to easily discover mkcd when starting to type mkdir.  'take' is only discovered by hunting it down.

**Comment by mcornella** [comment]
`take` was made into its own thing that supports different stuff (f68d65d32a4fce41f08ac229614b7e46baf5e916). I've added `mkcd` as an equivalent to `takedir`.

Thank you for your feedback!

**Pull request closed without merging**
