### PR TITLE
gitfast: add mergetool completion

### PR DESCRIPTION
**Pull request by remcohaszing**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- `mergetool` has been added to the `git` completion in the `gitfast` plugin.

## Other comments:

I switched to `gitfast` because I started using `git switch`. `mergetool` was the one completion I really missed and started typing wrong because `git m<tab>` would complete to `git merge `. (Note the trailing space.)

### CODE REVIEW

**Comment by mcornella** [comment]
The gitfast plugin uses the [official git completion](https://github.com/git/git/blob/master/contrib/completion/git-completion.zsh), you should direct this change to the upstream project. @felipec

**Comment by felipec** [comment]
@mcornella It uses the official completion, but not quite; I have patches on top of it.

Right now the projects are not properly synchronized (there's pull/8550 pending), we need more communication to decide how to proceed.

**Comment by mcornella** [comment]
Ok let me see what needs to be done to fix everything in the gitfast plugin.

**Comment by larson-carter** [comment]
@felipec I'm reviewing pull 8550, however it needs to be broken into 2 or more different PRs. It looks like you are trying to do so much into one PR.

See my exact reply here: https://github.com/ohmyzsh/ohmyzsh/pull/8550#issuecomment-606371743

**Pull request closed without merging**
