### PR TITLE
Patch/hitchiker fortune

### PR DESCRIPTION
**Pull request by luizpericolo**
Hitchhiker's Guide to the Galaxy fortune in comemoration of Towel Day

### CODE REVIEW

**Comment by luizpericolo** [comment]
Happy towel day 2017!

**Comment by luizpericolo** [comment]
@mcornella Is there something missing for this to be merged?
Thanks!

**Comment by rachael** [comment]
Resurrecting this because it's cute 

@mcornella

**Comment by mcornella** [comment]
Can this download the fortune file on first run instead? It's a biiig file for everyone that won't be using the plugin.

**Comment by TheTechRobo** [comment]
Hm, I'm wondering what place would be best for that download. `~/.oh-my-zsh/custom` ???

**Comment by mcornella** [comment]
Noticed that we have several files above 24k including the one from the chucknorris theme, so it's fine we have one more.

Merged in d8b3e115e968225b5a0b999ea9292ac0263d5586 after several fixes.

**Pull request closed without merging**
