### PR TITLE
Refactored django plugin

### LINKED ISSUE #8509: Django auto-complete plugins not working for custom commands
**Describe the bug**
I have added `django` to the plugins list in `~/.zshrc` (`plugins=(git django)`). But my custom commands do not auto-load on pressing `Tab`. I have tried this with my Python `virtualenv` sourced.

**System:**
 - OS: macOS
 - Zsh version 5.7.1 (x86_64-apple-darwin19.0)
 - Terminal emulator [e.g. iTerm2]

**Additional context**
https://docs.djangoproject.com/en/3.0/howto/custom-management-commands/

### LINKED ISSUE #8726: django plugin: _values:compvalues:11: not enough arguments
**Describe the bug**
Autocompletion for certain commands in django plugin doesn't work

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable this plugin 'django'
2. Install django and generate simple project with `django-admin startproject`
3. From the folder contains manage.py file try the autocomplete commands like `manage.py dumpdata` or `manage.py test`

**Expected behavior**
It must display list of applications specified in INSTALLED_APPS section in settings.

**Desktop (please complete the following information):**
 - OS / Distro: Ubuntu 19.10
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: 5.7.1
 - Terminal emulator GNOME Terminal

**Additional context**
- The autocompletion for 'celery' plugin that also evaluates `_values` command works just fine.
- I already removed ~/.zcompdump* files

### PR DESCRIPTION
**Pull request by ikhomutov**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Updated method that searches management commands (Fixes #8509)
- Updated method that searches installed applications (Fixes #8726)
- Added prefixes for global zsh variables to prevent possible collision
- Changed methods names that responsible for separate command completion to prevent from possible collisions when users try to create completion for custom command
- It is possible to create completion for custom commands (example for [rest_framework](https://github.com/ikhomutov/zsh-django-restframework/blob/master/zsh-django-restframework.zsh))
- Updated option based on latest LTS version of django

## Other comments:

Tested with django 2.2.6 and 2.2.10

### CODE REVIEW

**Comment by ikhomutov** [comment]
I've also deleted completion for django-admin command, because this command requires additional checks whether DJANGO_SETTINGS_MODULE environment is set or --settings option is present.

**Comment by bartekpacia** [comment]
This looks good, I think there's no reason why it should not be merged.
Thank you for the PR.

**Review by 53jk1 — APPROVED** [review]

**Comment by mcornella** [comment]
I've renamed the file to `_django` since it's only completion and added a fix for a potential vulnerabilty. Please test again and let me know if it works.

**Comment by mcornella** [comment]
Hey there, upon closer inspection, this refactor removes the completion description of arguments, is there any way that we can keep those or parse them from `manage.py` output?

**Comment by mcornella** [comment]
Plugin removed in 73001e9382db99ebd6effcf0bdcd227985109142.

**Pull request closed without merging**
