### PR TITLE
feat(tig): add `tdo` alias to show current branch and its upstream branch

### PR DESCRIPTION
**Pull request by liijunwei**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Added alias for tig, showing current branch and its origin branch in one tig view

## Other comments:

N/A

### CODE REVIEW

**Comment by mcornella** [comment]
Can you show a description of what the command does, and fix the alias description in the README and the PR title?

**Comment by liijunwei** [comment]
> Can you show a description of what the command does, and fix the alias description in the README and the PR title?

Sure， will "tig show(or diff) current branch and its upsteam"  do the work ?  I'm not sure.
But, emmm. should I create another PR to edit the README file ?

**Comment by liijunwei** [comment]
Appreciate for your reply. @mcornella

**Comment by mcornella** [comment]
This just shows both branches, is that the intention instead of just displaying the difference (`tig HEAD@{u}...HEAD`)?

`tdo`:
Captura de pantalla de 2021-09-16 10-47-01

`tig HEAD@{u}...HEAD`:
Captura de pantalla de 2021-09-16 10-48-32

Also, maybe the alias should be `tdu` since `upstream` is a more accurate name than origin.

**Comment by liijunwei** [comment]
> This just shows both branches, is that the intention instead of just displaying the difference (`tig HEAD@{u}...HEAD`)?
> 
> `tdo`:
> Captura de pantalla de 2021-09-16 10-47-01
> 
> `tig HEAD@{u}...HEAD`:
> Captura de pantalla de 2021-09-16 10-48-32
> 
> Also, maybe the alias should be `tdu` since `upstream` is a more accurate name than origin.

Yes, that's is my intention to show both branches, since in our git flow uses `rebase and fast-forward` insead of just merge commit into current branch. So I gotta frequently review where I am, and where the upsteam is. I suppose this will also be the demand of people who have similar workflows to ours.

I agree with your `tdu` suggestion, but ugh, my habbit is there...(It seems eaiser to type) ^.^, sure I can change it to `tdu`;

**Pull request closed without merging**
