### PR TITLE
feat(encode64): add `encodefile64` function

### PR DESCRIPTION
**Pull request by jmcombs**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- This commit adds `encodefile64` to the `encode64.plugin.zsh` to allow for encoding of a provided file's contents to base64
- The `README` has been updated describing the addition and how to use it

## Other comments:

I added this functionality because I have to encode files in base64 to upload to Cisco Webex Room Systems.

### CODE REVIEW

**Comment by jmcombs** [comment]
@jmeridth, Do I need to do anything after the PR has been approved to get it merged? Thanks!

**Comment by jmeridth** [comment]
One of the maintainers has to merge it. Do you see the option to merge?

**Comment by jmcombs** [comment]
@jmeridth, I do not. It says that only those with write access can merge it. Sounds like someone else has to merge it.

**Comment by carlosala** [comment]
Thanks for your contribution 😊

**Pull request merged**
