### PR TITLE
Add update alias to pipenv plugin.

### PR DESCRIPTION
**Pull request by SnoopDraugg**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

- [add `pdt` alias to `pip update`]

## Other comments:

Updating all the packages in the env is something I do on a regular basis and I hope that others would as well.

### CODE REVIEW

**Comment by carlosala** [comment]
`pup` is already a CLI tool. Could we get another alias instead?
https://command-not-found.com/pup

**Comment by SnoopDraugg** [comment]
> `pup` is already a CLI tool. Could we get another alias instead?
> https://command-not-found.com/pup

We sure can. 

What about `pdt`? A preliminary search doesn't turn up any major conflicts.

Alternatively, `pupd` or even `pupdt`? I'd like to try to keep the alias in line with the majority of the other aliases; but it's not necessary.

**Comment by carlosala** [comment]
pupd seems a better option, right?

**Comment by SnoopDraugg** [comment]
> pupd seems a better option, right?

You're right. I'm overthinking it.

**Review by SnoopDraugg — COMMENTED** [review]
Rename pup alias to pupd

**Comment by carlosala** [comment]
Thanks for your contribution!

**Comment by SnoopDraugg** [comment]
> Thanks for your contribution!

Thank you!

**Pull request merged**
