### PR TITLE
Duplicate python.plugin.zsh

### PR DESCRIPTION
**Pull request by alexrf45**
Duplicate for python3

## Standards checklist:

- [ x] The PR title is descriptive.
- [ x] The PR doesn't replicate another PR which is already open.
- [ x] I have read the contribution guide and followed all the instructions.
- [ x] The code follows the code style guide detailed in the wiki.
- [ x] The code is mine or it's from somewhere with an MIT-compatible license.
- [ x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x ] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- [...]

## Other comments:
I would recommend duplicating this plugin to support python3. Sorry this is my first PR... 
...

### CODE REVIEW

**Comment by carlosala** [comment]
First of all, congratulations for your first pull request! 🎉 👏🏻 
Secondly, your PR looks great! We have an issue opened (#10469) talking about that python topic. Do you have troubles using `python` instead of `python3`? Which system do you use?

**Comment by alexrf45** [comment]
> First of all, congratulations for your first pull request! tada 👏🏻 Secondly, your PR looks great! We have an issue opened (#10469) talking about that python topic. Do you have troubles using `python` instead of `python3`? Which OS/distro do you use?

Thank you I really appreciate that! 

I am currently on Debian 11 Bullseye. Yes I do tend to have more issues using python versus python3 especially with deprecation of python in a few security tools I use during research. 

I have more experience with python3. I figured this might be a welcome addition for more novice users or folks that prefer python3.

**Comment by carlosala** [comment]
I think that renaming every `python` to `python3` in omz would be the best idea at this moment, as many people uses Debian and other distros that potentially don't have the `python` binding. Let's ping @mcornella!

**Comment by alexrf45** [comment]
Copy sounds good to me!

**Pull request closed without merging**
