### PR TITLE
Update to Taskwarrior plugin with new aliases

### PR DESCRIPTION
**Pull request by manoelpqueiroz**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

- Corrected the `t` alias syntax to enable its usage;
- Added 49 aliases based on common Taskwarrior commands
- Added one alias to simplify a manual operation.

## Other comments:

This is my first PR ever opened on Github, thank you for allowing me to contribute to the project.

Acknowledging #6571, I have added aliases to the Taskwarrior plugin based on very common commands the program gives us and are listed on their official [documentation](https://taskwarrior.org/docs/commands/). Notable expceptions to this are:

- All standard reports receive a set of three additional aliases to easily filter tasks that are due in the day, week and month.
- Since Taskwarrior version 2.6, the user has the option to "purge" tasks instead of deleting them. This allows users to completely wipe out unwanted data from their program. However, in order to purge a task, one must get its UUID. I have made an alias to easily use the UUIDs of _all_ deleted tasks as the input to the command.

Duplicate aliases that conflict with other plugins are highlighted with comments, please instruct wether they should be renamed or not.

I do not know why the other PR was closed, the thread ended without a clear explanation. Should this implementation not be of the developers' interest, please let me know.

### CODE REVIEW

**Comment by manoelpqueiroz** [comment]
Waiting to check the situation with #11257 to advance.

**Comment by carlosala** [comment]
Hi @manoelpqueiroz! I think we have too many aliases in this PR. We have been following a new [contributing guide](https://github.com/ohmyzsh/ohmyzsh/blob/master/CONTRIBUTING.md#new-plugin-aliases) that encourages to add not many aliases to omz. Because of this, I'd ask to to remove most of them.
Thanks!

**Comment by mcornella** [comment]
Agree with Carlo, this is a lot of aliases when there is completion available and you probably don't use all of them on a daily basis. You should also check for not overriding existing commands with something like https://command-not-found.com/.

**Comment by carlosala** [comment]
Closing for the moment as there are too many aliases. Feel free to re-open if you want to continue with this!

**Pull request closed without merging**
