### PR TITLE
feat(wp-cli): add aliases for DB management

### PR DESCRIPTION
**Pull request by veesar**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [ ] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Added aliases for some frequently used 'wp db' commands

## Other comments:

...

### CODE REVIEW

**Comment by veesar** [comment]
Hi @joshmedeski, could you please take a look and see if this is fine? Was planning on updating some of the other commands if this is good.
Thanks!

**Comment by joshmedeski** [comment]
These aliases are clear and concise.

Please make sure to update the [plugin README](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/wp-cli/README.md) to reflect these new aliases.

**Comment by joshmedeski** [comment]
Looks good to me 👍

**Review by joshmedeski — APPROVED** [review]

**Comment by mcornella** [comment]
Thanks!

@joshmedeski I'll add you as plugin maintainer in the `CODEOWNERS` file if that's alright to you. This will mean you'll get automatically mentioned whenever there's a PR that modifies the plugin. Let me know!

**Comment by joshmedeski** [comment]
Add me, I'm happy to help maintain this plugin 😄

**Comment by mcornella** [comment]
Alright done. Thanks!

**Pull request merged**
