### PR TITLE
🚀 feat(git): Add git branch rename alias

### PR DESCRIPTION
**Pull request by otilor**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Updte git.plugin.zsh

## Other comments:

This adds a new alias for renaming a branch

### CODE REVIEW

**Comment by carlosala** [comment]
This should be documented in README.md also

**Comment by humaneguy** [comment]
Ok will dow

**Comment by humaneguy** [comment]
@carlosala Done

**Review by Tjolk072 — COMMENTED** [review]
Thanxxxx a lot for your help!

**Review by Tjolk072 — COMMENTED** [review]
Thanxxxxxxx a lot!

**Comment by humaneguy** [comment]
@Tjolk072 Thanks

**Comment by humaneguy** [comment]
@carlosala Kindly review for potential merge.

**Comment by carlosala** [comment]
There are many PRs opened changing git plugin, so probably it's going to take some time. Sorry about that ;)

**Comment by humaneguy** [comment]
Great. Take your time @carlosala 
Wanna tweet about this PR, tho'
Looks lit to me😇

**Comment by humaneguy** [comment]
Hi @carlosala. PR hasn't been merged, tho'

**Pull request closed without merging**
