### PR TITLE
feat(path): add plugin path(PATH variable operator)

### PR DESCRIPTION
**Pull request by kaivio**
## Standards checklist:
- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:
- add plugins/path/path.plugin.zsh

### CODE REVIEW

**Comment by carlosala** [comment]
In my opinion this plugin is not really needed. Most times you only need to change the path in the `zshrc`, where you can easily add a line `export PATH="/path/to/dir:$PATH"`. Do you usually change the `PATH` variable interactively in the shell? By the way, this can easily be done executing the same line written before (but it's not recommended to do so, as many startup functions depend on `$PATH` and which directories are there).
What's your opinion about it?
Thanks for your contribution! 😊

**Comment by kaivio** [comment]
> Do you usually change the PATH variable interactively in the shell? 

Yes, I often try alpha applications and temporary scripts, execute it in an external directory. Typing command shorter by added PATH, but long-term configuration is not necessary.

**Comment by rwmitchell** [comment]
I manipulate my path as well.  Code I write goes into a project path that further has debug, release, and install components before going into the actual install area.  My tool for that does:

 pathtool -h

  addpath     : add current directory to path
  bugpath   N : use /debug/   in path
  rlspath   N : use /release/ in path
  gldpath   N : use /install/ in path
  cleanpath   : remove missing and duplicate path elements
  delpath   N : remove path
  ordpath O N : re-order path element
  dopath    N : renable path
  gop       N : go to path
  loadpath    : load saved paths
  nopath    N : disable path
  showpath    : show paths

the commands that "change" the path only outputs the new path to the terminal, using an alias wrapper to set it for the current shell.

Many of the options get the path to change by using a program name and finding with path element it exists in.

image

**Comment by mcornella** [comment]
You can run these by using the full or relative path, you don't need to change `$PATH`. For example:
```console
$ wget https://example.com/some-command -O ~/Downloads
$ chmod +x ~/Downloads/some-command
$ ~/Downloads/some-command <arguments>
```

You could also add the current working directory to the path with
```sh
path+=(.)
```
and then you can run commands in the current directory without prefixing with `./` (note that if you do this, the recommended approach is to put the current working directory last, so as to not override system commands.

----

Regardless of that, while I appreciate the contribution this is not a thing that common users will need. You can still set it up as a custom plugin, see [adding a new plugin](https://github.com/ohmyzsh/ohmyzsh/wiki/Customization#adding-a-new-plugin). You can also create a repository for the plugin and add it to the list of [External plugins](https://github.com/ohmyzsh/ohmyzsh/wiki/External-plugins).

**Pull request closed without merging**
