### PR TITLE
feat(fig): add plugin for Fig

### PR DESCRIPTION
**Pull request by marcofranssen**
Adds autocomplete for [Fig](https://fig.io)

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Add [Fig](https://fig.io) autocompletion plugin

### CODE REVIEW

**Comment by robbyrussell** [comment]
Would be great to get some people to help us test this out.

**Comment by mcornella** [comment]
This would be better if the output from `fig completion zsh` is run each time, kinda like the `deno`, `cargo` or `rustup` plugins (note that the logic on these is bound to change, so it's done properly).

**Comment by marcofranssen** [comment]
> This would be better if the output from `fig completion zsh` is run each time, kinda like the `deno`, `cargo` or `rustup` plugins (note that the logic on these is bound to change, so it's done properly).

Much better indeed. Thanks for sharing. I have updated the plugin to be like that.

**Comment by mcornella** [comment]
Looks great, thanks!

**Comment by lomasz** [comment]
Is it typo in this line:
```bash
fig completions zsh >| "$ZSH_CACHE_DIR/completions/_fig" &|
``` 
?

Message after enabling plugin and rerun console:
```
Error: unknown command "completions" for "fig"

Did you mean this?
	completion

Run 'fig --help' for usage.
```

**Comment by mcornella** [comment]
Fixed, thanks for catching that!

**Comment by tomasp1189** [comment]
I have added the plugin but it doesn't seem to work. Other than adding `fig` to the plugins array in my `.zshrc` file, do I have to do anything else? BTW I installed fig before setting up Oh My Zsh, not sure if this is relevant.

**Comment by mcornella** [comment]
The plugin only adds completion, you still need the initialization code that fig adds automatically to .zshrc.

**Comment by tomasp1189** [comment]
Awesome! I rerun the install script option provided by fig) and it works! Thanks!

**Pull request merged**
