### PR TITLE
Add Deno completions

### LINKED ISSUE #9165: add deno plugins
i have been using <a href='https://deno.land'> Deno</a> for a long time, to make it easier for users like me in the present or future, it is better to bring support to Deno.

### PR DESCRIPTION
**Pull request by CallMeLaNN**
## Standards checklist:

- [x] The PR title is descriptive.
- [ ] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Add completions from `deno completions zsh `

## Other comments:

Elegant way of adding completions inspired by helm plugin, it will respect user Deno version.

There is an attempt to add this plugin before #9591 and #9363 but mostly for alias and I fix the script. I can combine those if there is a need for alias since using `zsh-autosuggestions` is good enough.

This should close #9165 too.

### CODE REVIEW

**Comment by carlosala** [comment]
Would be interesting to add some aliases. Could you copy my aliases in #9591 and add to the deno.plugin.zsh? I revised that they don't create conflicts!

**Comment by CallMeLaNN** [comment]
@carlosala I just check the `di` alias conflict with debian plugin, `dr` and `dt` conflict with dotnet and drush plugins.

I'm not sure how this alias being unique here, either this is ok or require conflict free with other plugins?
Probably maintainers can suggest and get this PR merged.

**Comment by carlosala** [comment]
True, I just revised the compatibility with apps, nit with other plugins. I tried your completion funcion and it doesn't work... The command for Deno is `deno completionS zsh`, with the s. But it neither works.

**Comment by CallMeLaNN** [comment]
My bad, just fix it.

I think Deno doesn't give much attention or maybe we need to wait for sometime.

**Comment by carlosala** [comment]
This completion function doesn't work for me. It throws the error:
```_arguments:comparguments:325: can only be called from completion function```

**Comment by mcornella** [comment]
Superseeded by #9847.

**Pull request closed without merging**
