### PR TITLE
feat(plugins): add plugin for `deno`

### LINKED ISSUE #9165: add deno plugins
i have been using <a href='https://deno.land'> Deno</a> for a long time, to make it easier for users like me in the present or future, it is better to bring support to Deno.

### PR DESCRIPTION
**Pull request by carlosala**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

I added completion and some useful aliases for `deno`. The completion function caches the user's version of `deno` and it copy the shell completions to `$ZSH/completions`, as @mcornella requested in #9591.
This closes #9363 #9591 #9681 PR because this one improves them. It also closes #9165 issue.
It would be great to have some feedback about the completion function, for me is working but it's the first time that I tried something like this. I got some code from #9557.

Thanks!

### CODE REVIEW

**Comment by carlosala** [comment]
Hi!
I changed radically the code in this second version, it does the same with less code so, better!
Could someone revise the plugin?
Thanks @mcornella for all your work!

**Comment by mcornella** [comment]
Hmm this uses `$ZSH/completions` which is a git tracked path and bound to be removed from the codebase, can you do something akin to the `npm` plugin which uses `$ZSH_CACHE_DIR` instead?

**Comment by carlosala** [comment]
Hi @mcornella!
I'm very noob on this, but I have red the output of `npm completion` and it's quite different to the output of `deno completions zsh`. If you have time, could you revise how to create a proper completion function? How can I load the output of `deno completions zsh` without saving a `_deno` file in a directory that is in the `$fpath`?
Thanks!

**Comment by mcornella** [comment]
Hmm you're right. Maybe put it in the same plugin folder and add a .gitignore, that seems more organized than using the phantom completions folder.

**Comment by carlosala** [comment]
Hey @mcornella. It's done!

**Comment by mcornella** [comment]
Thanks Carlo!

**Comment by carlosala** [comment]
A tu! @mcornella

**Pull request merged**
