### PR TITLE
ssh-agent: improvements

### PR DESCRIPTION
**Pull request by nunojpg**
Replaces #5585 

Comments are welcomed. In particular for abd0450 this should be considered to be provided directly by the plugin load framework.
I mean, it could be a option to mark plugins as non reentrant and oh-my-zsh would implement a mutex for those.

### CODE REVIEW

**Comment by robinwolny** [comment]
👍

**Comment by antoniusostermann** [comment]
👍 Would be awesome to have this!

**Comment by nunojpg** [comment]
@mcornella shall I rebase?

**Comment by mcornella** [comment]
If you can wrap your head around the recent changes go ahead. Otherwise I have it in my notes to adapt it for the new version.

**Comment by nunojpg** [comment]
@mcornella there you go.

**Review by robbyrussell — APPROVED** [review]
Am good to finally get this moving forward

**Comment by hjpotter92** [comment]
this leads to infinite loop on termux since the sandbox doesn't have access to /tmp and the path had been hardcoded.

```
+/data/data/com.termux/files/home/.oh-my-zsh/oh-my-zsh.sh:107> plugin=ssh-agent   +/data/data/com.termux/files/home/.oh-my-zsh/oh-my-zsh.sh:108> [ -f /data/data/com.termux/files/home/.oh-my-zsh/custom/plugins/ssh-agent/ssh-agent.plugin.zsh ']'   +/data/data/com.termux/files/home/.oh-my-zsh/oh-my-zsh.sh:110> [ -f /data/data/com.termux/files/home/.oh-my-zsh/plugins/ssh-agent/ssh-agent.plugin.zsh ']'          +/data/data/com.termux/files/home/.oh-my-zsh/oh-my-zsh.sh:111> source /data/data/com.termux/files/home/.oh-my-zsh/plugins/ssh-agent/ssh-agent.plugin.zsh            +/data/data/com.termux/files/home/.oh-my-zsh/plugins/ssh-agent/ssh-agent.plugin.zsh:1> lockdir=/tmp/oh-my-zsh-ssh-agent.lock                                        +/data/data/com.termux/files/home/.oh-my-zsh/plugins/ssh-agent/ssh-agent.plugin.zsh:3> true                                                                         +/data/data/com.termux/files/home/.oh-my-zsh/plugins/ssh-agent/ssh-agent.plugin.zsh:4> mkdir /tmp/oh-my-zsh-ssh-agent.lock                                          +/data/data/com.termux/files/home/.oh-my-zsh/plugins/ssh-agent/ssh-agent.plugin.zsh:9> sleep 0.1                                                                    +/data/data/com.termux/files/home/.oh-my-zsh/plugins/ssh-agent/ssh-agent.plugin.zsh:3> true                                                                         +/data/data/com.termux/files/home/.oh-my-zsh/plugins/ssh-agent/ssh-agent.plugin.zsh:4> mkdir /tmp/oh-my-zsh-ssh-agent.lock                                          +/data/data/com.termux/files/home/.oh-my-zsh/plugins/ssh-agent/ssh-agent.plugin.zsh:9> sleep 0.1
```

**Comment by TheTechRobo** [comment]
he reverted the merge

**Comment by robbyrussell** [comment]
@hjpotter92 How is this looking after an omz update?

**Comment by hjpotter92** [comment]
> @hjpotter92 How is this looking after an omz update?

did a git pull, the recent master branch still has the lockfile generation code: https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/ssh-agent/ssh-agent.plugin.zsh



> he reverted the merge

i don't think the revert got merged back: https://github.com/ohmyzsh/ohmyzsh/compare/revert-6309-ssh

**Comment by tony** [comment]
@robbyrussell Did this revert get pushed?  I don't think it's in yet

This breaks zinit for me completely, I think. I'm not sure how to use the old ref with `snippet`

https://github.com/tony/.dot-config/blob/1dc5a15/.zshrc#L56

I'm not quite sure why it breaks - no errors. It just hangs the terminal.

**Comment by mcornella** [comment]
Reverted the change.

**Pull request merged**
