### PR TITLE
feat(kubectl): add aliases for replicasets

### PR DESCRIPTION
**Pull request by esemeniuc**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Add `kdrs` alias for describing replicasets
- Update `kgrs` to allow grepping for `replicaset` more easily

### CODE REVIEW

**Comment by esemeniuc** [comment]
Any status update?

**Comment by carlosala** [comment]
I think both `replicaset` and `rs` are just the same thing, it's an alias, as far as I see in the `kubectl` docs. So the first alias renaming does not make so much sense, at the end it will do the same thing.

**Comment by esemeniuc** [comment]
Yes, that is correct. The reason to replace line 105 is to grep the list of aliases more easily. Line 106 is the important addition, since there is no quick shortcut to describe a replicaset

**Comment by esemeniuc** [comment]
Sorry for the delay, updated now!

**Pull request merged**
