### PR TITLE
feat(archlinux): add support for aura AUR helper

### PR DESCRIPTION
**Pull request by ratijas**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

Arch Linux plugin: add support for aura AUR helper.

## Other comments:

~This is draft PR. We are yet to settle on some aliases.~

Related issue in aura repository: https://github.com/fosskers/aura/issues/675

### CODE REVIEW

**Comment by ratijas** [comment]
There's nothing more I'd like to add.

Refactoring change deserves its own pull request & a proper review process, so here it goes: #9546

**Comment by ratijas** [comment]
Bump.

**Comment by mcornella** [comment]
Merged #9546. Can you rebase?

**Comment by ratijas** [comment]
> Merged #9546. Can you rebase?

Let's see…

**Comment by ratijas** [comment]
Rebased (or rather cherry-picked).

**Pull request merged**
