### PR TITLE
Replace `.` aliases with as-you-type expansion

### PR DESCRIPTION
**Pull request by dimitriye98**
Replace aliases:
- `...`
- `....`
- `.....`
- `......`

with as-you-type auto-expansion.

### CODE REVIEW

**Comment by robbyrussell** [comment]
Out of curiosity, how much quicker/slower is this?

**Comment by dimitriye98** [comment]
Latency-wise, there doesn't seem to be any. It's definitely easier to grok how many levels you'll be jumping up, but admittedly, the one downside is that you need to delete 3 characters to undo a level rather than 1. I personally prefer it to aliases, since it gives more visual feedback.

**Comment by dimitriye98** [comment]
If you want I can pull request it as a plugin instead of a mod to the core.

**Comment by mcornella** [comment]
Hi @dimitriye98, this is cool but it doesn't take into account the type of dots being typed: if it's a route it's ok, but everything else should be expanded. So for instance if I'm typing `echo to be continued...` it will be expanded into `echo to be continued../..` which is not what I'd expect at all. 

The good news is that I have an alternative proposal: use the logic in [this blog post](http://blog.patshead.com/2011/07/automatically-expanding-zsh-global-aliases-as-you-type.html) and adapt it to only expand `...` aliases.

**Comment by robbyrussell** [comment]
We'll close this given how long it's been pending more discussion for quite some time.

**Pull request closed without merging**
