### PR TITLE
Mercurial: changed prompt_info to hg_get_id

### PR DESCRIPTION
**Pull request by abaez**
I propose this pull request since it allows for more mercurial repository details and allows to run slightly faster than before. 

When using the mercurial plugin, it tended to have certain slowdowns with retrieval of (heavy) branch status. This was due both to the multiple check calls of `$(in_hg)`, when using `$(hg_prompt_info)`, and to the programming of the `hg branch` command in mercurial.

The `hg id` command has a tendency to be quicker in the callback and, as a bonus, allows for greater detail to a mercurial repository status. I think the `$(hg_get_id)` is better suited for mercurial branching since the command can allow for multiple status outputs like `changeset`, `branch`, and `bookmarks`. It also gives a quick status reference change to the repository when in use.

As such, I took the liberty to truncate the multiple check calls and to also replace the `$(hg_get_branch_name)` function with `$(hg_get_id)` for `$(hg_prompt_info)`.

### CODE REVIEW

**Comment by aerickson** [comment]
I use hg bookmarks primarily and this change made the mercurial plugin more more useful. Thanks. :)

**Comment by robbyrussell** [comment]
@aerickson would you be open to rebasing this for us?

**Comment by aerickson** [comment]
Yeah, absolutely. The `in_hg` checks have already been removed on master, so there's not much left.

https://github.com/ohmyzsh/ohmyzsh/compare/master...aerickson:pr_4229_rebase

Let me know if you'd like a new PR or how to proceed. Thanks!

**Comment by TheTechRobo** [comment]
What they want I think is to force-push this existing PR to your new commit.

**Comment by aerickson** [comment]
Yeah, GH has the feature that allows maintainers to push to a PR, but I'm not a maintainer and it's not my PR.

**Comment by TheTechRobo** [comment]
Oops, didn't notice you weren't the author!

**Pull request closed without merging**
