### PR TITLE
add support to `take' for taking remote urls

### PR DESCRIPTION
**Pull request by mgalgs**
Download, extract, and cd into the resulting directory.

### CODE REVIEW

**Comment by mgalgs** [comment]
Any interest here?  I've been using this for about 1.5 years now and it's quite convenient.

**Comment by TheTechRobo** [comment]
What's the sattus  on this PR, other than conflicts?

**Comment by mgalgs** [comment]
Rebased. I've been using this for nearly 8 years now :exploding_head: :exploding_head:, it's incredibly handy.

**Review by TheTechRobo — APPROVED** [review]
LGTM, mostly! An https://github.com url and git:// urls fdid not get recognised. Did not test git@ ssh connections. Tarballs work (tested with https://mirrors.edge.kernel.org/pub/software/scm/git/git-0.01.tar.gz).

**Comment by mgalgs** [comment]
> An `https://github.com` url and git:// urls fdid not get recognised.

Can you give some example urls that didn't work?

Here's a `git://` url:

```
❯ take git@github.com:ohmyzsh/ohmyzsh.git
Cloning into 'ohmyzsh'...
remote: Enumerating objects: 26135, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 26135 (delta 8), reused 16 (delta 6), pack-reused 26113
Receiving objects: 100% (26135/26135), 7.66 MiB | 10.70 MiB/s, done.
Resolving deltas: 100% (13079/13079), done.
```

and an https://

```
❯ take https://github.com/ohmyzsh/ohmyzsh.git
Cloning into 'ohmyzsh'...
remote: Enumerating objects: 26135, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 26135 (delta 9), reused 15 (delta 6), pack-reused 26112
Receiving objects: 100% (26135/26135), 7.60 MiB | 19.42 MiB/s, done.
Resolving deltas: 100% (13095/13095), done.
```

**Comment by TheTechRobo** [comment]
Seems to require appending ".git" to the end of the url which i nromally don't do.

image

**Comment by mgalgs** [comment]
Yes it uses the `.git` "suffix" to determine whether to use `curl` or `git` to fetch the resource.

**Comment by TheTechRobo** [comment]
@mcornella Thoughts on this PR? Does it require more testers?

**Review by robbyrussell — APPROVED** [review]

**Comment by mattiasflodin** [comment]
How does this alias work? It should be documented. The [wiki](https://github.com/ohmyzsh/ohmyzsh/wiki/Cheatsheet) still just says that take creates a directory without mentioning the URL magic. Can I clone a git repository into any path somehow or does it always end up in the PWD??

**Comment by mgalgs** [comment]
@mattiasflodin I've submitted a Wiki PR for this over here [1].

To answer your question, yes, it always goes into CWD.

[1] https://github.com/ohmyzsh/wiki/pull/16

**Comment by mgalgs** [comment]
Example usage:

```
cd /tmp
take https://github.com/ohmyzsh/ohmyzsh.git
# you are now inside a directory called ohmyzsh
```

**Comment by mattiasflodin** [comment]
@mgalgs very appreciated, thank you!

**Pull request merged**
