### PR TITLE
[Plugins] sprunge alike as sprunge is out of order

### PR DESCRIPTION
**Pull request by ahanjrah**
Sprunge is not working per https://github.com/rupa/sprunge/issues/43 and https://github.com/rupa/sprunge/issues/45

ix.io is a similar service, can be found at: http://ix.io

### CODE REVIEW

**Comment by etu** [comment]
https://ptpb.pw/ is also nice (source here <https://github.com/ptpb/pb>). One benefit over ix.io is https :-)

**Comment by mcornella** [comment]
sprunge seems to be working as of today, but ix.io could be useful as well. Seems though that [their client](http://ix.io/client) is better because it uses all of the features of the service. Can you use that instead and add a basic README?

> https://ptpb.pw/ is also nice (source here https://github.com/ptpb/pb). One benefit over ix.io is https :-)

[This one's dead now](https://github.com/ptpb/pb/issues/246).

**Comment by etu** [comment]
@mcornella Yeah... Well aware of that, and it's sad :(

https://github.com/etu/webpaste.el/commit/7345c5f62d5cff4d84379eaf5dc8b2bb8bc4f99c

Thanks anyways though :)

**Comment by mcornella** [comment]
> sprunge seems to be working as of today, but ix.io could be useful as well. Seems though that [their client](http://ix.io/client) is better because it uses all of the features of the service. Can you use that instead and add a basic README?
> 
> > [ptpb.pw](https://ptpb.pw/) is also nice (source here [ptpb/pb](https://github.com/ptpb/pb)). One benefit over ix.io is https :-)
> 
> [This one's dead now](https://github.com/ptpb/pb/issues/246).

Closing due to inactivity.

**Pull request closed without merging**
