### PR TITLE
feat(starship): create plugin

### PR DESCRIPTION
**Pull request by axieax**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Add starship prompt as a zsh plugin

## Other comments:

...

### CODE REVIEW

**Comment by carlosala** [comment]
Hi!
Did you tested it? In their website they recommend to evaluate the script at the end of the zshrc. Probably it may have problems with omz initialization of themes and that kind of things.
Thanks!

**Comment by axieax** [comment]
Hi, I've tested this and it seems to work fine without a ZSH_THEME set. Perhaps I can add a clarification in the README to ensure this.

**Comment by axieax** [comment]
@carlosala updated README with this clarification :D

**Comment by axieax** [comment]
Hi @carlosala could you please review this? Thanks!

**Pull request merged**
