### PR TITLE
feat: Add plugin for OpenTofu 

### PR DESCRIPTION
**Pull request by chenzejun**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:
Add plugin for OpenTofu which is a fork of Terraform that is open-source, community-driven

Migrate completion ability form Terraform plugin with some update for Opentofu, such as descrptions
Use different alias from Terraform plugin to avoid conflict(`alias tt='tofu'`  vs. `alias tf='terraform'`)
Add three useful alias for refresh(`alias ttr='tofu refresh'`), test(`alias ttt='tofu test'`) and workspace(`alias ttws='tofu workspace'`) command

## Other comments:

...

### CODE REVIEW

**Review by miketheman — APPROVED** [review]

**Comment by Jitsusama** [comment]
I'm definitely interested to see this happen!

**Comment by mcornella** [comment]
Hi @chenzejun, this looks very nice and almost ready to merge, and there is strong support for it.

I have one question though in regard to the completion, where is this from? I haven't seen it anywhere else, and I can't see opentofu bundling it either. I'm hesitant to merge it this way over just doing

```sh
complete -C tofu tofu
```

which is the bash method and works for zsh as well\*, since the zsh way has to be kept up to date with the changes to `tofu`.

Is this just a rework of the completion in the terraform plugin? I've tested the `complete` method and it seems to do the same, minus the descriptions, so for maintainability I would rather go with the `complete` version.

\* After doing `bashcompinit`, which we do by default in Oh My Zsh.

**Comment by mcornella** [comment]
Alright, made several improvements based on https://github.com/ohmyzsh/ohmyzsh/pull/12285#issuecomment-2226978526.

**Review by carlosala — APPROVED** [review]
LGTM!🚀

**Pull request merged**
