### PR TITLE
add new alias to clear cache of pacman and yay together

### PR DESCRIPTION
**Pull request by shosseinib**
## Standards checklist:

- [X] The PR title is descriptive.
- [X] The PR doesn't replicate another PR which is already open.
- [X] I have read the contribution guide and followed all the instructions.
- [X] The code follows the code style guide detailed in the wiki.
- [X] The code is mine or it's from somewhere with an MIT-compatible license.
- [X] The code is efficient, to the best of my ability, and does not waste computer resources.
- [X] The code is stable and I have tested it myself, to the best of my abilities.
- [X] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

**Here's the rephrased pull request in Markdown format:**
- Add new alias `allcl` which runs the following commands:

```bash
sudo pacman -Scc; yay -Scc
```

**The semicolon (`;`) is used instead of the ampersand (`&&`) to ensure that the first command runs correctly before the second command is executed.**
- Updated `README.md` for this alias

### CODE REVIEW

**Comment by ratijas** [comment]
> The semicolon (;) is used instead of the ampersand (&&) to ensure that the first command runs correctly before the second command is executed.

That sounds backwards

**Comment by shosseinib** [comment]
> That sounds backwards
What is you suggestion?

**Comment by carlosala** [comment]
Doesn't `yay` already does `pacman -Scc` behind the scenes? I never used `yay`, but at least in `paru` I guess it works that way.

**Comment by ratijas** [comment]
> > That sounds backwards
> 
> What is you suggestion?

The operators you described work the other way than how you presented it. My suggestion would be to use ` && ` ampersand operator because that is the one that actually checks the return value and short-circuits if the left hand side command fails.

**Comment by shosseinib** [comment]
> Doesn't `yay` already does `pacman -Scc` behind the scenes? I never used `yay`, but at least in `paru` I guess it works that way.

You're right I close this PR.

**Pull request closed without merging**
