### PR TITLE
Improve description

### PR DESCRIPTION
**Pull request by 0xEddie**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [ ] The code follows the code style guide detailed in the wiki.
- [ ] The code is mine or it's from somewhere with an MIT-compatible license.
- [ ] The code is efficient, to the best of my ability, and does not waste computer resources.
- [ ] The code is stable and I have tested it myself, to the best of my abilities.
- [ ] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

- Add tool description to plugin README

### CODE REVIEW

**Review by LunarWatcher — CHANGES_REQUESTED** [review]
All four of your edits just add plagiarized content. That's not good in any way. /cc @mcornella (consider slapping all four PRs with the spam label)

**Comment by 0xEddie** [comment]
I've amended each PR to more consisely describe the tool's functionality, based on your incredibly constructive and friendly feedback @LunarWatcher. 

For my future reference, is it best practice to submit a single PR with all 4 file changes, or as I have done with separate PRs for separate plugins?

**Comment by mcornella** [comment]
The PR title is not descriptive and you have not read the contribution guidelines that specify how to properly format the commit message.

You have also spread out the changes across multiple PRs (more specifically, 5 PRs which is the bare minimum for Hacktoberfest). You are making these contributions with bad intent and this is not the spirit of the event, so Olivia's feedback is justified.

I will be closing the rest of the PRs for the same reason.

**Comment by 0xEddie** [comment]
Sorry I don't know what Hacktoberfest is? 
I genuinely just wanted to improve the description of these plugins, so that the next person doesn't have to click through to find out what each tool actually is like I had to.

If I make a new PR condensing the same changes, but adhering to the commit guidelines (sorry again, missed these instructions while skimming) would the PR be accepted? Or would it be discarded still?

**Comment by mcornella** [comment]
My dude.

You made exactly 5 PRs and no more on October 7, on a repository with the Hacktoberfest label.

image

After that you made zero other contributions, and before that you made zero other PRs. You are lucky that I did not label these as spam.

In any case, I will not be discussing further whether these PRs were or were not made with questionable motives.

If you are so interested in getting these in, feel free to submit these changes in a single or multiple commits, as long as their in a single PR.

For the changes to this plugin, this reads better:

```
This plugin adds smart tab completion for [TaskWarrior](https://taskwarrior.org/), a tool for for managing your *to-do's* from the command line.
[empty line]
It uses the zsh tab comp...
```

Good luck

**Pull request closed without merging**
