### PR TITLE
lib: enable diff color

### PR DESCRIPTION
**Pull request by holymonson**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

enable diff color if possible.

### CODE REVIEW

**Comment by mcornella** [comment]
`diff --color=auto` is already the default in my system, what's your `diff` version and in what platform?

**Comment by holymonson** [comment]
> `diff --color=auto` is already the default in my system, what's your `diff` version and in what platform?

diff (GNU diffutils) 3.7 , in both archlinux and macOS.
Anyway, `diff --color=auto --color`, with an extra color option, seems no harm to you?

**Comment by mcornella** [comment]
> Anyway, `diff --color=auto --color`, with an extra color option, seems no harm to you?

I mean that `diff` (without arguments) already adds color automatically if not piped. Does that not happen for you?

**Comment by holymonson** [comment]
No, the default is no color. As stated in https://www.gnu.org/software/diffutils/manual/html_node/diff-Options.html
>--color [=when]
Specify whether to use color for distinguishing different contexts, like header, added or removed lines. when may be omitted, or one of:
> * none Do not use color at all. **This is the default when no –color option is specified.**
> * auto Use color only if standard output is a terminal.
> * always Always use color.
>
>Specifying --color and no when is equivalent to --color=auto.

**Comment by mcornella** [comment]
You're right, it doesn't color it, I probably ran the wrong command. LGTM

**Comment by kattjevfel** [comment]
Since this was merged my shell takes a full 6 seconds to load, not quite sure how to debug this but reverting the commit fixes it.

**Comment by holymonson** [comment]
@kattjevfel Place your alias after loading ohmyzsh libs? Custom settings are usually placed at the end so you can overwrite anything you want.

**Comment by mcornella** [comment]
We should prefix the diff call with `command` to bypass his alias when checking for the color argument.

It might also be a good idea to cache the check like we do in the grep.zsh file.

**Pull request merged**
