### PR TITLE
Change default ZSH_COMPDUMP directory to ZSH_CACHE_DIR

### PR DESCRIPTION
**Pull request by ctranstrum**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Fixes issue #7332
- Approach taken from a comment by @mcornella at https://github.com/ohmyzsh/ohmyzsh/issues/7332#issuecomment-624221366
- Seemed like an easy fix that I was also interested in, so I thought I'd contribute

### CODE REVIEW

**Comment by gaving** [comment]
Any chance of seeing this merged?

Would save setting our own variable such as the workarounds in https://github.com/ohmyzsh/ohmyzsh/issues/7332.

**Review by 53jk1 — APPROVED** [review]

**Comment by tw-space** [comment]
Smart change, I'd like to see this merged too. Is the next action on @ctranstrum?

**Comment by mcornella** [comment]
The blocker for this is that all the previous suggestions to fix completion issues by doing `rm ~/.zcompdump*` will be obsolete. I'm not sure yet how to proceed with this part of the problem.

**Comment by Drumstickx** [comment]
While this push request has been stale for more than a year, I would like to "revive" it for two reasons:

1. I like the idea that applications use commonly agreed upon directories (e.g., `.cache`, `.config`) for their files. Personally, I strive for a minimal amount of dotfiles and -directories directly in my home directory
2. I agree that it would be somehow a breaking change with regards to past documentation. However, sometimes breaking changes are required to move forward and improve mistakes from the past. The longer we wait on this, the more anwers will refer to the "old" location.

**Comment by VikalpRusia** [comment]
+1

**Comment by carlosala** [comment]
It seems like, [as stated in the manual](https://zsh.sourceforge.io/Doc/Release/Completion-System.html#Initialization), compdump file should go in `$ZDOTDIR`, or `$HOME` if it's not defined, as well as all other shell configuration files. We are [already respecting that](https://github.com/ohmyzsh/ohmyzsh/blob/b4f9698733d7b29cc495e649e26fd6c3a5dcfcae/oh-my-zsh.sh#L105), so it should not be changed.
Thanks for your contribution!

**Comment by bavalpey** [comment]
@carlosala 

The manual specifies where these are placed by default. It does not specify where they _should_ go. Not allowing them to use an environment variable or something similar means this violates XDG compliance.

**Pull request closed without merging**
