### PR TITLE
gitfast: update completions (#8894)

### PR DESCRIPTION
**Pull request by tantegerda1**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- update git completions to the current git version

### Steps done:

- update version number in `plugins/gitfast/update`
- run `plugins/gitfast/update`
- test it (`rm ~/.zcompdump*`, restart zsh)
- acknowledge the checklist from githubs pull request template
- modified the PR description to reflect that I acknowledged the checklist from githubs pull request template

## Other comments:

Fixes: #8894

### CODE REVIEW

**Comment by tantegerda1** [comment]
> Please follow our [PL template](https://github.com/ohmyzsh/ohmyzsh/blob/master/.github/PULL_REQUEST_TEMPLATE.md)

Thanks for the heads-up, adapted the PR description.

**Comment by tantegerda1** [comment]
Copy from [a comment on Issue 8894](https://github.com/ohmyzsh/ohmyzsh/issues/8894#issuecomment-662295453) because it is better suited here:

Heads up: this PR might be a little bit naive … I'm not too much into the OMZ internals and know nothing about e.g. possible conflicts of this PRs changes with other git plugins, assumptions about installed git versions etc…

**Comment by mcornella** [comment]
Hi @tantegerda1, we're using v2.16 completions because newer versions require a v2.17 git or newer, see https://github.com/ohmyzsh/ohmyzsh/pull/7918.

**Comment by garymm** [comment]
It seems v2.17 has been out for over 2 years at this point: https://github.com/git/git/releases/tag/v2.17.0

How long does this plugin need to maintain backwards compatibility?

**Pull request closed without merging**
