### PR TITLE
Add two aliases

### PR DESCRIPTION
**Pull request by gai871013**
1.Easier to use `pa` than `artisan`
2.Added `pat` as an alias for `php artisan tinker`

## Standards checklist:

- [x] The PR title is descriptive.
- [ ] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- [...]

## Other comments:

...

### CODE REVIEW

**Comment by mcornella** [comment]
Can you rewrite the PR in English? Also those aliases should be documented in the plugin README.

**Comment by gai871013** [comment]
> Can you rewrite the PR in English? Also those aliases should be documented in the plugin README.

Okey, it has been changed to English, and these aliases has been added to the  README file.

**Comment by mohssineAboutaj** [comment]
why this PR doesn't accepted yet? i need it

**Comment by mohssineAboutaj** [comment]
@gai871013 can you please change the title and follow their rules?

**Comment by mcornella** [comment]
If you still have a need for this, feel free to create a separate PR yourself with these changes while keeping to our contribution guidelines. Some things to consider:

1. Using a descriptive title
2. Fixing the style in the plugin README (e.g. the table formatting)
3. Using commit subjects in line with our convential commits (see CONTRIBUTING.md) -- something like `feat(laravel): add aliases for `artisan` and `artisan tinker` would be a good one.

**Pull request closed without merging**
