### PR TITLE
feat(npm): toggle `npm install` / `npm uninstall` by pressing F2 twice

### PR DESCRIPTION
**Pull request by alexkev**
## Standards checklist:

- [x] The PR doesn't replicate another PR which is already open.
- [x] The PR title is descriptive.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- A simple addition to npm. It allows the user to toggle `npm install` & `npm uninstall` in the command line buffer by hitting F2, F2.

...
Users who have contributed to this file:
 @larson-carter
 @mcornella
 @a-h-i
 @sorin-ionescu
 @oknowton
 @hacfi
 @AlexxNica
 @fabianrios
 @dimensi0n
 @athahersirnaik
 @AntouanK
 @a-r-d

### CODE REVIEW

**Comment by mcornella** [comment]
You described exactly what it does but the most important thing is why? Do you use this often and what problem does it solve?

**Comment by alexkev** [comment]
> You described exactly what it does but the most important thing is why? Do you use this often and what problem does it solve?

Just like the rest it is a shortcut.  

The problem: how much extra time it takes to find the last installed package in the command line buffer and then change "install" to "uninstall" (or vice versa) or type it out.  

The solution: a keyboard shortcut that does it for you. It becomes most handy when you are trying several similar npm packages, switching versions, or are uninstalling, reinstalling, and installing new packages. 

I probably use this once a day or several times a day if I am trying out a few new packages.

**Comment by mcornella** [comment]
Thank you Alex, and apologies for the delay!

**Comment by Manu1400** [comment]
successfully tested on my Mac. thanks you for this feature.

**Comment by Lofty-Brambles** [comment]
How would I go about rewriting this for other package managers like, say, `pnpm`? The issue is with the numerous aliases that occur. [add/install/i, rm/remove/uninstall/un]

**Pull request merged**
