### PR TITLE
refactor(git-groh): Remove dependency for `git_current_branch`

### PR DESCRIPTION
**Pull request by liijunwei**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Remove dependency for `git_current_branch` in `groh` git alias

## Other comments:

...

### CODE REVIEW

**Comment by liijunwei** [comment]
anyone have a moment to take a look? 👀

**Comment by carlosala** [comment]
Hi @liijunwei!
Thanks for your contribution! Why should we remove `git_current_branch` dependency? It's actually really fast, and I don't see why should we do it. Thanks!

**Comment by liijunwei** [comment]
I just realized that `git_current_branch` is in core lib of git, maybe I was wrong

But the main reason is that I find [current implementation for `git_current_branch`](https://github.com/ohmyzsh/ohmyzsh/blob/249c708ed3a4a7a63d16a6e911a46b6fb9623cbd/lib/git.zsh#L96) is too hard to understand, many indirection inside 😵 

Maybe there are some edge cases are the concern, but I'd like to suggest  this for git_current_branch
```
function git_current_branch() {
  git rev-parse --abbrev-ref HEAD
}
```

Another reason is that I prefer this tool have less dependencies(personal taste, coule be ignored 😄 )

**Comment by liijunwei** [comment]
I like git plugin in omz, but I have to unalias it and redefine if myself
image

**Pull request closed without merging**
