### PR TITLE
Adding autoloaded completion plugin for homeshick

### PR DESCRIPTION
**Pull request by arlopurcell**

### CODE REVIEW

**Comment by robbyrussell** [comment]
Hi @arloherrine, can you please include a README file with some usage examples?

**Comment by arloherrine** [comment]
Looking through other comparable completion plugins, I couldn't find any with whole README files that I could use as a template. Maybe adding a comment like this with a link to the project's homepage (which itself links to tutorials with usage examples etc.) is enough?

**Comment by arloherrine** [comment]
ping?

**Comment by TheTechRobo** [comment]
If you just added a readme.md file with the link to the homepage, with a short summary of what it does, I think it would be fine.

**Comment by mcornella** [comment]
The upstream project [already has completion](https://github.com/andsens/homeshick/blob/master/completions/_homeshick). Closing this one, but thanks for the contribution!

**Pull request closed without merging**
