### PR TITLE
feat(aws): support sso profiles

### PR DESCRIPTION
**Pull request by ojongerius**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

aws profiles that use sso are currently not supported, this changes set the profile if an sso url is found

### CODE REVIEW

**Comment by maksyms** [comment]
@ojongerius thank you very much for the PR, it is definitely a great idea, and also, quite relevant. My company moved to SSO recently as well, which made the `acp` function less relevant. With your update, `acp` could be much more powerful!

I've posted a few comments to structure the code slightly clearer - would you mind having a look?

**Comment by ojongerius** [comment]
@maksyms 👋 I don't see any comments?

**Comment by maksyms** [comment]
Look at the "Review" section, the comments are on the code itself.

**Comment by ojongerius** [comment]
Sorry mate, there is not review "Reviewers: No reviews" and https://github.com/ohmyzsh/ohmyzsh/pull/9795/files show no comments.

**Review by maksyms — COMMENTED** [review]
@ojongerius here are the reviews - can you see?

**Comment by ojongerius** [comment]
Awesome, cheers @maksyms, I'll have a look when I find time 👍

**Comment by barakharyati** [comment]
@maksyms can you please also add support to source_profiles with SSO?

**Comment by stuart-warren** [comment]
> @maksyms can you please also add support to source_profiles with SSO?

@barakharyati Can you clarify what you mean here please, I'd also really like this feature and had created a very similar MR before finding 2 others with this requirement from you

**Comment by barakharyati** [comment]
@maksyms  AWS CLI support Assume role Chaining using Source Profile.
Currently, when you use Assume role profile that its source_profile is SSO, the cli cannot detect that and sign in with the Asuume_role profile.
so you need first to run aws sso login with the original sso (source_profile) and then run the command with the assume role profile.

It will be great if we can just run aws sso login with the Assume role Profile. and AWS cli will be able to detect the source profile and use it.

aws config + sh command attached.

**aws config** 
`
[profile sso_source_Profile]
  sso_start_url = https:/d-123456.awsapps.com/start
  sso_region = eu-central-1
  sso_account_id = 123456789
  sso_role_name = 123456789-Zooz-ops-power-user
  region = eu-central-1
  output = json
  duration_seconds = 14400

[profile assume_role_profile]
  source_profile = sso_source_Profile
  role_arn = arn:aws:iam::123456789:role/role2assume
  region = eu-central-1
  duration_seconds = 3600

`
**aws login ** 
`
#current login flow
aws sso login --profile sso_source_Profile
AWS_PROFILE=assume_role_profile
aws s3 ls 

#suggested login flow
AWS_PROFILE=assume_role_profile
aws s3 ls 
`
thx. :)

**Comment by stuart-warren** [comment]
thanks, so you don't need the `--role-session-name` flag on `aws sso login`

**Comment by barakharyati** [comment]
you do because the sso will assume the provisioned role (from the permission set and then use it to assume the IAM role.

**Comment by hans-d** [comment]
what's the status of this PR?

**Comment by maksyms** [comment]
> @maksyms can you please also add support to source_profiles with SSO?

Sure - feel free to create a pull request and we can take it through the process.

**Comment by maksyms** [comment]
@hans-d 

> what's the status of this PR?

There were a few comments and suggestions, which the author was going to look at and implement. The author is probably very busy, and I'm sure when they find the time, the updates will be implemented. Until then, the PR stays Open.

**Comment by ojongerius** [comment]
I'm still swamped with other work and have little use for this atm.

I'll close this PR now and  encourage anyone wanting to use any of the changes (and suggested changes!) in a fresh PR.

**Pull request closed without merging**
