### PR TITLE
feat(ys): show `svn` repository information

### PR DESCRIPTION
**Pull request by mckelvin**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- feat(ys): show svn repo info

@ysmood

### CODE REVIEW

**Comment by mcornella** [comment]
Thanks!

**Comment by szaffarano** [comment]
Hi @mcornella 
I'm using the `ys` theme with `zplug`, and after I updated it I started to get this error

```
zsh: command not found: svn_prompt_info
```
To fix it I have to explicitly install `svn` plugin.  It's possible to fix it in a better way? (for instance, adding a configuration option to "disable" svn prompt?)

Thanks :)

**Comment by ysmood** [comment]
Only enable it if svn is installed.

**Comment by szaffarano** [comment]
Yes, it's what I did, but since I don't need svn support, I wondered whether there is a better solution than installing the svn plugin.
Thanks

**Comment by mcornella** [comment]
You don't need the svn plugin, the `lib/prompt_info_functions.zsh` file adds noop definitions for these so they don't run anything unless the plugin is enabled.

**Comment by szaffarano** [comment]
Thanks @mcornella 
I added
```
zplug "lib/prompt_info_functions", from:oh-my-zsh
```
to my `.zshrc` and it worked

**Pull request merged**
