### PR TITLE
[PLUGINS][GIT]: Adds `git branch -v` alias

### PR DESCRIPTION
**Pull request by theodorosidmar**
Hello there!

I'm a heavy user of `git branch -v`. So, I decided to create `gbv` alias. I hope ou enjoy it!

### CODE REVIEW

**Comment by keithbrianptomo** [comment]
?

**Comment by theodorosidmar** [comment]
@keithbrianptomo ? lol

**Review by 53jk1 — APPROVED** [review]

**Comment by carlosala** [comment]
Hi @theodorosidmar!
I think adding that alias does not add a lot of value, since you only avoid two keystrokes. Going from `gbv` to `gb -v` is almost the same stuff. Even though, if you use it a lot I recommend you add it to your zshrc.
Thanks for your contribution!

**Comment by theodorosidmar** [comment]
I have it! Thank you for your feedback :)

**Pull request closed without merging**
