### PR TITLE
feat(git): add function for `git`

### PR DESCRIPTION
**Pull request by JamesHopbourn**
Signed-off-by: James Hopbourn <jameshopbourn@gmail.com>

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

- feat(git): add function for `git`

## Other comments:

add new function to quicky open file or homepage in browser.

example:
`ghop` open current branch homepage, e.g. master, test, dev
`ghop oh-my-zsh.sh` open oh-my-zsh.sh code page directly
`ghop plugins/git` open git plugin directory page
`ghop Keyboard\ Maestro/README.md` open path with space

support three type of git remote url such as:
- https url: https://github.com/JamesHopbourn/Apple-Automation
- ssh protocol: git@github.com:JamesHopbourn/Apple-Automation.git
- Host config in ssh config file: hopbourn:JamesHopbourn/CompanyPorject.git

### CODE REVIEW

**Comment by mcornella** [comment]
When do you use this?

**Comment by mcornella** [comment]
I asked more about why you use it and how often. This seems like something you'd maybe want integrated with your editor or within GitHub itself, which you can access with the keyboard shortcut `t` within the GitHub UI.

**Comment by Froggo8311** [comment]
Huh.

```
omz pr test 11447
cd ~/.oh-my-zsh
ghop
# computer starts freaking out, acts as if I just ran a fork bomb, crashes my WM, slows down the TTY
```

How the heck

**Comment by carlosala** [comment]
Let's close this. It seems this PR is not getting a lot of traction and there are alternatives to do similar things.
Thanks for your contribution!

**Pull request closed without merging**
