### PR TITLE
feat(plugins): add fnm plugin

### PR DESCRIPTION
**Pull request by sebenik**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Add plugin for [fnm](https://github.com/Schniz/fnm), Fast and simple Node.js version manager.

Similar plugin was attempted but never accepted. Also plugin at #8789 is outdated so I created a new PR.

### CODE REVIEW

**Comment by Schniz** [comment]
Awesome!
fnm provides shell completions. So maybe the plugin could `eval $(fnm completions --shell=zsh)`?

**Comment by sebenik** [comment]
@Schniz great idea, makes it compatible with current installed fnm version.
I'll change it.

**Comment by sebenik** [comment]
Unfortunately output of `fnm completions --shell=zsh` isn't meant to be sourced and adding completions evaluating it is not working.

PR stays unchanged and is ready.

**Comment by mcornella** [comment]
You can follow the same approach as in the [deno](https://github.com/ohmyzsh/ohmyzsh/blob/70ab2928/plugins/deno/deno.plugin.zsh) and [gh](https://github.com/ohmyzsh/ohmyzsh/blob/70ab2928/plugins/gh/gh.plugin.zsh plugins.

**Comment by sebenik** [comment]
@mcornella thanks for the tip. Done.

**Comment by mcornella** [comment]
This needs the `.gitignore` file as well to ignore the generated `_fnm` file.

**Comment by sebenik** [comment]
Tnx, added.

**Pull request merged**
