### PR TITLE
Add plugin zshl 

### PR DESCRIPTION
**Pull request by rishabh96b**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Add plugin named "zshl" 

## Other comments:
- I was looking into the plugins to list basic things like themes and plugins available so that I don't have to dig into repo to find suitable ones so I found a need to add a new plugin. Feel free to suggest a new name though ;)
- The above plugin now has basic functionality to list themes and plugins available in the system to install. You can also list the custom themes and plugins installed/available on the system.

### CODE REVIEW

**Comment by larson-carter** [comment]
There are a few things that need to be addressed here.

1. Should this be named something different? It should since our CLI tool is named omz and this can cause a lot of confusion.
2. The wording [here](https://github.com/ohmyzsh/ohmyzsh/pull/8961/files#diff-e5554d2389157a0f30ad83adc85ce72dR3-R5) is a bit confusing, you also need to be more detailed in the readme on how the user can use this plugin.
3. > This plugin allows you to change list available themes and plugins that can be installed.
It really doesn't do that. It is just running `ls` and displays what themes are available?
4. It does not consider custom themes and plugins? We need to add support for that
5. [This](https://github.com/ohmyzsh/ohmyzsh/pull/8961/files#diff-cdfb925af7ffad47340026b990d86d68R9-R11) needs to be more detailed for the user describing how to actually use the plugin but also keeping it short.

**Comment by rishabh96b** [comment]
Thanks for your feedback @larson-carter ! I will look into it.

**Comment by rishabh96b** [comment]
Hey @larson-carter :wave: 
For the ubuntu-latest test, looks like the the URL is not correct
 ```
The repository 'https://packages.microsoft.com/repos/azure-cli bionic Release' no longer has a Release file.` 
```
The correct URL seems to be 
```
https://packages.microsoft.com/repos/azure-cli/dists/bionic/Release
```
Also please let me know if you prefer a fresh PR for this. I've tried to address your comments in best possible way. Thanks!

**Comment by larson-carter** [comment]
@rishabh96b Hello again. Sorry for the late reply. Yes, if you could make another PR fixing our CI pipelines I would greatly appreciate that!

Tag me in that PR.

Also, tag me here when you want me to review this PR again!

**Comment by mcornella** [comment]
> Hey @larson-carter 👋
> For the ubuntu-latest test, looks like the the URL is not correct
> 
> ```
> The repository 'https://packages.microsoft.com/repos/azure-cli bionic Release' no longer has a Release file.` 
> ```
> 
> The correct URL seems to be
> 
> ```
> https://packages.microsoft.com/repos/azure-cli/dists/bionic/Release
> ```

This is an issue with the ubuntu-latest apt repositories, which sometimes fail and sometimes don't. Don't worry about the failed status.

> Also please let me know if you prefer a fresh PR for this. I've tried to address your comments in best possible way. Thanks!

The PR has become polluted with other commits, it's better to `rebase` against the current main branch instead of merging it, but don't worry about it now. I think it's better to add this functionality to the omz CLI (`lib/cli.zsh`). I have a branch ready for it, if you want I can add you to the co-authors list and let this PR be closed.

**Comment by rishabh96b** [comment]
Sure @mcornella ! It will be a privilege to get this added into the official `omz` cli. Can you mention me in the PR whenever you create one? Would love to look it at it.

**Comment by rishabh96b** [comment]
@mcornella looks like you have mentioned `Co-authored-by: Rishabh Bohra <rishabh.bohra@quicfind.com>` as co-author in your branch which is not me :sweat_smile: . My username is @rishabh96b and email-rishabhbohra01@gmail.com

**Pull request closed without merging**
