### PR TITLE
Add an alias to upgrade-interactive to the latest version

### PR DESCRIPTION
**Pull request by neilime**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Add `yuil` alias : yarn upgrade-interactive --latest

### CODE REVIEW

**Comment by bartekpacia** [comment]
Hi @neilime, I think this is great and useful. 

PS Why so many changes in the README? (I guess the autoformatter kicked in) Could you  force-push to keep the delta as small as possible?

**Comment by neilime** [comment]
Hi @bartekpacia, 

The are so many change sin the readme because the description of the new command "yuil" is longer than the other one so the table lines ending have been increased.

**Comment by bartekpacia** [comment]
OK, thanks for the explanation @neilime 👍

**Comment by mcornella** [comment]
@bartekpacia you can toggle viewing whitespace changes by clicking on the cog in the files tab.

LGTM

**Comment by bartekpacia** [comment]
wow, didn't know about this. Thanks @mcornella!

**Pull request merged**
