### PR TITLE
Add direnv plugin

### PR DESCRIPTION
**Pull request by mosch**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Added a plugin for direnv 

## Other comments:

It's the output of `direnv hook zsh` and should work well for others.

### CODE REVIEW

**Comment by mosch** [comment]
Not sure who can review this. @larson-carter would you be up for checking it 🤞🏻?

**Comment by mosch** [comment]
@dan-lee since you are using the same tools, would you do a verification for me?

**Review by dan-lee — APPROVED** [review]
Totally works for me!

**Comment by larson-carter** [comment]
@mosch 
Sorry for not getting the tag for this PR. I don't know what happened.

I'm going to request @mcornella's input!

**Comment by mcornella** [comment]
I had written an analysis of the different hooks direnv outputs based on the version, but since v2 all are kinda the same, so there's no need to use `source <(direnv hook zsh)`. LGTM

**Review by UglyJoevIne — APPROVED** [review]

**Review by UglyJoevIne — APPROVED** [review]

**Review by herrkochi1995-star — APPROVED** [review]

**Pull request merged**
