### PR TITLE
Add Fastlane plugin

### PR DESCRIPTION
**Pull request by alejandro-isaza**

### CODE REVIEW

**Comment by robbyrussell** [comment]
Could you add a README for this, too?

**Comment by aleph7** [comment]
@robbyrussell added!

**Comment by apocolipse** [comment]
@aleph7 This plugin should check all fastlane options (the list from `fastlane actions`) for completions list, not just available lanes.  As well, it'd be nice to have action options after autocompleting one.  This is useful for all of fastlane's adhoc actions that don't go in a lane (i.e. `register_devices`)
So if i start typing
```zsh
fastlane reg
```
that will fully resolve to 
```zsh
fastlane register_devices
```
With another tab (by calling `fastlane action register_devices`, note no `s` on actions) it should show all options for that action
```
$> fastlane register_devices
devices
devices_file
team_id
username
```
etc.

**Comment by foxundermoon** [comment]
nice

**Comment by jcarroll-mediafly** [comment]
Been using this all the time now! So nice to not have to type out lanes anymore as our projects have quite a few now!

**Comment by marvindanig** [comment]
Is there a status on this plugin's inclusion officially?

**Comment by mcornella** [comment]
I started refining the code but saw that the project already adds completion, which is basically this one. [You can enable it by running `fastlane enable_auto_complete`](http://docs.fastlane.tools/faqs/#enable-tab-auto-complete-for-fastlane-lane-names).

The only thing I'd change is the `completions=` line for a simple `sed`:
```sh
  completions="$(sed -En "s/^\s*lane \:([^ ]+).*$/\1/p" "$file")"
```
as well as adding a return when no Fastfile file is found. I'd be good to submit this to the upstream project.

I'll close this for the time being but if many people are interested it could be done to automatically source the fastlane completion script (I don't have it installed so I don't know how that's done).

Thanks!

**Pull request closed without merging**
