### PR TITLE
feat(poetry): add plugin to provide completion for Poetry

### PR DESCRIPTION
**Pull request by kronion**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Adds a `poetry` plugin that provides tab completion for the [poetry](https://python-poetry.org/) CLI. 

## Other comments:

Based on PR #7353.

@mcornella

### CODE REVIEW

**Comment by carlosala** [comment]
Hi kronion!
The way of loading completion functions has changed a little bit since Marc told to you how to do it. I would recommend you to see how other plugins (such as `deno`, `gh`...) do that and adapt the PR to it.
Thanks!

**Comment by mcornella** [comment]
Yeah, more like the `deno` or `gh` plugins, or even the `rust` plugin which you linked. Sorry if I wasn't more specific after your initial message 😅

**Comment by mcornella** [comment]
Thanks!

**Comment by carlosala** [comment]
@mcornella look at the second part of my review, the `_comps[gh]=_poetry` is still there, should be fixed

**Comment by mcornella** [comment]
ugh damn, sorry

**Comment by mcornella** [comment]
Fixed

**Comment by mcornella** [comment]
More like two because I'm blind af

**Pull request merged**
