### PR TITLE
feat(last-working-dir): log separate `lwd`s for different SSH keys on the same user account

### PR DESCRIPTION
**Pull request by wilkis3**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Modified condition at ```chpwd_last_workind_dir``` and ```lwd```.

### CODE REVIEW

**Comment by mcornella** [comment]
Please explain a bit more. What's the reason behind the change and where does the `$SSH_USER` variable come from, I couldn't find anything about it.

**Comment by wilkis3** [comment]
$SSH_USER is an user environment for SSH.
Sometimes they will used to [log connected SSH keys to auth log](https://forums.aws.amazon.com/thread.jspa?messageID=723107) or [seperate history for different SSH key under one user account](http://screenage.de/blog/2012/02/10/how-to-log-history-and-logins-from-multiple-ssh-keys-under-one-user-account-with-puppet/) 

Do you know a better way to design this feature?

**Comment by mcornella** [comment]
Can you document this in the README, with a little description of the setup to enable `SSH_USER` env variables?

**Comment by wilkis3** [comment]
> Can you document this in the README, with a little description of the setup to enable `SSH_USER` env variables? Also a short sentence to explain the reason (i.e. different people using the same user).

Yes, I committed the documentation to the README with a short use case and manual.

**Comment by mcornella** [comment]
Alright, looks good now. Thanks for your contribution!

**Pull request merged**
