### PR TITLE
fix(bgnotify): don't require accessibility perms in macos

### PR DESCRIPTION
**Pull request by tresni**
Changes in #11256 undid #10318 which prevented unnecessary permission prompts.

By refactoring the `bgnotify_termid` check to instead look to see if the terminal application is visible and that its current foreground window is the window bgnotify was invoked from, we require *no* special permission for Automation or Accessibility. This check is seen as the terminal application controlling itself.

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- change MacOS appId lookup to see if terminal is frontmost and our current window is visible

### CODE REVIEW

**Comment by AuroraWright** [comment]
+1, as is I need to reapply this manually every time the plugin is updated

**Comment by carlosala** [comment]
@AuroraWright could you please open a PR with the conflicts solved? We can review it there!

**Comment by tresni** [comment]
Didn't know there were conflicts now. I can update it

**Comment by AuroraWright** [comment]
[oh-my-zsh.patch](https://github.com/ohmyzsh/ohmyzsh/files/13733720/oh-my-zsh.patch)
Have been using this without issues for a while now

**Comment by tresni** [comment]
Sorry for the delay @carlosala , I've now merged all the changes from master. I did rename some functions to prevent unintended overrides (e.g. if someone had a `find_sway_appid` already defined.)

**Review by carlosala — APPROVED** [review]
LGTM!

**Comment by carlosala** [comment]
Thanks for your contributions!

**Pull request merged**
