### PR TITLE
feat(git): introduce `grbia` alias for `git rebase --interactive --autosquash`

### PR DESCRIPTION
**Pull request by Upsylonbare**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

Add an alias for `git rebase --interactive --autosquash`

## Other comments:

I am a unsatisfied user of the `grbi` alias as a use it everyday with the option `--autosquash`.
Hence this PR introduce the alias that can faster my everyday work process. I am sure it can helps other users too.

### CODE REVIEW

**Comment by larson-carter** [comment]
Just a note/reference. We typically do not implement more alias. 

Simply spoken we typically dont merge these request unless it is a widespread complaint, and it allows for more interactions/speed.

**Comment by larson-carter** [comment]
@Upsylonbare the information is mostly from our discord server.

We don't want to have it overloaded with aliases, unless it is a new versioning to the core software/packages or if it is a commonly utilized one via community engagement.

If you want - You can leave the PR open and promote it in the discord server (Follow the rules), or you can use other formats to get a community behind it.

I personally consider this a "nested alias" meaning it uses multiple flags which in general means lesser use.

**Comment by carlosala** [comment]
We had a similar situation in this PR https://github.com/ohmyzsh/ohmyzsh/pull/9451#issuecomment-1727402970.
The good thing is that you can configure autosquash in your gitconfig if you use it.
Thanks!

**Comment by Upsylonbare** [comment]
Thanks, didn't know that !

**Pull request closed without merging**
