### PR TITLE
Add aliases for systemd --user start/stop/enable/..

### PR DESCRIPTION
**Pull request by lislon**
Added new aliases: 

`sc-user-start <service>` means `systemctl --user start <service>`

Avaliable actions: `start`, `stop`, `status`, `enable`, `disable`, `edit`

### CODE REVIEW

**Comment by sachin21** [comment]
:+1:

**Comment by thuandt** [comment]
:+1:

**Comment by robbyrussell** [comment]
@lislon could we get a rebase on this?

**Comment by mcornella** [comment]
Fixed by #6661

**Pull request closed without merging**
