### PR TITLE
fix(git): fix fallback to develop branch if `master` not found

### LINKED ISSUE #11964: `gbda` no longer works when the default branch is called something other than main, trunk, mainline, default
### Describe the bug

When running `gbda`, I now get:

```
client git:(develop) gbda            
fatal: Not a valid object name master
fatal: not a valid object name -m
fatal: unknown commit master
...more of the same in a loop
```

This is probably caused by https://github.com/ohmyzsh/ohmyzsh/pull/11948

### Steps to reproduce

1. Start a repo with a default branch named, say, "develop"
1. Enable plugin 'git'
1. Run `gbda`
1. 💥 

### Expected behavior

It should delete all merged and squash-merged branches.

### Screenshots and recordings

_No response_

### OS / Linux distribution

macOs 13.6

### Zsh version

5.9

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mcornella**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

- Return error code if no main or develop branch were found
- Fall back to `git_develop_branch` if `git_main_branch` was not found in `gbda` function

## Other comments:

Fixes #11964

### CODE REVIEW

**Review by carlosala — APPROVED** [review]
LGTM!
It indeed fixes the issue for me.
It might be nice maybe to default to `main` instead of `master`, seems to be more common nowadays.

**Comment by LunarWatcher** [comment]
I wouldn't recommend hard switching from master to main. Both are still widely used. Consider checking both by default instead

**Comment by carlosala** [comment]
@LunarWatcher I was talking about the branch name we output if no one is found.

**Comment by mcornella** [comment]
I'd rather not over-rely on the default here and not introduce a breaking change if it's possible, so I'll merge it directly.

Thanks for the review!

**Pull request merged**
