### PR TITLE
Create aliases for npm plugin

### PR DESCRIPTION
**Pull request by hjpotter92**
Add the following 3 aliases:
- npmvM
- npmvm
- mpmvp

To assist in versioning the project

### CODE REVIEW

**Comment by slavaGanzin** [comment]
I suggest to separate npm completions and aliases. 
Generally I can't get why you need them if you have awesome zsh completion...

**Comment by hjpotter92** [comment]
@slavaGanzin zsh completion requires me to type in `npm ve<tab>` which takes ~2s on my system. There is no completion yet for the `version` subcommand completion. So, I won't be able to complete them to `version major` etc.

**Comment by slavaGanzin** [comment]
@hjpotter92 just curious. Why it takes 2s?

**Comment by hjpotter92** [comment]
@slavaGanzin nearly 30 active plugins, a few of my own precmd etc. listeners, old laptop, some other factors I don't know about!

**Comment by mcornella** [comment]
It's probably the node process starting up after starting the computer and caching files.

Unfortunately there is currently no way to separate aliases from completion. If you just want the completion, perhaps you can just add the zsh completion to your zshrc. From [npm/completion.sh](https://github.com/npm/npm/blob/master/lib/utils/completion.sh):

```zsh
  _npm_completion() {
    local si=$IFS
    compadd -- $(COMP_CWORD=$((CURRENT-1)) \
                 COMP_LINE=$BUFFER \
                 COMP_POINT=0 \
                 npm completion -- "${words[@]}" \
                 2>/dev/null)
    IFS=$si
  }
  compdef _npm_completion npm
```

**Pull request closed without merging**
