### PR TITLE
ci(dependencies): pass app token properly

### PR DESCRIPTION
**Pull request by carlosala**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

Bugfixes of #12109:

- Pass `GH_TOKEN` properly.
- Author commits as the bot (displayed correctly on Github UI)
- Use bot token as well for `project.yml` workflow
- Fix `tmp` dir

### CODE REVIEW

**Comment by carlosala** [comment]
PRs generated by this branch: #12127 #12128

**Comment by carlosala** [comment]
We need to review carefully before merging why submodules are created when generating the PRs. See changed files for #12127 and #12128

**Comment by mcornella** [comment]
I believe the submodule stuff is because of the python script not getting a valid `TMP_DIR` path, therefore creating the remote repository in the local directory.

This should be getting the value from `RUNNER_TEMP` but apparently it's not available from `env`. The docs I used for building that are in https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables.

**Comment by carlosala** [comment]
@mcornella you're right! Fixed, we can merge this PR! 🚀 
FYI PRs generated are #12133 #12134

**Review by mcornella — APPROVED** [review]
LGTM!

**Pull request merged**
