### PR TITLE
fix(docker): only generate completion for docker >23

### PR DESCRIPTION
**Pull request by carlosala**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [ ] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

### CODE REVIEW

**Comment by YHYJ** [comment]
Why only generate completion for docker > 23, `docker version --format '{{.Client.Version}}` causes docker.service to start with terminal, it should have been started by docker.socket when running docker

**Comment by carlosala** [comment]
@YHYJ `docker completion zsh` cli command only exists for docker >23

**Comment by sdondley** [comment]
I'm not sure this patch was a very good idea. Looks like docker engine version 23 is just a few months old and _docker file can get generated from sources available on GitHub. And the code completion file generated by `docker completion zsh` is very old and does not complete at all for many subcommands, at least on macOS running latest version of Ventura (13.4).

**Comment by YHYJ** [comment]
I don't think `docker version --format '{{.Client.Version}}'` command should be used, this caused docker.service to start unexpectedly

**Comment by carlosala** [comment]
@YHYJ does `docker --version` start also the service for you?

**Comment by carlosala** [comment]
@sdondley docker folks are switching to cobra v2 completions, generated by `docker completion zsh`. As it's new, it'll keep improving more and more. For example, it allows to have completion for `docker compose`, `docker buildx`, and other CLI plugins.
If you want to have another completion, you can of course download any script you want and add it to a directory present in `$fpath`/

**Comment by sdondley** [comment]
OK, but if I have an older version of docker on the machine, this new version of the plugin won't work at all and even if I have a newer version, it will not work at all for many subcommands. Seems to me you should wait until it's at least as good as the old version before using `docker completion zsh` don't you think?

**Comment by carlosala** [comment]
@sdondley I see your point, but the new version has that CLI plugins completion that the old doesn't, and the old one hasn't been updated for 4 years and the repo has been archived.

**Comment by sdondley** [comment]
@carlosala The new version is missing at least half the subcommands the "old" completion script and it also has no subcommand description.  And the "old" one is actually very up to date and was updated just last month: https://github.com/docker/cli/blob/7d723e2ba7b8607cf9ca5b3ea541f1ce60c700ec/contrib/completion/zsh/_docker#L6

At any rate, I will not be using your version of the docker plugin and will be overriding it with the older version. But at a minimum, I recommend adding something to the README that explains why the new version is crippled until the new completion script automation feature with Cobra is implemented properly and how people can use the old version of the docker plugin to get better completion until that happens.

**Comment by YHYJ** [comment]
> @YHYJ`docker --version`还为您启动服务吗？

Yes, `docker` will make docker.socket start docker.service

**Comment by carlosala** [comment]
Then we can't workaround that, we need to assess the version to see whether or not we can generate the completion script.

**Comment by ondra-m** [comment]
Is there a way how to get completion for older docker using latest omz please?

**Pull request merged**
