### PR TITLE
feat(plugins): `octozen` shows an Octocat zen quote on startup

### PR DESCRIPTION
**Pull request by gtrefs**
Added a plugin which `curls` `https://api.github.com/octocat` on startup and displays the returned message.

### CODE REVIEW

**Comment by joyarzun** [comment]
It's nice but Sehll stays a little slow to start

**Comment by gtrefs** [comment]
@joyarzun thanks for the feeback. The reason might be the HTTP call to the API. I am not sure how to mitigate this.

**Comment by enderahmetyurt** [comment]
:octocat:

**Comment by robbyrussell** [comment]
> The reason might be the HTTP call to the API. I am not sure how to mitigate this.

We'll opt to pass `--connect-timeout` to `curl` to try and keep it speedy for people.

**Pull request merged**
