### PR TITLE
feat(git): add merge squasch alias

### PR DESCRIPTION
**Pull request by EinfachAleks**
add new alias for git merge --squash

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- [...]

## Other comments:

...

### CODE REVIEW

**Review by jmeridth — CHANGES_REQUESTED** [review]
Looks good but please update the `plugins/git/README.md` file with your new alias.

**Review by jmeridth — APPROVED** [review]

**Review by jmeridth — APPROVED** [review]

**Comment by carlosala** [comment]
I think it's a great addition, a simple alias that might be used in several workflows. Could you please update the readme as well?

**Comment by EinfachAleks** [comment]
@carlosala yes of course, have apparently taken over the wrong at rebase ...

**Comment by EinfachAleks** [comment]
@carlosala  done ;)

**Comment by carlosala** [comment]
Thanks for your contribution!

**Comment by eval-exec** [comment]
Hello, would you like to add some git command alias for `git reflog`?

**Comment by EinfachAleks** [comment]
@eval-exec i will try to create a few

**Pull request merged**
