### PR TITLE
web-search: add Wayback Archive

### PR DESCRIPTION
**Pull request by pgimalac**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Add Reddit and The Internet Archive Wayback Machine to the list of search engines.

### CODE REVIEW

**Comment by larson-carter** [comment]
@pgimalac  Lets think here, would developers actually use the wayback machine in zsh? Reddit is borderline. 

@mcornella What is your opinion?

**Comment by pgimalac** [comment]
@larson-carter honestly I don't think so but I like to know that it's possible !
Feel free to remove it if you really prefer.
And for Reddit I really think it might be used.

**Comment by mcornella** [comment]
Reddit is not a search engine. The Wayback Machine is, and I can see it being useful for some people. Can you remove Reddit and also add the Wayback Machine to the README?

**Comment by pgimalac** [comment]
@mcornella as you wish, it's done.

**Pull request merged**
