### PR TITLE
Add silverblue toolbox plugin

### PR DESCRIPTION
**Pull request by hyperreal64**
Apologies in advance if I have misunderstood the instructions for submitting a PR. This is my first ever PR.

### CODE REVIEW

**Comment by bartekpacia** [comment]
Hi @hyperreal42, thanks for the contribution.

Please include link to your GitHub profile in the plugin's README because you'll be its maintainer (that's what we strive for, every plugin has a person responsible for it).

**Comment by hyperreal42** [comment]
> Please include link to your GitHub profile in the plugin's README because you'll be its maintainer (that's what we strive for, every plugin has a person responsible for it).

Done. Let me know if anything else is needed. :-)

**Comment by bartekpacia** [comment]
@hyperreal42 Thank you, but I don't see any pushed changes. Maybe you forgot? ;P

**Comment by hyperreal42** [comment]
> @hyperreal42 Thank you, but I don't see any pushed changes. Maybe you forgot? ;P

Lol sorry I'm new to this. I pushed the changes to my forked repo earlier. Wasn't that what I was supposed to do?

**Comment by bartekpacia** [comment]
Now it's good :) Thanks

**Pull request closed without merging**
