### PR TITLE
feat(conda-env): add plugin for conda prompt display

### PR DESCRIPTION
**Pull request by cjeonguk**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Adds a `conda-env` plugin which provides `conda_propmt_info` function that we can use in our theme, which displays the basename of the current `$CONDA_DEFAULT_ENV`.

## Other comments:

- `conda-env` is a popular package manager for python.
- `conda-env` plugin works similarly to the `virtualenv` plugin, but for [`conda`](https://anaconda.com).

### CODE REVIEW

**Comment by afeld** [comment]
Duplicate of https://github.com/ohmyzsh/ohmyzsh/pull/9691.

**Comment by carlosala** [comment]
It's not really a duplicate I think, as they implement different things.

**Comment by cjeonguk** [comment]
It's the same name, but #9691 is a plugin with aliases and mine is a plugin with prompt display function. I think another plugin name would be better. `conda` has a wide range to explain its function.

**Comment by naturedamends** [comment]
Should all plugins use your function instead of https://github.com/ohmyzsh/ohmyzsh/pull/11785

**Comment by mcornella** [comment]
Took a while, but thanks for the contribution!

**Comment by skupr-anaconda** [comment]
If anyone asks how to use it then do the next:
Add `conda-env` to plugins in your `~/.zshrc`:
`plugins=(... conda-env)`
run `source ~/.zshrc.`
Then if you run :
`╰─❯ conda_prompt_info`
`[abs]`
It will say the name of your current environment.

**Pull request merged**
