### PR TITLE
Add option to automatically upgrade custom plugins

### LINKED ISSUE #5599: Autoupdate git repos in custom/plugins
It would be nice if ohmyzsh searched for .git folders in custom/plugins/* and ran `git pull` in those directories

personally, I have [zsh-autosuggestions](https://github.com/zsh-users/zsh-autosuggestions) and [zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting) in that directory

### PR DESCRIPTION
**Pull request by dmohns**
Closes #5599

### Objective
It is a common use case to have custom plugins or themes managed in git repositories similar to OMZ itself. Popular examples are https://github.com/zsh-users/zsh-autosuggestions or https://github.com/zsh-users/zsh-syntax-highlighting for plugins and https://github.com/denysdovhan/spaceship-prompt for themes. 

It would be nice if these custom plugins and themes would smoothly integrate into OMZ's update process. The scope of this PR is to add this functionality.

### Comments
- I don't want to steal anybody's work, most of the effort was done by @benwaffle in the corresponding issue. 
- I think it is a good choice to add the possibility for automatic updates but disable it by default. Users should take a conscious decision (and be aware of it's implications) when choosing to enable automatic updates of custom plugins and themes.
- These are my first steps with OMZ happy to receive feedback and comments.

### Discussion
I am not entirely sure, if a feature like this has it's place in OMZ.

### CODE REVIEW

**Comment by mattmc3** [comment]
This seems like a lot of change and introduction of new variables and complication for a one-liner. Maybe adding this to tools/upgrade.sh would be sufficient.

```find $ZSH_CUSTOM -type d -name .git -prune -execdir git pull -q \;```

**Comment by dlemfh** [comment]
I'd really like to be able to use this functionality (that is, not have to manually update my plugins every time). Is anyone interested in going further with this PR? (I'd be glad to help!)

In my opinion, the one-liner approach seems okay as well. Less complexity leads to better maintainability.

**Comment by larson-carter** [comment]
@dmohns This has the potential to be a useful PR. Can you please resolve the current conflicting files that way I can take a look during a review?

**Comment by dmohns** [comment]
Thanks @larson-carter for considering this PR. From a brief look the update logic has changed quite a bit since I last worked on this PR. Adapting this might require some effort and as I no longer use OMZ myself, I will probably not find the motivation to do so. But I would be more than happy if someone else takes over!

**Comment by archteck** [comment]
I did some adaptions and it worked fine on my machine. Good job @dmohns !
Hope someone takes this, i can share the changes i have made if you want.

**Comment by carlosala** [comment]
Closed in favour of #10772

**Pull request closed without merging**
