### PR TITLE
feat(git-commit): create plugin

### PR DESCRIPTION
**Pull request by xiBread**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Add a plugin that adds git aliases for conventional commits

## Other comments:

https://www.conventionalcommits.org/en/v1.0.0/#summary

### CODE REVIEW

**Comment by AlexLombry** [comment]
Can we have this merge ?

**Comment by freewaying** [comment]
Good Job!

**Comment by centrumek** [comment]
Hi @xiBread, do you have any information to make it done? Or anyone knows some other alternatives?

It would be great to have this feature!

**Comment by carlosala** [comment]
This PR seems to have quite a bit of support, let's go to merge it!
Thanks for your contribution!

**Pull request merged**
