### PR TITLE
Added more terraform aliases

### PR DESCRIPTION
**Pull request by l13t**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Added aliases that simplify work with Terraform workspaces in CLI

## Other comments:

...

### CODE REVIEW

**Comment by klyse** [comment]
did you consider adding another alias: `tfa!`for `terraform apply -auto-approve`.

**Comment by l13t** [comment]
I'm not a fan of such approach :) . But it could be something like `tfaa`

**Comment by carlosala** [comment]
Maybe those are too many aliases. Could we stick to just adding one or two? There's a new policy for that [here](https://github.com/ohmyzsh/ohmyzsh/blob/master/CONTRIBUTING.md#new-plugin-aliases).
Thanks!

**Comment by nitrocode** [comment]
If it will speed things up, I'd be content with the subset of only workspace, list, and select aliases.

**Comment by nitrocode** [comment]
cc @robbyrussell thoughts on this PR?

**Comment by carlosala** [comment]
There are a lot of aliases in this PR, but it isn't getting much traction. Closing!

**Pull request closed without merging**
