### PR TITLE
Add alias for clonning and cd into repo in git plugin

### PR DESCRIPTION
**Pull request by nelsonmestevao**
I found the solution in [this](https://stackoverflow.com/questions/59392153/git-clone-and-cd-into-it) StackOverflow Question.

### CODE REVIEW

**Comment by TheTechRobo** [comment]
Should it go in documentation

**Comment by nelsonmestevao** [comment]
> Should it go in documentation?

Yes, for sure!

**Review by TheTechRobo — APPROVED** [review]
A quick once over looks good.

**Comment by mcornella** [comment]
Duplicate of #8220.

**Comment by mcornella** [comment]
I've added you as co-author btw: https://github.com/ohmyzsh/ohmyzsh/commit/714399a7c33963384ef7f21ce21f6d134416f9aa.

**Pull request closed without merging**
