### PR TITLE
Add Terragrunt Alias

### PR DESCRIPTION
**Pull request by Tensho**
https://github.com/gruntwork-io/terragrunt

### CODE REVIEW

**Comment by Tensho** [comment]
@mcornella Please could we merge this stuff? 🙇

**Comment by Tensho** [comment]
Documented `tg` alias

**Review by 53jk1 — APPROVED** [review]

**Comment by Tensho** [comment]
@mcornella Anything else here?

**Comment by mcornella** [comment]
Where does the completion script come from?

**Comment by Tensho** [comment]
@mcornella From `terraform` counterpart mostly.

**Comment by pirish** [comment]
+1 for this PR

**Pull request closed without merging**
