### PR TITLE
feat(timoni): add completion plugin

### LINKED ISSUE #12801: A plugin for Timoni (timoni.sh)
### If the feature request is for a plugin or theme, specify it here.

timoni

### If the feature solves a problem you have, specify it here.

_No response_

### Describe the proposed feature.

I'd like a simple plugin for the Timoni Kubernetes package manager (https://timoni.sh). Timoni's CLI is built with the same library/framework of most Go applications, so a simple plugin like the FluxCD one would be enough (enables shell completions).

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Related Issues

_No response_

### PR DESCRIPTION
**Pull request by matheuscscp**
Fixes #12801

## Standards checklist:

- [X] The PR title is descriptive.
- [X] The PR doesn't replicate another PR which is already open.
- [X] I have read the contribution guide and followed all the instructions.
- [X] The code follows the code style guide detailed in the wiki.
- [X] The code is mine or it's from somewhere with an MIT-compatible license.
- [X] The code is efficient, to the best of my ability, and does not waste computer resources.
- [X] The code is stable and I have tested it myself, to the best of my abilities.
- [X] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

- Add plugin for Timoni

### CODE REVIEW

**Comment by matheuscscp** [comment]
cc @stefanprodan

**Review by stefanprodan — APPROVED** [review]
Thanks @matheuscscp

**Review by carlosala — APPROVED** [review]
LGTM 🚀

**Comment by carlosala** [comment]
Thanks for your contribution!

**Pull request merged**
