### PR TITLE
Add toolbox run (tbr) to Toolbox plugin

### PR DESCRIPTION
**Pull request by francoism90**
## Standards checklist:

- [X] The PR title is descriptive.
- [X] The PR doesn't replicate another PR which is already open.
- [X] I have read the contribution guide and followed all the instructions.
- [X] The code follows the code style guide detailed in the wiki.
- [X] The code is mine or it's from somewhere with an MIT-compatible license.
- [X] The code is efficient, to the best of my ability, and does not waste computer resources.
- [X] The code is stable and I have tested it myself, to the best of my abilities.
- [X] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

- Add `tbr` to allow run `toolbox run`.
- Change `te` to `tbe` to have them in sync.

## Other comments:

I'm thinking of adding more commands, but I'm still new to Toolbox.

### CODE REVIEW

**Comment by carlosala** [comment]
could you update readme? I think adding one alias would be enough, but tell me if something essential is missing!

**Comment by christianparpart** [comment]
Aliasing `tr` might accidentally break regular uses of the more advanced users not expecting this. Because `tr` is actually a [valid UNIX command](https://en.wikipedia.org/wiki/Tr_(Unix)#:~:text=tr%20is%20a%20command%20in,in%20its%20input%20data%20set.). :-)

**Comment by carlosala** [comment]
we could move the other alias to `tbe` and this to `tbr`!

**Comment by francoism90** [comment]
@carlosala Sorry for not being that active, if it's Ok, I'll change the alias for both. :)

**Comment by francoism90** [comment]
Also is `tb` not used for Thunderbolt devices?

**Comment by carlosala** [comment]
not sure, where?

**Comment by francoism90** [comment]
@carlosala I have updated the PR, let me know, maybe more can be added. :)

**Pull request merged**
