### PR TITLE
added table of content for easier navigation

### PR DESCRIPTION
**Pull request by MohanSha**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Added table of content section in readme

## Other comments:

...

### CODE REVIEW

**Comment by NoahvdAa** [comment]
GH has a built-in table of contents

image

**Comment by LunarWatcher** [comment]
yeah, I fail to see the reason behind adding a ToC when GitHub already displays one by default

**Comment by mcornella** [comment]
Thanks for the contribution, but what they said.

**Comment by MetaMmodern** [comment]
@NoahvdAa @LunarWatcher @mcornella  Hi folks) I was going to create a similar PR and found this one. Unfortunately, github TOC is not available in mobile GitHub application(on Android at least). Do you still think that you don't need a TOC inside the markdown itself?

**Comment by TheTechRobo** [comment]
I mean, it probably couldn't hurt to put it in a `<details>` tag

(example for those who've never used it:

```
<details><summary>Table of contents</summary>

# Hello World!

</details>
```

<details><summary>Table of contents</summary>

# Hello World!

</details>

**Comment by MetaMmodern** [comment]
@TheTechRobo alrighty, got it, will do in a while)

**Pull request closed without merging**
