### PR TITLE
bugfix: upgrade correct branch when running upgrade_oh_my_zsh

### PR DESCRIPTION
**Pull request by ngaro**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

If oh-my-zsh is installed with `BRANCH=somebranch` then `upgrade_oh_my_zsh` tried to use the (incorrect) branch `master` instead of `somebranch`.
This PR fixes this.

## Other comments:

This does the same as PR #8005 which i closed myself because it didn't follow contribution guide

### CODE REVIEW

**Comment by mcornella** [comment]
`git symbolic-ref --short HEAD` in `git pull` is redundant, since a `git pull` already uses the current branch if not passed, so it could just be removed to only say `git pull origin`.

**Comment by ngaro** [comment]
You are correct, the effect is the same.

I prefer using my more explicit method because It emphasizes that you are upgrading the current branch without touching any other branches.

**Comment by ngaro** [comment]
Merge conflict is now fixed, (although github doesn't seem to know this)

**Review by 53jk1 — APPROVED** [review]

**Comment by wac-** [comment]
This seems to have gotten stalled and seems like the conflicts haven't been resolved.

Can I suggest something like https://github.com/ohmyzsh/ohmyzsh/compare/master...wac-:upgrade-stay-on-branch to move things forward?

**Comment by ngaro** [comment]
Your method is indeed better, thanks !
Now let's hope it's gets merged soon before it conflicts again...

**Comment by ngaro** [comment]
I just noticed that the same problem exits when using the new `omz update` (which didn't exist when i created this bugfix). I'll fix it there also _after_ this gets **finally**  merged...

**Comment by mcornella** [comment]
098bcda6910aa2f734fb0ad59ac089157a239c87 adds `oh-my-zsh.remote` and `oh-my-zsh.branch` settings when installed, which are then used by the updater to figure out from where to `git pull`.

If you need to change that, you can do `git -C "$ZSH" config oh-my-zsh.remote <remote-name>` or `git -C "$ZSH" config oh-my-zsh.branch <branch-name>` to change the behavior manually.

**Pull request closed without merging**
