### PR TITLE
updated .gitignore

### PR DESCRIPTION
**Pull request by bartekpacia**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Added a wildcard (`*`) to ignore all `.DS_Store` files. I really don't know what else to say.

## Other comments:
It's annoying for me to have all those nested `.DS_Store` included.

### CODE REVIEW

**Comment by mcornella** [comment]
I was under the impression that these files were all named `.DS_Store`. Has that changed?

**Comment by bartekpacia** [comment]
It might be just me, but I had nested `.DS_Stores` getting added to git's staging area and adding that wildcard fixed that🤷‍♂️

**Comment by mcornella** [comment]
When you say nested, what do you mean? What're the filenames?

**Comment by bartekpacia** [comment]
I mean files not in the root (`.oh-my-zsh/`), but in its children directories.

**Comment by mcornella** [comment]
The way it's written in the `.gitignore` file, any file named `.DS_Store` anywhere in the repository will be ignored. There has to be something else happening here:
image

**Comment by bartekpacia** [comment]
Okay, so it was some other problem on my side. Thanks for response!

**Pull request closed without merging**
