### PR TITLE
Add autocomplete for vagga

### PR DESCRIPTION
**Pull request by webknjaz**
Hello,

I've written some autocomplete rules for https://github.com/tailhook/vagga
It would be nice to merge this to upstream

Have a nice day :)

### CODE REVIEW

**Comment by webknjaz** [comment]
@tailhook
Paul this is PR with zsh completion rules for vagga. Plz take a look :)
If there's anything I missed — let me know.

**Comment by rrader** [comment]
Nice. Maybe it's possible to utilize the vagga-completion.sh script that comes with vagga instead of parsing the vagga's output?

**Comment by tailhook** [comment]
Yes, it's possible to utilize `vagga-completion.sh` (`bashcompinit`). But it's not the goal. The goal is probably to utilize the vagga's internal completion command that `vagga-completion.sh` uses.

The good thing about zsh-completion is that it allows to add descriptions to every entry in completion, so we would probably want to extend `vagga _compgen` command to have descriptions too.

/cc @anti-social

**Comment by webknjaz** [comment]
Alright, I'll look into it as well. `vagga-completion.sh` doesn't work for me. Nevertheless, I'm going to check whether I could call internal `vagga`'s autocomplete API. Thanks @tailhook :)

**Comment by tailhook** [comment]
Well, have you tried this?
```
autoload bashcompinit
bashcompinit
source /wherever/vagga/is/vagga-completion.sh
```

**Comment by tailhook** [comment]
Okay, here is more clear completion for zsh. If you add the following to `.zshrc` completion work well (without option descriptions yet):
```
_vagga() {
    compadd -- $(vagga _compgen ${words[2,-2]} -- $PREFIX)
}
compdef _vagga vagga
```
It should be easy to convert it to a `#autoload` script, but I'm not sure exact syntax.

Also, it would be nice if someone check if I pass arguments to `vagga _compgen` correctly

**Comment by robbyrussell** [comment]
⌛️ Am closing this for now as we'll need a README included. Happy to reconsider in the future.

**Pull request closed without merging**
