### PR TITLE
fix(pass): update `pass` completion to ff5ac38

### PR DESCRIPTION
**Pull request by rmuit**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

Quote $@ in completion.

## Other comments:

I started using zsh yesterday, and my command completion broke. 

It happens at least with filenames containing colons. The details of the breakage are: "the completion suggestions are all weird so they are useless". (I haven't looked at further details.)

The completion command contains a $@, and I my first guess was maybe trying to quote it would help. Lo and behold, it did! So I stopped trying to understand much about zsh completion after that.

### CODE REVIEW

**Comment by mcornella** [comment]
Can you send this patch upstream? This file is a bundle of the official pass autocompletion.

**Comment by rmuit** [comment]
Upstream (https://www.passwordstore.org/) suggests sending an e-mail including a patch to a mailinglist. I did so, although I botched the subject line: https://lists.zx2c4.com/pipermail/password-store/2021-March/thread.html

I am not super sure who is going to respond there. I can understand you're not merging this PR but I'd like it to remain visible here for the while because visibility (or possibility for others to respond) isn't excellent with this upstream method.

**Comment by rmuit** [comment]
Oh - also, it just re-broke silently after 1.5 days of working, and isn't fixed by me removing ~/.zcompdump* as suggested elsewhere. Mysterious.

**Comment by mcornella** [comment]
Maybe it working was a false positive. I'd bet we need to quote the colon characters so that it's not treated as a separator.

Something like this maybe:
```
${variable//:/\\:}
```

Note the double backslash. I haven't looked at the code so I can't tell you where to do that, but maybe this helps you.

**Comment by mcornella** [comment]
Or since it's using sed anyway maybe you can use quote colon characters with it, before it does the backslash duplication.

**Comment by rmuit** [comment]
Thank you for updating and closing this with a second/proper commit -- and sorry for not getting back to this.

(There's never time... I've been slugging along with broken password completion until things suddenly worked because of this.)

**Pull request merged**
