### PR TITLE
Add completion plugin for IPFS (InterPlanetary File System)

### PR DESCRIPTION
**Pull request by aramboi**

### CODE REVIEW

**Comment by kubukoz** [comment]
For anyone who, like me, was looking for a way to get ipfs completions:

```zsh
cd ~/.oh-my-zsh/custom/plugins
git clone https://github.com/hellounicorn/zsh-ipfs
```

then add `zsh-ipfs` to your plugins :)

**Comment by aramboi** [comment]
@kubukoz That should work as well. Fair warning though, I haven't updated that completion script in years as I haven't worked with IPFS lately. I am planning to do an update in the following weeks. Until then, if you notice something is off, I would appreciate opening an issue or a PR.

**Comment by aramboi** [comment]
@kubukoz got some time on my hands and updated the completion script to the latest version of IPFS. I will push an update to this PR soon. 🙂

**Comment by aramboi** [comment]
Updated the completion plugin to the latest version.

**Pull request merged**
