### PR TITLE
feat(flutter): use up-to-date zsh completion

### PR DESCRIPTION
**Pull request by cpboyd**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Updates to use the built-in `flutter zsh-completion` instead of the hardcoded, outdated list.

## Other comments:

This is based on the `kubectl` autocomplete caching implementation.
Once, when testing the speed impact, I did notice `Waiting for another flutter command to release the startup lock...` from rapidly opening shells.

### CODE REVIEW

**Comment by carlosala** [comment]
Hi! Really nice contribution, let's move ahead with it!
Could you follow the same structure as we have with [`deno` plugin](https://github.com/ohmyzsh/ohmyzsh/blob/249c708ed3a4a7a63d16a6e911a46b6fb9623cbd/plugins/deno/deno.plugin.zsh#L14-L27)? It's better for maintainability to have always the same structure in every plugin.
Thanks!

**Comment by cpboyd** [comment]
@carlosala I've adjusted it to match the `deno` plugin.

**Review by carlosala — APPROVED** [review]
nice contribution, thanks! 🙌🏻

**Comment by carlosala** [comment]
@mcornella can you merge this, please?
Thanks!

**Comment by BetterB0y** [comment]
Something is wrong with it. Completition is now not working for me. After deleting _flutter dir and restarting zsh I can manage to get it working. But after rebooting terminal completition is not working again.
I got:
-- console output produced during zsh initialization follows --
compdef: unknown command or service: flutter

**Comment by cpboyd** [comment]
@BetterB0y 

1. Can you post the output from `flutter --version` ?
2. Can you double-check that you add `flutter` to your `PATH` before your `plugins=()` block in `.zshrc` ?
   - Your error seems to indicate that flutter may not be in your path when the auto-complete function runs.

**Comment by BetterB0y** [comment]
Flutter version:

Flutter 2.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5464c5bac7 (4 miesiące temu) • 2022-04-18 09:55:37 -0700
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2

**Comment by BetterB0y** [comment]
Zrzut ekranu 2022-08-9 o 22 29 12

**Comment by BetterB0y** [comment]
@cpboyd Can you check?

**Comment by cpboyd** [comment]
I'm not able to reproduce, but it seems that this error sometimes occurs for other plugins as well: #630
There are various suggestions there.

If you're able to run `flutter zsh-completion` from the command-line (which should be available in Flutter 2+) then the script _should_ work.

It'd probably be best to open an issue and reference this PR, as I'm not familiar with OMZ's internals surrounding compdef and such.

**Comment by cpboyd** [comment]
@BetterB0y I did just notice that I don't have ZSH_COMPDUMP defined. Maybe OMZ doesn't properly clear/update that if manually defined. Have you tried making a backup and then clearing it out?

**Comment by BetterB0y** [comment]
@cpboyd I deleted all files from dir completitions, removed ZSH_COMPDUMP and rebooted. Same again. I don't have completitions for flutter after reboot.

**Comment by cpboyd** [comment]
Are you still getting `compdef: unknown command or service: flutter` or another error?

As I mentioned earlier, it'd probably be best to create a new issue and reference this PR. I'm not familiar enough with compdef to help debug any further.

**Pull request merged**
