### PR TITLE
chore: removing old completion code

### PR DESCRIPTION
**Pull request by carlosala**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

Removing TODO marked code

### CODE REVIEW

**Comment by mcornella** [comment]
/remind me to merge this PR in 2 months

**Comment by mcornella** [comment]
I'll get a reminder in 2 months to merge this, thanks for the PR!

**Comment by carlosala** [comment]
@mcornella time to merge!

**Pull request merged**
