### PR TITLE
feat(tasko): new tasko plugin

### PR DESCRIPTION
**Pull request by knid**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

- Created tasko function
- Created README.md file

## Other comments:

...

### CODE REVIEW

**Comment by robbyrussell** [comment]
Hi @knid, what are you offering here that isn't currently available in the [existing TaskWarrior plugin](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/taskwarrior)? 

Might this be something we can blend into the existing plugin?

**Comment by knid** [comment]
Hi @robbyrussell, it's different. The plugin you shared enables tab completion. Mine is opens annotation content with native open commands (xdg-open or open). Like URL or file.

**Comment by robbyrussell** [comment]
@knid I'm worried that 'tasko' might not be descriptive enough of a name and if people are using TaskWarrior, they'll see the other. Could we explore merging these two concepts into one?

**Comment by knid** [comment]
@robbyrussell Taskwarrior uses `task` cli command. I thought `task-open` or `tasko` would be nice. But that's okay for me. We can merge two repo into one.

**Comment by knid** [comment]
Or i can change repo name to `taskwarrior-open`

**Comment by mcornella** [comment]
Can you show a recording of what your plugin does, for example using `asciinema`?

It's not clear from reading TaskWarrior docs why `xdg-open` or `open` is needed, as according to [[1]] descriptions are just text-based.

BTW we have a utility function called `open_command` that uses the right command based on platform/OS.

[1]: https://taskwarrior.org/docs/dom/

**Comment by knid** [comment]
[asciinema record](https://asciinema.org/a/vKZYyLYMVQ6qK5u7CmSXDlPqQ)

Its just open annotation content quickly.

**Comment by mcornella** [comment]
I think this makes the most sense as an addition to Taskwarrior itself, if it's a common use case to add URLs as task annotations. If not, that is too specific of a use case and won't be useful to enough people to be worth the expensive maintenance cost and manual testing.

Thanks for the contribution!

**Pull request closed without merging**
