### PR TITLE
vagrant: add common aliases

### PR DESCRIPTION
**Pull request by penguinpowernz**
I found it strange these were missing.  I ran through them all to check that they weren't conflicting with any commands on my system and they were all good.

Almost made `vagrant init` alias to `vi` lol (used `vgi` instead).

Closes #3140
Closes #3312

### CODE REVIEW

**Comment by ncanceill** [comment]
cc @fb3 @irnnr

**Comment by curiositycasualty** [comment]
I had opened PR #2964, but this PR can have my vote if you add aliases for:
```
vagrant ssh-config
vagrant global-status
```

**Comment by penguinpowernz** [comment]
Added them now, `vsshc` and `vgs` respectively.

**Comment by curiositycasualty** [comment]
Awesome! Closing PR #2964

**Comment by penguinpowernz** [comment]
Merging this or nah @curiositycasualty ?

**Comment by curiositycasualty** [comment]
Sure!

**Pull request merged**
