### PR TITLE
feat(git): support trunk branches in `git_main_branch`

### PR DESCRIPTION
**Pull request by alissonbrunosa**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [ ] I have read the contribution guide and followed all the instructions.
- [ ] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:
It adds `trunk` branch name as option in case the repository uses it as default branch.
- [...]

## Other comments:

...

### CODE REVIEW

**Comment by mcornella** [comment]
Is there a reason you're not using `main`? That seems to be the future standard, so reliance on this function is going to bring problems down the line.

**Comment by alissonbrunosa** [comment]
Hey @mcornella, yeah there is, I am contributing for https://github.com/cli/cli, and they're using `trunk` as default branch, and I believe there are more out there.
Being honest, I don't think the community has defined a standard :sweat_smile:

**Comment by mcornella** [comment]
Weird since GitHub itself had defined `main` as the new default. I've changed the logic to a for in case we need to support other cases in the future.

**Comment by alissonbrunosa** [comment]
@mcornella Awesome.

**Pull request merged**
