### PR TITLE
fix(init): prevent multiple compdump compilations

### LINKED ISSUE #11341: zrecompile race condition when opening several terminals at once
### Describe the bug

I use the i3 window manager.  I have autologin configured and automatically start six terminals (alacritty) with zsh on the start of i3.  In several of those terminals I often get

``` zrecompile:zcompile:99: invalid zwc file: /home/w/.zcompdump-huette-5.9.zwc ```

I suspect that it is some kind of race condition when multiple processes try to update the zwc file at once.

### Steps to reproduce

It can be reproduced more or less reliably with (something like) the following:

``` touch ~/.zcompdump-${HOST}-5.9; alacritty&; alacritty&; alacritty& ```

When I run the previous command with my usual configuration the error appears almost every time in at least one of the terminals spawned.  However, when I create a new user on my machine with a minimal configuration, then it happens far less often.  But it does happen.

It may be harder to reproduce on more recent hardware.  I am working on an about 10 years old system with an "Intel(R) Celeron(R) CPU N3150 @ 1.60GHz".

### Expected behavior

No error message. Maybe some kind of locking.

### Screenshots and recordings

_No response_

### OS / Linux distribution

Arch Linux

### Zsh version

5.9

### Terminal emulator

alacritty

### If using WSL on Windows, which version of WSL

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by carlosala**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

- Compile compdump only if there's no lockfile

Closes #11341

### CODE REVIEW

**Comment by mcornella** [comment]
File creations (with touch) are not atomic, there could be two processes finding no lock file and enter the if at the same time before the `touch` runs.

See the `check_for_upgrade.sh` script for an example of a lock mechanism using `mkdir`.

There is also a lock functionality in a module, look for `zsystem flock` in https://zsh.sourceforge.io/Doc/Release/Zsh-Modules.html.

**Comment by carlosala** [comment]
@mcornella yas, thanks for the hint! I tested launching multiple instances of `zsh` (and echoing stuff to be sure) and I everything works well from my side!

**Comment by mcornella** [comment]
Looks good to me, good job!

@whxvd can you test if this solves your issue? You can check out this PR with `omz pr test 11345`. Thanks!

**Comment by whxvd** [comment]
When I run `touch $ZSH_COMPDUMP; alacritty&; alacritty&; alacritty&` without the PR, the error appears at least half of the times. With the PR at least 30 tests in succession yielded no error. So it seems to work! Thanks a lot!

**Comment by mcornella** [comment]
Thanks for testing!

**Comment by carlosala** [comment]
Thanks for the contribution!!!

**Pull request merged**
