### PR TITLE
feat(sudo): support aliases to $EDITOR

### PR DESCRIPTION
**Pull request by subnut**
If you use some alias for your $EDITOR, say `e`. You type `e /to/file`.
But that file needs sudo permission. You naturally do `<Esc><Esc><Enter>`.
But, to your dismay, it errors out `command not found`, because it
didn't detect your alias to $EDITOR, thereby failing to convert it to
`sudoedit`.

This commit tries to detect your alias and convert it to sudoedit.

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Removed a trailing whitespace
- Added vim modeline
- Added my name and GitHub user URL under Authors
- Added the actual functionality this PR is intended for

## Other comments:

NONE

### CODE REVIEW

**Comment by subnut** [comment]
Ping @mcornella

**Comment by mcornella** [comment]
Good idea but a small tip: you can use the `$aliases` variable to get the command.

**Comment by subnut** [comment]
@mcornella Why is this PR not merged? Any problems?

> you can use the $aliases variable to get the command

How? I am unable to understand... It would be better if you show me how to use it in which line.....

**Comment by mcornella** [comment]
> How? I am unable to understand... It would be better if you show me how to use it in which line.....

Right sorry, I thought it was clear. The `$aliases` variable is an associative array that holds, for every alias, the command it runs. So if you have an alias `e=$EDITOR`, `$aliases[e]` is `$EDITOR`. You can use this instead of checking the output of `alias`.

**Comment by mcornella** [comment]
I've changed the logic to use the $aliases variable and significantly reduced the complexity. I've tested on my end and it seems to work, but do try it yourself before I merge it.

**Comment by subnut** [comment]
Oh... so that's why my local commit wasn't pushing! :smile:

This is the way I had tried to implement it -
```diff
diff --git a/plugins/sudo/sudo.plugin.zsh b/plugins/sudo/sudo.plugin.zsh
index c092e81..6869bbd 100644
--- a/plugins/sudo/sudo.plugin.zsh
+++ b/plugins/sudo/sudo.plugin.zsh
@@ -28,7 +28,6 @@ sudo-command-line() {
         if [[ -z $EDITOR ]]; then                       # EDITOR not set, so no work
             return
         fi
-        _EDITOR=$EDITOR                                 # To later restore the original value
         _CURRENT=$(echo -n $BUFFER | cut -d' ' -f1)     # Get current command (to check for alias)
         if [[ $_CURRENT == $EDITOR ]]; then             # If current command is same as EDITOR, no need to check further.
             return 0
@@ -36,40 +35,13 @@ sudo-command-line() {
         if [[ $_CURRENT == 'sudoedit' ]]; then          # If current command is sudoedit, no need to check further.
             return 0
         fi
-        if [[ $EDITOR =~ ' ' ]]; then
-            EDITOR="'$EDITOR"                           # If EDITOR has spaces, then alias will be wrapped in ''
-        fi
 
-        # Check for aliases that match the value of $EDITOR
-        if
-            () {
-                for alias in $(alias | grep "=$EDITOR" | cut -d= -f1)
-                do  if [[ $alias = $_CURRENT ]]; then
-                        EDITOR=$alias   # set EDITOR to the alias
-                        return 0
-                    fi
-                done
-                return 1    # none of these aliases match
-            };
-        then
-            return
-
-        # Maybe alias is set to the variable instead of it's value
-        elif
-            () {
-                for alias in $(alias | grep \=\'\$EDITOR | cut -d= -f1)
-                do  if [[ $alias = $_CURRENT ]]; then
-                        EDITOR=$alias   # set EDITOR to the alias
-                        return 0
-                    fi
-                done
-                return 1    # none of these aliases match
-            }
+        # Check if current command is aliased to $EDITOR
+        if echo -n $aliases[$_CURRENT] | grep -e ^$EDITOR -e '^$EDITOR' &> /dev/null
         then
+            EDITOR=$_CURRENT
             return
         fi
-
-        EDITOR=$_EDITOR     # Nothing matched. Restore $EDITOR
     }
 
     if [[ -n $EDITOR && $BUFFER == $EDITOR\ * ]]; then
```

<br>
Anyway.. Okay, I shall be testing it a bit, and reporting back to you.

_off-topic_: Do you know any (free) good resources for learning zsh? I am a noob (in case you haven't figured it out already..)

**Comment by subnut** [comment]
well.... just as I am about to report it, you push `e38f004`

**Comment by mcornella** [comment]
> _off-topic_: Do you know any (free) good resources for learning zsh? I am a noob (in case you haven't figured it out already..)

I always end up going to the [Zsh documentation](http://zsh.sourceforge.net/Doc/Release/zsh_toc.html#SEC_Contents), most frequently the [expansion](http://zsh.sourceforge.net/Doc/Release/Expansion.html#Parameter-Expansion) docs. Also completion can be very useful sometimes. For example, when trying to find a way to modify a variable with `${(modifier)var}` you can type `${([TAB]` and you get many options. Reading official Zsh code (completion functions) also gives me a lot of ideas. And if that isn't enough, you have the [zsh-workers mailing list](https://www.zsh.org/mla/) at your disposal.

**Comment by subnut** [comment]
@mcornella Thanks!
BTW there's a bug... aliases work well, but if the command is the actual value of $EDITOR, then it doesn't work

**Comment by subnut** [comment]
See GIF - 
gifcast_201112011639

**Comment by mcornella** [comment]
So `$EDITOR` is `nvim` in that case?

**Comment by subnut** [comment]
Yes

**Comment by mcornella** [comment]
Oh, so your setup is like
```zsh
EDITOR=nvim
alias n=nvim
```
and the problem you find is that when the typed command uses the alias, triggering the function twice goes back to using `nvim` instead of `n` which is the alias?

**Comment by subnut** [comment]
No, the problem is that when the command is `nvim sudo.plugin.zsh` and the function is triggered, the result is `sudo nvim` instead of `sudoedit`

**Comment by subnut** [comment]
I added this line to see the values of $LBUFFER and $EDITOR
`zle -M "$LBUFFER $EDITOR"`

See this GIF -
gifcast_201112012225

**Comment by subnut** [comment]
Seems like the value of $EDITOR is set to the alias, even when the current command isn't an alias

**Comment by subnut** [comment]
you can see that the value of $EDITOR is `n` when the command is `nvim`, causing `sudo nvim` instead of `sudoedit`

**Comment by subnut** [comment]
UPDATE: seems like `$cmd` is only taking the first character of the buffer -
gifcast_201112012923

**Comment by mcornella** [comment]
Right, I had it working before. Try with this patch:
```patch
diff --git a/plugins/sudo/sudo.plugin.zsh b/plugins/sudo/sudo.plugin.zsh
index c75821fc..f2445a76 100644
--- a/plugins/sudo/sudo.plugin.zsh
+++ b/plugins/sudo/sudo.plugin.zsh
@@ -37,7 +37,7 @@ sudo-command-line() {
     # Get the first part of the typed command and check if it's an alias to $EDITOR
     # If so, locally change $EDITOR to the alias so that it matches below
     if [[ -n "$EDITOR" ]]; then
-        local cmd="${(Az)BUFFER[1]}"
+        local cmd="${${(Az)BUFFER}[1]}"
         if [[ "${aliases[$cmd]} " = (\$EDITOR|$EDITOR)\ * ]]; then
             local EDITOR="$cmd"
         fi
```

**Comment by subnut** [comment]
That was it!

**Comment by mcornella** [comment]
Ok, thanks for debugging! Do you think this is ready to merge?

**Comment by subnut** [comment]
Yeah, I think so...

**Comment by subnut** [comment]
Don't you think these commits should be sqashed before merging?

**Comment by mcornella** [comment]
Yeah but I couldn't do it without force-pushing to the branch, which automatically closes the PR because I'm not the PR owner. Instead, I'll squash it now, when merging from the GitHub UI.

**Pull request merged**
