### PR TITLE
update: display logo in rainbow colors

### PR DESCRIPTION
**Pull request by mcornella**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

Displays the logo in rainbow colors when updating, similar to the [rainbow sticker sold on the website](https://shop.planetargon.com/products/ohmyzsh-ascii-art-stickers-set-of-3).

screenshot of the rainbow logo

### CODE REVIEW

**Comment by Stakker** [comment]
This is awesome and essential, thank you! :-) Could you possibly share the color codes? I also have added a similar logo into my shell startup, but I don't have the right colors...

**Comment by larson-carter** [comment]
@Stakker

Are these what you are wanting?: https://github.com/ohmyzsh/ohmyzsh/pull/8941/files#diff-6d2fa595805de6f141a64f905f4db641R4-R10

**Comment by Stakker** [comment]
Yes, exactly, thank you! :-)

**Comment by Chiramisu** [comment]
How can we disable this? I don't want it.

**Pull request merged**
