### PR TITLE
feat(git): added git aliases for working with tags

### PR DESCRIPTION
**Pull request by gitaarik**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Added git aliases for working with tags

### CODE REVIEW

**Comment by carlosala** [comment]
Hi Rik!
We have tons of PRs regarding the `git` plugin. In advance, sorry for the delay that could take this PRs to be reviewed ;)

**Comment by gitaarik** [comment]
Ok, thanks for the update :)

**Comment by adamchainz** [comment]
I like the idea of `gt` for `git tag`, but I’m not sold on the others.

`git push --tags` pushes *all* tags, which can lead to accidents. Using [`--follow-tags`](https://git-scm.com/docs/git-push#Documentation/git-push.txt---follow-tags) pushes only annotated tags associated with the current commit, which is preferable for many workflows. It can also be enabled by default with the `push.followTags` option, so there's no need for an alias change there.

`gshs` for `git show --stat` is not tag-related. Perhaps useful, but there are a bunch of other extra-detail-adding options on `git show` that seem similarly important...

**Comment by carlosala** [comment]
What Adam says makes much sense!
Thanks for the triaging :)

**Comment by gitaarik** [comment]
The `gt` alias for `git tag` was apparently already added by e2b855341bfd587590734da860d75ead7788810f and later again removed by 0e1e877ea9182f87b3ab34cbc2ea944b34f5345e because it supposedly clashes with [Graphite](https://graphite.dev/) CLI commands.

**Comment by adamchainz** [comment]
Thanks. We have rediscovered that with comments on #11910.

**Pull request closed without merging**
