### PR TITLE
added homeshick plugin

### PR DESCRIPTION
**Pull request by typekpb**

### CODE REVIEW

**Comment by mcornella** [comment]
Should this still be merged? Is there interest in this?

**Comment by ax42** [comment]
It would help me (for one) as a someone new to both zsh and homeshick

**Comment by robbyrussell** [comment]
Would be open to considering this but would like to see a README included. In the meantime, people are welcome to toss this into their custom/ plugins folder

**Comment by TheTechRobo** [comment]
By the way @robbyrussell, you can go to "Files changed" and request changes instead of closing PRs.

**Pull request closed without merging**
