### PR TITLE
feat(git): Add alias for 'git submodule add'

### PR DESCRIPTION
**Pull request by lmnotran**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Add `gsa` alias for `git submodule add`

### CODE REVIEW

**Comment by fmalcher** [comment]
Could you please add the new alias to the table in the README, too? 😊 Thanks!

**Comment by lmnotran** [comment]
@fmalcher Ooo, thanks for catching that! Just added it to the README

**Comment by lmnotran** [comment]
@fmalcher could you review this again?

**Comment by lmnotran** [comment]
CC: @mcornella

**Review by fmalcher — COMMENTED** [review]
LGTM 🙂

**Comment by lmnotran** [comment]
Hi @mcornella , could you review this?

**Comment by lmnotran** [comment]
@stevenpitts @mcornella @carlosala @rlankfo @daviddavis - Can someone review this? Please either reject or approve and merge this PR. It's been open for almost 11 months

**Comment by stevenpitts** [comment]
Sorry, I'm not a maintainer, I can't help you here

**Comment by daviddavis** [comment]
I'm also not a maintainer.

**Review by jmeridth — APPROVED** [review]

**Comment by lmnotran** [comment]
Bump

**Review by rlankfo — APPROVED** [review]
I'm also not a maintainer but this looks good to me 🏄

**Comment by adamchainz** [comment]
Adding a submodule seems like quite a rare activity. Does it really need a three-letter alias? 

Perhaps we would be better served with an alias like `gsub` for `git submodule`. `gsub add` isn’t so much to type, especially since one still needs to provide the repo URL and path. Then you could also use `gsub status` etc.

**Comment by carlosala** [comment]
I agree. We have the most common cases that are `init` and `update`, I wouldn't add more aliases to the specific case of submodules.
Thanks for the contribution and triaging!

**Pull request closed without merging**
