### PR TITLE
feat(git): added alias glm - git pull origin $(git_main_branch)

### PR DESCRIPTION
**Pull request by OmriBarZik**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Added alias for `git pull origin $(git_main_branch)` - `glm`

## Other comments:

There is an alias for `git pull upstream $(git_main_branch)` - (`glum`) and it's very handy, why not have the same concept in the origin remote.
I use this alias in my environment all the time.

### CODE REVIEW

**Review by TheTechRobo — APPROVED** [review]

**Comment by puneeth-r** [comment]
@TheTechRobo @OmriBarZik Any idea when this PR will be merged? This will be a great addition to the aliases.

**Comment by TheTechRobo** [comment]
Conflicts would need to be resolved, but even once they are there’s still a huge backlog of pull requests so it may take awhile

**Comment by OmriBarZik** [comment]
Hey @TheTechRobo, I've fixed the merge conflicts

**Comment by carlosala** [comment]
I'd say this alias is a bit niche. You could use `gupom` for the same purpose, and the only difference is that it adds the `--rebase` option. Normally you want to rebase on top of main, you don't want to create extra merge commits there.
Thanks for your contribution!

**Pull request closed without merging**
