### PR TITLE
fix(rtx)!: rename `rtx` plugin to `mise`

### PR DESCRIPTION
**Pull request by jaredallard**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

- Renames the `rtx` plugin to `mise` to reflect the new project name.

## Other comments:

This is a BREAKING CHANGE because the `rtx` plugin will no longer exist. I decided to not implement any transition logic because the author hasn't provided any wrappers for `rtx` to continue working once `mise` is installed. I feel that ohmyzsh shouldn't provide that.

### CODE REVIEW

**Comment by jaredallard** [comment]
Sorry for the plethora of post-open changes. Wanted to update the title and desc to be better :D

**Review by nelsonmestevao — APPROVED** [review]

**Comment by carlosala** [comment]
Hi! For sure we need to do so! I'll think about the best option, but removing 100% the old `rtx` plugin is not the best solution. Let's have a transition period, I'll push it here! Thanks for your contribution!

**Comment by carlosala** [comment]
Thanks for your contribution!

**Comment by nelsonmestevao** [comment]
I am getting at zsh start "] command not found" because of this plugin. Any idea why?

**Comment by carlosala** [comment]
I'm not able to reproduce. Could you send the session initialization logs (check how to [here](https://github.com/ohmyzsh/ohmyzsh/wiki/Troubleshooting#other-problems)) and send them to logs@ohmyz.sh?
Thanks!

**Pull request merged**
