### PR TITLE
feat(cli): add subcommands for plugin `enable` and `disable`

### PR DESCRIPTION
**Pull request by pollyduan**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- feat(CLI): add sub command for plugin: enable and disable

## Other comments:

Enable git plugin:

$ omz plugin enable git
INFO: Plugin named "git" was enabled.

$ omz plugin disable git
INFO: Plugin disable successfully.

Diasble git plugin:

$ omz plugin disable git
INFO: Plugin named "git" was disabled.

$ omz plugin enable git
INFO: Plugin enable successfully.

### CODE REVIEW

**Comment by jamespeapen** [comment]
The disable command breaks my config.

Before disable:
```
plugins=(forgit conda-zsh-completion fzf-tab zsh-syntax-highlighting zsh-autosuggestions)
```

After running disable it removes 's' from plugin names:
```
plugins=(forgit conda-z h-completion fzf-tab z h- yntax-highlighting z h-auto ugge tion )
```

**Comment by pollyduan** [comment]
Could you tell me about your OS? I tested it on Mac OS. It looks like there was an error in the regular expression when replacing Spaces at the end. Let me verify that.

**Comment by jamespeapen** [comment]
It's on Mac and the bug is still there. 
If the goal is to load plugins only when you want them, there is #9753 which allows loading plugins without changing the zshrc. I don't know if manipulating the config files from a command is a good idea.

**Comment by pollyduan** [comment]
@jamespeapen You are right, however, if a user wants to enable a plug-in, I think he will want to persist it.

**Comment by jamespeapen** [comment]
Temporary loading could be useful. See #9672

**Pull request merged**
