### PR TITLE
Update rails plugin commands

### PR DESCRIPTION
**Pull request by choosen**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:
* I want to reduce warnings using rails instead of rake aliases
```
DEPRECATION WARNING: Using `bin/rake routes` is deprecated and will be removed in Rails 6.1. Use `bin/rails routes` instead.
 (called from load at /Users/piotrwasiak/.rbenv/versions/2.7.1/bin/rake:23)
```
* I updated information about parameters and readme
* removed very legacy script commands

## Other comments:

Auto-completion does not work for me. I got this (--help is useless in current command)

obraz

### CODE REVIEW

**Comment by awasum** [comment]
@choosen I think it will be a good idea to squash the commits for this update to just one commit so that the git history looks clean. Do you know what I mean?

**Comment by choosen** [comment]
Ofc. I am going to do that

Piotr Wasiak

pon., 15 cze 2020, 14:34 użytkownik Awasum Yannick <notifications@github.com>
napisał:

**Comment by choosen** [comment]
@awasum  done ✅

**Comment by bartekpacia** [comment]
@choosen thanks
@awasum  I'm not sure how progress on this looks like, could you add the PR to the appropriate table in the spreadsheet?

**Review by 53jk1 — APPROVED** [review]

**Review by Archish27 — APPROVED** [review]

**Pull request closed without merging**
