### PR TITLE
Temporarily change the rainbow colours to blue and yellow

### PR DESCRIPTION
**Pull request by amxfonseca**
We are living unprecedented times. At this exact moment thousands of people are losing their lives by fighting a war that nobody wants to be in. Millions of people are being forced to flee their homes and leave everything behind.

Unfortunately there seems to be no easy way to deescalate such horrendous conflict.

For decades the development community has been showing the world that is possible to work together, independent of race of nationality. And this project one such example.

This change is not a political statement. It's not about good or bad, right or wrong. It's simply about the unnecessary suffering that millions of people are being subject to.

I noticed some other projects are taking similar actions. I think we should join the movement and hopefully the world can see that we do not stand by this (nor by any other) war.

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Change the *Oh my ZSH* logo rainbow pattern to blue and yellow.

## Remarks

I am not a design specialist. The 256 colour terminal has a limited colour pallet. So the chosen values are a naive approximation. We are open for improvement suggestions.

Screenshot 2022-03-03 at 11 18 29

PS: ~I was not able to test the true colour version of the change. It would be nice if someone could do a proper visual check~ 🙏 See comment bellow

### CODE REVIEW

**Comment by amxfonseca** [comment]
iTerm version (truecolor)

image

**Review by Tjolk072 — COMMENTED** [review]
Thank you very much for your help! Really appreciated! :-)

**Comment by mcornella** [comment]
Updated the logo to background colors:

### truecolor

truecolor logo screenshot

### 256bits

256color logo screenshot

**Comment by amxfonseca** [comment]
@mcornella That is a bit… less subtle 🙂

As long as we raise awareness I don’t really care about the final looks. 

We shouldn’t just keep this PR open forever. Some people are losing everything every passing day.

**Comment by hardenchant** [comment]
_This change is not a political statement._ – actually it is.

Of course, no one should suffer from political squabbles, but i think the community should also remain professional and have clean code without flags and political references. Now, its just emotions.

**Comment by robbyrussell** [comment]
If anyone stumbles across this PR, please consider contributing to one of these:

* https://opencollective.com/1kproject
* https://opencollective.com/sucho
* https://opencollective.com/europe

**Comment by amxfonseca** [comment]
> _This change is not a political statement._ – actually it is.
> 
> Of course, no one should suffer from political squabbles, but i think the community should also remain professional and have clean code without flags and political references. Now, its just emotions.

Increasing the awareness of an ongoing war whose perpetrators are committing atrocities against civilian population is now political? Rape, murder and torture now fit under politics. That seems a bit of a stretch.

Again, the community is free to decide if this change should be done or not. There are a lot of arguments that can be made if this should be merged. But stating it is just "emotions" kinda shows how detached from reality you currently are.

But I guess when all your news come directly from Pravda you can't expect much.

**Pull request closed without merging**
