### PR TITLE
fix(git)!: Standardize `git pull --reabse` aliases

### LINKED ISSUE #11104: Duplicate Alias Command for Git
### Describe the bug

I wanted to know what the shorthand command for `git pull --rebase origin master` and typed `alias | grep 'git pull'` and noticed a duplicate command.

```
$ alias | grep 'git pull'
ggpull='git pull origin "$(git_current_branch)"'
gl='git pull'
glum='git pull upstream $(git_main_branch)'
gpr='git pull --rebase'
gup='git pull --rebase'
gupa='git pull --rebase --autostash'
gupav='git pull --rebase --autostash -v'
gupom='git pull --rebase origin $(git_main_branch)'
gupomi='git pull --rebase=interactive origin $(git_main_branch)'
gupv='git pull --rebase -v'
```
The command 'git pull --relbase' is duplicated.

### Steps to reproduce

1. Open terminal
2. type: alias | grep 'git pull --rebase'

### Expected behavior

Only one config for 'git pull --rebase'

### Screenshots and recordings

_No response_

### OS / Linux distribution

macOS 12.5

### Zsh version

5.8.1

### Oh My Zsh version

master (d41ca84)

### Terminal emulator

iTerm2, Terminal.app, VSCode integrated terminal

### If using WSL on Windows, which version of WSL

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by zee-bit**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

- Revised aliases for `git pull --rebase` and it's derivates to the more standard form of `gpr*` from `gup*`.
- BREAKING CHANGE: The alias `gup` for `git pull --rebase` and its derivatives are replaced by `gpr` for standardization. This means the previous aliases would no longer be available. See git plugin README for list of deprecated aliases.

## Other comments:

Fixes #11104

### CODE REVIEW

**Comment by zee-bit** [comment]
Sorry, the commit was incomplete earlier (forgot to update, because of dinner). I had to force-push with the new changes to the same commit. Let me know if there's any other inconsistency.

**Review by LunarWatcher — APPROVED** [review]
LGTM. But this is a breaking change, so the PR needs to indicate that. See https://www.conventionalcommits.org/en/v1.0.0/ if you're not familiar with how

**Comment by zee-bit** [comment]
Hey @LunarWatcher, I have updated the PR desc as well as the commit to indicate a breaking change as per the link you provided. Please let me know if I am still missing anything. :)

**Comment by esemeniuc** [comment]
would love to see this also

**Review by rafaelbernard — APPROVED** [review]

**Comment by nicolasbarra** [comment]
Excited to see this merged after the conflicts have been resolved!

**Comment by zee-bit** [comment]
Updated!

**Review by tjarbo — CHANGES_REQUESTED** [review]
Reference to https://github.com/ohmyzsh/ohmyzsh/issues/11104#issuecomment-1336491627

**Comment by esemeniuc** [comment]
Bump to see this merged!

**Comment by rivenirvana** [comment]
+1 for merge

**Comment by carlosala** [comment]
@mcornella @adamchainz I'd like to hear your comments about it. IMO it makes sense, but it's kinda of a super crazy breaking change.
Maybe we could add a message for it (something like that `gup` is now deprecated and you should use `gpr`)?

**Comment by adamchainz** [comment]
Do we really need `--rebase` aliases anyway? One can configure `pull.rebase = true` and it will be used by default. I imagine most people using these aliases would be better off making it the default.

But if we are to keep them, I’m fine with a breaking change, perhaps with a warning for a period.

**Comment by mcornella** [comment]
We're currently polling on whether to proceed with this change on [this Discord message](https://discord.com/channels/642496866407284746/829052424723365889/1158467038537334836), in case you want to get your voice heard.

> Do we really need --rebase aliases anyway? One can configure pull.rebase = true and it will be used by default. I imagine most people using these aliases would be better off making it the default.

I agree with you that a config option is best for your use case if you do this by default. These aliases solve the use case of people who do different things based on different repositories (think personal vs company ones), for which an alias is significantly less overhead than custom configs per repository / path.

**Comment by mcornella** [comment]
Consensus is positive towards the change, reassigning to me to implement the deprecation notice functions for 1-2 months to accomodate alias users.

**Comment by u3u** [comment]
```sh
[oh-my-zsh] 'gup' is a deprecated alias, using 'gpr' instead.
```

⚠️ Please do not deprecate it!!! We have already grown accustomed to it. We will be distressed if the command suddenly becomes unusable!

**Pull request closed without merging**
