### PR TITLE
Add git add --interactive alias

### LINKED ISSUE #9347: GIT Shortcut: `gai` for `git add -i`
**Is your feature request related to a particular plugin or theme? If so, specify it.**
git

**Is your feature request related to a problem? Please describe.**
Not a problem, just a "missing" shortcut for git! ;)

**Describe the solution you'd like**
Would like to see a shortcut added for `git add --interactive` or `git add -i`. This shortcut could be called `gai`, as I do not currently see that used for any other shortcut. 

**Describe alternatives you've considered**
The only real alternative is to use the full git command `git add -i`.

### PR DESCRIPTION
**Pull request by alexpjohnson**
## Standards checklist:

- [X] The PR title is descriptive.
- [X] The PR doesn't replicate another PR which is already open.
- [X] I have read the contribution guide and followed all the instructions.
- [X] The code follows the code style guide detailed in the wiki.
- [X] The code is mine or it's from somewhere with an MIT-compatible license.
- [X] The code is efficient, to the best of my ability, and does not waste computer resources.
- [X] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Adds an alias for git add --interactive

## Other comments:

Closes #9347

### CODE REVIEW

**Comment by alexpjohnson** [comment]
Would anyone be able to help me debug why CI failed? Seems like it's a simple change that mirrors other like PRs### .

**Comment by jrista** [comment]
Thanks for taking this up, @alexpjohnson! If I had known it was really this simple, I'd have done the PR myself...for some reason, I thought it would be more involved.

**Review by 53jk1 — APPROVED** [review]

**Comment by alexpjohnson** [comment]
@mcornella Is it possible to get this merged in this week?

**Comment by mcornella** [comment]
I've decided to reject this. See reason here: https://github.com/ohmyzsh/ohmyzsh/issues/9347#issuecomment-726155168

**Pull request closed without merging**
