### PR TITLE
feat(bira): add support for `kube-ps1` prompt

### PR DESCRIPTION
**Pull request by SgtDaJim**
bira is a theme that has a special style prompt. In order to make it more beautiful when using kube-ps1 prompt plugin, i made a little modification.

One thing I have to point out is, after merge, when using bira theme, bira will detect whether include kube-ps1 in plugins. if included, the prompt will changed immediately, needn't to set PROMPT=$PROMPT'$(kube_ps1) '

before:
image

after:
image

### CODE REVIEW

**Review by 53jk1 — APPROVED** [review]

**Comment by retrry** [comment]
What do we need to do, to get this PR merged?

I wanted to open a new PR with changes like this (https://github.com/retrry/ohmyzsh/commit/c42f6dd5f4e22da3a99639d0dc4c081fa94c8855), but saw this PR.

**Comment by SgtDaJim** [comment]
Sorry I close it by mistake and re-open it..
So is there anything I can do to help merge the update?

**Comment by zamai** [comment]
Not sure who to tag, but the fix is still valid in 2024 :) 
@kbakdev maybe you can merge it?

**Comment by carlosala** [comment]
Thanks for your contribution!

**Review by carlosala — COMMENTED** [review]
LGTM!

**Comment by zamai** [comment]
that was fast  🥇 
now I just need to understand when it would be released :)

**Comment by carlosala** [comment]
You can just `omz update` and you'll have it! 😉

**Pull request merged**
