### PR TITLE
Respect `$ZDOTDIR` in installer and uninstaller

### LINKED ISSUE #9001: Installer does not respect $ZDOTDIR
**Describe the bug**
`tools/install.sh` installs into `~` even when `$ZDOTDIR` is set.

**To Reproduce**
1. `cd "$(mktemp -d)"`
2. `ZDOTDIR=$PWD zsh -d`
3. `sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"`

**Expected behavior**
OMZ installs into `$ZDOTDIR`.

**Actual behavior**
OMZ installs into `~`.

**Desktop (please complete the following information):**
 - OS / Distro: macOS
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator: Apple Terminal

### LINKED ISSUE #10479: Install script does not account for .zshrc in ZDOTDIR
### Describe the bug

When zsh configuration is using the environment variable ZDOTDIR, the oh my zsh install script incorrectly considers no zsh config file is present.

### Steps to reproduce

1. Create  `~/.zshenv` with content:

```
ZDOTDIR=${HOME}/.config/zsh
```

2. Put actual zsh config at ~/.config/zsh/.zshrc

**Incorrect Behavior:**

3. When installing with `curl`, the install script considers that no .zshrc exists and creates one in $HOME:

```
Looking for an existing zsh config...
Using the Oh My Zsh template file and adding it to `~/.zshrc`.
```

### Expected behavior

Oh my zsh should put its configuration in `$ZDOTDIR/.zshrc` and not create another .zshrc.

### Screenshots and recordings

_No response_

### OS / Linux distribution

Ubuntu 20.04.2. LTS 

### Zsh version

5.8

### Oh My Zsh version

Install script 2021-12-04

### Terminal emulator

Terminator

### If using WSL on Windows, which version of WSL

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mcornella**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- feat(installer): respect and install in `$ZDOTDIR` if set (#9376)
  Fixes #9001, fixes #10479

## Other comments:

- [x] Installer support
- [ ] Uninstaller support
- [ ] Figure out other places where it might need to be taken into consideration

### CODE REVIEW

**Comment by carlosala** [comment]
Looks nice!

**Comment by carlosala** [comment]
Maybe changing the documentation would be nice, just adding before the `sh -c` a possible `ZDOTDIR=somewhere`

**Comment by librick** [comment]
Just read through this PR and looks good to me for what it's worth.
Only nitpick is that it might be useful to print the full path to the .zshrc file in the "Found .zshrc ..." log messages so that it's more obvious which file was found and where. i.e., on line 313 (https://github.com/ohmyzsh/ohmyzsh/commit/ebfd5eba641697d4b96d8f7dba9c53650c731ee4#diff-5dc310979be51acc76eb748ef379630b65614b5a4132fc5a870019ade043935bR313) and line 328 (https://github.com/ohmyzsh/ohmyzsh/commit/ebfd5eba641697d4b96d8f7dba9c53650c731ee4#diff-5dc310979be51acc76eb748ef379630b65614b5a4132fc5a870019ade043935bR328) print `Found $zdot/.zshrc.`

I think it would be beneficial to merge this PR even before any corresponding changes to the uninstall script are made. The uninstall script already ignores the `ZSH` variable and tries to delete `~/.oh-my-zsh` if it exists. In my opinion, uninstalling oh-my-zsh at non-default paths should be a separate PR from this one. Thanks for all the help on this!

**Review by carlosala — APPROVED** [review]
@mcornella LGTM! 🚀

**Comment by mcornella** [comment]
@librick I applied your suggestions. If you try this out, let me know if you have any other issues, thanks!

**Pull request merged**
