### PR TITLE
feat(git): add `gdu` alias to diff against upstream

### PR DESCRIPTION
**Pull request by caugner**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Adds the `gdu` alias in the git plugin to `diff` against the tracked upstream branch (`@{u}`)

## Other comments:

(None.)

### CODE REVIEW

**Comment by caugner** [comment]
@mcornella Any chance to get this alias merged?

**Review by 53jk1 — APPROVED** [review]

**Review by liijunwei — APPROVED** [review]

**Comment by liijunwei** [comment]
Mine PR is `git diff HEAD@{u} HEAD`, which is duplicated...
I'll cancle my PR, goodluck to you. @caugner

**Comment by liijunwei** [comment]
But ugh... your commit message might be "feat(git): add alias for `git diff`"  as CONTRIBUTING GUIDELINES suggestd.

**Comment by caugner** [comment]
> 
> 
> But ugh... your commit message might be "feat(git): add alias for `git diff`" as CONTRIBUTING GUIDELINES suggestd.

Looks like the guidelines have changed since I opened this PR in March 2020 (e.g. 831089a3757ed08170c7e7687eb3e0377f286d82)...

**Comment by mcornella** [comment]
Hey can you add this to the README?

**Comment by caugner** [comment]
> 
> 
> Hey can you add this to the README?

✅ in 10a5f35e.

**Comment by mcornella** [comment]
Thanks and apologies for the delay!

**Pull request merged**
