### PR TITLE
feat(jsontools): Added alias to pretty print json-lines (ndjson)

### PR DESCRIPTION
**Pull request by eduardofv**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Added `pp_ndjson`alias to pretty print [ndjson a.k.a. json-lines](http://ndjson.org)
- Updated README to reflect new function

## Other comments:

...

### CODE REVIEW

**Comment by eduardofv** [comment]
I'm adding the rationale for the feature I had on an separated issue:

## If the feature solves a problem you have, specify it here.
JSON lines (http://ndjson.org) is a format that extends JSON standard to multi-line independent json objects. It's used on streaming, json storage, etc. Sometimes it's necessary to see easily whole or part of such a file.

## Describe the proposed feature.
Want to be able to easy view ndjson streams:

```
# echo two separate json objects and pretty print both
echo '{"a": "b"}\n{"c": [1,2,3]}' | pp_ndjson
```
## Describe alternatives you've considered
`python -m json.tool`

**Comment by mcornella** [comment]
Pulled and refactored in #10203 (it adds support for `is_json` and the rest). Please check it out with `omz pr test 10203` and let me know if there are any issues.

**Comment by eduardofv** [comment]
On my tests everything looks fine

**Comment by mcornella** [comment]
Thanks!

**Pull request closed without merging**
