### PR TITLE
feat(z): replace `rupa/z` with `agkozak/zsh-z`

### LINKED ISSUE #10975: z plugin tab completion doesn't work
### Describe the bug

Using Debian testing (bookworm), fully updated as of today.

Using z plugin with Oh-My-Zsh doesn't work. When I type `z` and then press the `Tab` key, instead of shows the most frequent directories, it shows the following output:

Captura de pantalla_2022-06-04_15-54-52

However, when I use the `z` plugin without Oh-My-Zsh (i.e. only using Zsh and then `source ~/.oh-my-zsh/plugins/z/z.zsh`, it works OK:

Captura de pantalla_2022-06-04_15-59-51

### Steps to reproduce

1. Enable plugin `z`.
2. Type `z` + press `Space` + press `Tab` key.

### Expected behavior

It shows the most frequent directories and I can select one using the `Tab` key.

### Screenshots and recordings

_No response_

### OS / Linux distribution

Debian testing (bookworm)

### Zsh version

zsh 5.9 (x86_64-debian-linux-gnu)

### Terminal emulator

Alacritty

### If using WSL on Windows, which version of WSL

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by carlosala**
### Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

Title is descriptive
Closes #10975

### CODE REVIEW

**Comment by mcornella** [comment]
LGTM but let me test it out tomorrow.

**Comment by mcornella** [comment]
Approved after extensive testing.

Similarities:
- All behavior from rupa/z is matched in this port (include compatibility with settings)

Differences:
- Directory completion is better
- MANUAL.md has more information about other available settings
- `awk` is not used as well as many other changes in the underlying code (without breaking changes)

**Comment by moniquelive** [comment]
After this upgrade I keep getting this:

image

It's unusable now. Please advise.

**Comment by mcornella** [comment]
Hey Monique, thanks for reporting! Could you let me know the output of `which z`?

**Comment by moniquelive** [comment]
Sure:

```shell
❯ which z
z () {
	[ $# -gt 0 ] && _z "$*" && return
	cd "$(_z -l 2>&1 | fzf --height 40% --nth 2.. --reverse --inline-info +s --tac --query "${*##-* }" | sed 's/^[0-9,.]* *//')"
}
```

**Comment by moniquelive** [comment]
I probably downloaded this and forgot! I'm sorry.
Guess I'll leave without my "z<enter> / fzf" workflow for now :(

**Comment by mcornella** [comment]
I think you can readapt this function by replacing `_z` (which is now the completion function) to `zshz`.

**Pull request merged**
