### PR TITLE
fix(battery): use `pmset` for battery percentage in macOS

### PR DESCRIPTION
**Pull request by aimuz**
returns the battery charge consistent with the system battery manager

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- [...]

## Other comments:

...

### CODE REVIEW

**Comment by mcornella** [comment]
I don't have a Mac to test this, so can you post the following?
- Output with old version
- Output with new version
- Output of `pmset -g batt`

**Comment by aimuz** [comment]
### old version

```bash
function battery_pct() {                                                                                                                                                                                                                             
    local battery_status="$(ioreg -rc AppleSmartBattery)"
    local -i capacity=$(sed -n -e '/MaxCapacity/s/^.*"MaxCapacity"\ =\ //p' <<< $battery_status)
    local -i current=$(sed -n -e '/CurrentCapacity/s/^.*"CurrentCapacity"\ =\ //p' <<< $battery_status)
    echo $(( current * 100 / capacity ))
}
$ battery_pct                                                                                                                                                                                                                                            
97
```

### new version

```bash
function battery_pct() {                                                                                                                                                                                                                             
    pmset -g batt | grep -Eo "\d+%" | cut -d% -f1
}
$ battery_pct                                                                                                                                                                                                                                            
100
```

### pmset -g batt

```
Now drawing from 'Battery Power'
 -InternalBattery-0 (id=8388707)	100%; discharging; 2:28 remaining present: true
```


The output of the old version may be closer to the actual situation of the battery, because it is calculated by its own algorithm, while the new version directly uses the system battery management value. There will be differences between them.

**Review by 53jk1 — APPROVED** [review]

**Comment by aimuz** [comment]
@mcornella Hello, what is the PR status

Recently, I haven't seen any state

**Comment by mcornella** [comment]
Thanks!

**Pull request merged**
