### PR TITLE
feat(rbw): add completion for `rbw` Bitwarden client

### PR DESCRIPTION
**Pull request by carlosala**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Adding [`rbw`](https://github.com/doy/rbw) plugin

## Other comments:

[`rbw`](https://github.com/doy/rbw) is nowadays the most used CLI for [Bitwarden](https://bitwarden.com), an Open Source password manager.

### CODE REVIEW

**Comment by jsoref** [comment]
Hi, you're going to need to rebase this PR onto master in order to pass the spell checker which is going to ask you to add lines to `.github/actions/spelling/expect.txt`:

```
bitwarden
rbw
```

(You can insert them alphabetically, or just place them somewhere.)

**Comment by carlosala** [comment]
Done, thank you!

> Hi, you're going to need to rebase this PR onto master in order to pass the spell checker which is going to ask you to add lines to `.github/actions/spelling/expect.txt`:
> 
> ```
> bitwarden
> rbw
> ```
> 
> (You can insert them alphabetically, or just place them somewhere.)

**Comment by mcornella** [comment]
https://github.com/ohmyzsh/ohmyzsh/pull/10515#issuecomment-1002110292:
> Can you update this to use background code, as in `fnm`, `deno`, `gh`, ... plugins?

**Comment by carlosala** [comment]
@mcornella done!

**Pull request merged**
