### PR TITLE
feat: added initial support for flatpak

### PR DESCRIPTION
**Pull request by nesper8**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

- Added a plugin for managing (installing, uninstalling, searching, pinning, running, killing, backing up, etc...) flatpak applications

### CODE REVIEW

**Comment by claymorwan** [comment]
Is this plugin available ? It doesn't seem to be in the repo so I wanted to make a flatpak plugin but saw this one

**Comment by nesper8** [comment]
Closing due to lack of interest

**Comment by claymorwan** [comment]
ig that means I can't open a pull request for mine

**Comment by nesper8** [comment]
PR has been open and merge ready for over 11 months

Another similar PR which aims to add flatpak aliases also suffered the same fate 

I take that ohmyzsh has no intent nor incentive to ever support flatpak aliases for some reason or other

I'm no longer interested in this project because I moved to Windows about 4 months ago and forgot about this PR

**Comment by claymorwan** [comment]
Kinda weird that they refuse a Flatpak plugin even tho it's widly used, but yet they have a Snap plugin

**Pull request closed without merging**
