### PR TITLE
feat(npm): add alias for `npm run build`

### PR DESCRIPTION
**Pull request by sarah-noor-12232**
This is my first ever attempt at open source contribution, and it is intended for the HacktoberFest. (although I only added 2 lines, I'm not sure if it qualifies) Anyway, enjoy your alias!

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [ ] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [ ] The code is stable and I have tested it myself, to the best of my abilities.
- [ ] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

- added requested alias for `npm run build` as `npmrb`

## Other comments:

I did not test this. (I am not sure how to test a different branch of zsh)

### CODE REVIEW

**Comment by carlosala** [comment]
Thanks, could you please document it in the README? Thanks!

**Comment by sarah-noor-12232** [comment]
> Thanks, could you please document it in the README? Thanks!

Done :D

**Review by carlosala — APPROVED** [review]

**Comment by carlosala** [comment]
Thanks for your contribution!

**Comment by nazirahmad7340** [comment]
Thank you

**Pull request merged**
