### PR TITLE
fix(debian)!: remove ar alias

### LINKED ISSUE #9304: debian plugin shadows ar archiver
**Describe the bug**

debian plugin sets up alias `ar` which shadows `ar` archiver from `binutils` package.
This program is used for creating libraries and deb archives, shadowing it would introduce problems.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable `debian` plugin
2. Run command `which ar`
3. See `ar: aliased to sudo apt remove`

**Expected behavior**
`ar` must not be shadowed

**Desktop:**

 - OS / Distro: Gnu/Linux Debian bullseye
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator: [`st`](https://st.suckless.org/)

### PR DESCRIPTION
**Pull request by carlosala**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

- Remove `ar` alias

## Other comments:

This alias was shadowing `ar` archiver. Closes #9304

### CODE REVIEW

**Review by LunarWatcher — APPROVED** [review]

**Comment by mcornella** [comment]
I agree to remove the conflicting alias, but as it is a breaking change I will flag it as such.

**Comment by carlosala** [comment]
Yes, me too👌🏻

**Comment by carlosala** [comment]
@mcornella let's merge this, could you add the `!` at the message when merging?

**Comment by mcornella** [comment]
There is also an `ar` function that will take precedence and related completion setup for the same. I will make the changes tomorrow and write a breaking change message for the changelog.

**Pull request merged**
