### PR TITLE
Added "doas" plugin to support a "sudo" alternative

### PR DESCRIPTION
**Pull request by NeoTheFox**
## Changes:

- Added "doas" plugin that is just a carbon copy of "sudo" plugin.

## Other comments:

This will help OpenBSD users and Linux users that use doas instead of sudo for privilege escalation. You can also use doas on OSX. There isn't really any new code here or major changes.

### CODE REVIEW

**Comment by NeoTheFox** [comment]
@dongweiming can you please check this as an author of the original plugin?

**Comment by mcornella** [comment]
The problem with a "rip-off plugin" is that once changes are made to one, the other becomes obsolete. A better alternative is to make the `sudo` plugin configurable to allow setting the `sudo` word and the `sudo -e`/`sudoedit` word.

The replacement for `sudo` would be `doas`, but does `doas` have an "edit" equivalent?

**Comment by 154pinkchairs** [comment]
@mcornella, well, you can use doas $EDITOR. The risk of plugin becoming obsolete is much less of an issue than with sudo, because doas is dead simple and will remain like this, that's it's objective. Will try working on a solution though.

**Comment by carlosala** [comment]
@154pinkchairs actually `sudo $EDITOR` does not do exactly the same as `sudo -e`

**Comment by carlosala** [comment]
Let's close this in favour of #11395

**Pull request closed without merging**
