### PR TITLE
Add autocompletion plugin for rustup subcommands

### PR DESCRIPTION
**Pull request by dwillie**
Added a new plugin for rustup which supports autocomplete across the top level commands and subcommands where they apply

### CODE REVIEW

**Comment by dgellow** [comment]
Any reason the PR hasn't been merged?

**Comment by dwillie** [comment]
Not that I know of

**Comment by robbyrussell** [comment]
Could we get a README file for this?

**Comment by pkulev** [comment]
Oh, wow.
I've created separate plugin: https://github.com/pkulev/zsh-rustup-completion.
@robbyrussell, I can create PR here, but there is little quirk: rustup can generate autocomplete itself.
How can I integrate generation with standard oh-my-zsh update pipeline?

**Comment by dwillie** [comment]
Sorry this sat here for so long - @pkulev's solution does sound superior to this, is there perhaps another example of a plugin using generated autocomplete?

**Comment by mcornella** [comment]
The `npm` plugin uses cached completions, we could adapt that one.

**Comment by ccqpein** [comment]
Is it still open?

**Comment by mcornella** [comment]
ping

**Pull request closed without merging**
