### PR TITLE
feat(plugin): :sparkles: Create pnpm plugin

### PR DESCRIPTION
**Pull request by felipe-heredia**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

- Add new plugin for `pnpm`
- Add completion for `pnpm`
- Add aliases for `pnpm`

### CODE REVIEW

**Comment by larson-carter** [comment]
Hey @felipe-heredia 

Thank you for taking the time to contribute to OMZ.

However at this time we are not accepting new: [plugins](https://github.com/ohmyzsh/ohmyzsh/wiki/External-plugins) due to how many we [currently have](https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins-Overview)

Due to how many we have actively and how many have to be maintained pnpm plugin has not been added yet, however it can get some use as an external one for the community.

CC: @carlosala

**Comment by LunarWatcher** [comment]
Duplicate of https://github.com/ohmyzsh/ohmyzsh/pull/9793 anyway

**Comment by felipe-heredia** [comment]
@LunarWatcher I've duplicated it because there's been no interaction with @mheob comment in about a year.

**Comment by carlosala** [comment]
It seems like there's already a cool external [`pnpm` plugin](https://github.com/ntnyq/omz-plugin-pnpm).
We'd accept a PR adding it as an external plugin!
Thanks for your contribution!

**Pull request closed without merging**
