### PR TITLE
[emotty] fix typo that resulted in math error

### PR DESCRIPTION
**Pull request by mcornella**
Solves #5482.

### CODE REVIEW

**Comment by dubbadubbadubbacha** [comment]
Still getting this error on FreeBSD. I believe the tty location is different.

**Comment by mcornella** [comment]
What's the value of `$TTY`?

**Comment by mcornella** [comment]
That's weird. What do you get running `tty`? What zsh version are you using?

**Comment by dubbadubbadubbacha** [comment]
tty returns <code>/dev/pts/1</code>
and myt zsh version is 5.6.2

**Comment by mcornella** [comment]
@dubbadubbadubbacha thanks for waiting so long. I've submitted #7844 with a possible fix, let me know if it works.

**Comment by mcornella** [comment]
Ping @dubbadubbadubbacha. Please run `echo ${(%):-%l}` so I can make one more test.

**Comment by mcornella** [comment]
Nevermind I pushed the fix. It should all go smoothly now.

**Pull request merged**
