### PR TITLE
Support for the racket tools: raco and racket

### PR DESCRIPTION
**Pull request by catull**
Add support for Racket language tools `raco` and `racket`.

### CODE REVIEW

**Comment by mcornella** [comment]
Has no interest.

**Comment by catull** [comment]
@mcornella Too bad, can you at least state your reasoning ?
This PR is almost 2 years now.
What is your point of criticism ?
"Has no interest." is not helpful.

**Comment by mcornella** [comment]
Meaning there are no user +1s or comments. It makes no sense to merge it if no users will use it.

**Comment by catull** [comment]
How about now ?

**Pull request closed without merging**
