### PR TITLE
git - display upstream remote/branch for the given local branch

### PR DESCRIPTION
**Pull request by DFieldFL**
In response to Issue #5676

### CODE REVIEW

**Comment by easterwood** [comment]
Hi,

I tried this change with the amuse theme but the upstream isn't displayed in the prompt. The amuse theme uses the function `git_prompt_info`. 

If I test the `parse_git_upstream_branch` on the command line the upstream branch name is displayed. 



Any ideas?

**Comment by DFieldFL** [comment]
@easterwood I don't seem to be having the same issue. See Below.

attached remote branch

Things to try out.

1. Did you restart your terminal session?
2. Did you make changes to the `git_prompt_info` function on this line? https://github.com/robbyrussell/oh-my-zsh/pull/5677/files#diff-6fd2f97d5b3acf53783112ad92948f12R7

**Comment by easterwood** [comment]
I forgot to mention that I merged your change into this repo w/o conflicts.

**Comment by DFieldFL** [comment]
Did you trying restarting your terminal/session?

**Comment by easterwood** [comment]
After restarting the pc the behavior is the same.

**Comment by easterwood** [comment]
Hm, I `source`ed the `lib/git.zsh` file and now it works.

**Pull request closed without merging**
