### PR TITLE
Add Insecure completion-dependent directories detected section to README

### PR DESCRIPTION
**Pull request by gliptak**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

### CODE REVIEW

**Comment by mcornella** [comment]
There's a very long and informative error message printed when this happens, which already points out the same. It's better to put that in the terminal than expecting the user to go to the README for a solution to their specific problem, isn't it?

**Comment by gliptak** [comment]
I do not recall seeing ```ZSH_DISABLE_COMPFIX=true``` in the informative message.

**Comment by mcornella** [comment]
It is there: https://github.com/ohmyzsh/ohmyzsh/blob/40b013f5f119be27bd2fdece431cf4979193bd25/lib/compfix.zsh#L40-L41

**Comment by gliptak** [comment]
@mcornella thank you. maybe I had an older version

**Pull request closed without merging**
