### PR TITLE
Added flatpak plugin to manage flatpak.org applications

### PR DESCRIPTION
**Pull request by robb-randall**
## Standards checklist:

- [X] The PR title is descriptive.
- [X] The PR doesn't replicate another PR which is already open.
- [X] I have read the contribution guide and followed all the instructions.
- [X] The code follows the code style guide detailed in the wiki.
- [X] The code is mine or it's from somewhere with an MIT-compatible license.
- [X] The code is efficient, to the best of my ability, and does not waste computer resources.
- [X] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:
- Added flatpak plugin
- Adds aliases to manage flatpak applications
- Creates aliases for installed flatpak applications

## Other comments:
- I am not affiliated in any way with flatpak.org, just a flatpak user.

### CODE REVIEW

**Review by 53jk1 — APPROVED** [review]

**Comment by robb-randall** [comment]
@53jk1 - Is there anything I need to do to get my PR merged?

**Comment by robb-randall** [comment]
Due to lack of interest, closing.

**Comment by TheTechRobo** [comment]
Don't do that! There's a HUGE backlog of PRs - just because they haven't gotten around to it, doesn't mean that they don't care!

**Comment by cirelli94** [comment]
I think this is an useful plugin and I would be interested in using it :+1: 
There is [here](https://github.com/jackpot51/dotfiles/blob/85eba3fa98b09a46f390367a3d1b59d9b6745c7b/bash/.bash_aliases) an interesting implementation with check if there is already a command at that name that I'd like to see implemented (maybe with a warning in that case).

**Pull request closed without merging**
