### PR TITLE
Add git-lfs plugin

### PR DESCRIPTION
**Pull request by hellovietduc**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Add git lfs plugin, which is requested in #8598
- Add a few more aliases git the current git plugin as suggested in #8598

### CODE REVIEW

**Comment by vietduc01100001** [comment]
@bartekpacia In my oppinion, it's fine leaving it there. But if you think it's not OK, I'll remove it. I'm new to contribute to ohmyzsh so just tell me if something's wrong in my PR. Thank you.

**Comment by bartekpacia** [comment]
@vietduc01100001 No no, it's just my personal opinion. I'm quite new to `ohmyzsh` too. 
Hopefully we can get more feedback from @larson-carter

**Comment by larson-carter** [comment]
@vietduc01100001 So if this is going to be a completely separate plugin then why are you adding aliases to the git plugin? Couldn't all of this code simply be made under git? Instead of us having to have a user enable 2?

**Comment by vietduc01100001** [comment]
@larson-carter I just added all the suggested aliases from the issue, so it's kind of messy I guess. I think I can undo the changes to the git plugin, and make a separate PR for that?

**Comment by larson-carter** [comment]
@vietduc01100001 That might be the simplest solution. Ideally you would rebase from the master branch and finish your work here.

**Comment by vietduc01100001** [comment]
@larson-carter @bartekpacia I've updated my PR. Please take a look!

**Comment by mcornella** [comment]
Thanks!

**Comment by hellovietduc** [comment]
> Thanks!

Thank you very much!

**Pull request merged**
