### PR TITLE
Cleanup whitespaces in aliases table

### PR DESCRIPTION
**Pull request by tvedeane**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Just cleanup of raw MD file

### CODE REVIEW

**Review by TheTechRobo — APPROVED** [review]
Looks fine to mee, except for 1 thing:

do newlines still work? newlines in markdown need either two spaces after a sentence like so  
or two linebreaks which this doesn't have.

**Comment by TheTechRobo** [comment]
Why did I just approve that? I have a lot to learn about GH.

**Comment by tvedeane** [comment]
Yes, it looks like the newlines are handled correctly. I visually compared current [master](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git) with the [result](https://github.com/tvedeane/ohmyzsh/tree/patch-1/plugins/git) of applying my patch.

**Comment by TheTechRobo** [comment]
Ok, then sounds good!

**Comment by mcornella** [comment]
Closed in favor of https://github.com/ohmyzsh/ohmyzsh/pull/9743 or https://github.com/ohmyzsh/ohmyzsh/pull/10101.

**Pull request closed without merging**
