### PR TITLE
feat(ys): add virtualenv prompt info

### PR DESCRIPTION
**Pull request by MrAureliusR**
Now this theme will show if you are in a virtualenv, and if so, what the name of the virtualenv is.

### CODE REVIEW

**Comment by MrAureliusR** [comment]
I have been using this theme with this addition for a few months now, and it works perfectly with all the plugins I use.

**Review by 53jk1 — APPROVED** [review]

**Comment by MrAureliusR** [comment]
Is going to be merged eventually? It's been almost a year, and it's a fairly trivial change.

**Comment by MrAureliusR** [comment]
Should I close this PR? I don't think I've ever had one sit _this_ long before.
I thought it was useful, but since it hasn't been merged I'm assuming there's a reason why? Did I not match formatting? Is there a better way I could have achieved the same result? I am happy to refactor or re-write the commit if that's the issue.

**Comment by TheTechRobo** [comment]
@mcornella is very busy with the hundreds of PRs. Don't fret - it will eventually be reviewed.

**Comment by mcornella** [comment]
Sorry it took so long.

**Pull request merged**
