### PR TITLE
Added rtx plugin (asdf replacement)

### PR DESCRIPTION
**Pull request by demonkillerr**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:
Added a plugin for rtx, which is faster asdf as it is written in rust. Solves #11700.
- [...]

## Other comments:
I would like to add aliases to both rtx and asdf based on use cases of users. An example would be
```alias install = "rtx install"```
...

### CODE REVIEW

**Comment by robbyrussell** [comment]
Hey there -- we really appreciate the contribution!

Cheers,
Robby

**Comment by tilgovi** [comment]
@demonkillerr I'm testing this out on two systems and seeing some weirdness.

On mac OS with rtx installed by brew, the `libexec` directory that's being referenced in the code doesn't exist. Is it possibly an arm/x86 difference? I'm on x86.

On Ubuntu with rtx installed via apt, the binary is `/usr/bin/rtx` and there are no other files installed that I can find. There is no completion file, for instance. I have to run `eval "$(rtx completion zsh)"`.

Any thoughts on either of these? I'm happy to try a PR, unless this all makes immediate sense to you and you want to make a quick fix.

**Comment by mcornella** [comment]
@tilgovi can you test #11949? `omz pr test 11949` should work for you

**Comment by tilgovi** [comment]
That is better insofar as it finds the rtx command. I think I prefer an option to set up shims instead of using activate, though, as it's more compatible with IDEs and such. But if this is how the community would prefer it, what you've got is fine!

**Comment by tilgovi** [comment]
Alternatively, it probably does no harm to add the shims first, then activate, and let the activation take precedence in the PATH? I defer to folks who are better acquainted with rtx.

**Comment by tilgovi** [comment]
For now I have this in `.oh-my-zsh/custom/rtx.zsh`, along with the plugin activated:

```
if [[ -z "$RTX_DATA_DIR" ]]; then
	export RTX_DATA_DIR="${XDG_DATA_HOME:-${HOME}/.local/share}/rtx"
fi

path=("$RTX_DATA_DIR/shims" $path)
typeset -U path
```

**Comment by mcornella** [comment]
> Alternatively, it probably does no harm to add the shims first, then activate, and let the activation take precedence in the PATH?

This seems like a sensible option, could you open a PR for this?

**Pull request merged**
