### PR TITLE
Add plugin clipboard

### PR DESCRIPTION
**Pull request by bb2020**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Adding a new plugin.

## Other comments:

This plugin replaces kill-ring of zsh with system clipboard by overriding default bindings. Copying and pasting between any application and zsh becomes much more seamless.

### CODE REVIEW

**Comment by TriMoon** [comment]
I would suggest a different name for this plugin, the current title suggest **clearing** the clipboard.
Maybe a good alternative would be just plain "clipboard"?

**Comment by bb2020** [comment]
I agree. I was thinking the same thing.

**Comment by TriMoon** [comment]
PS: why the strange extension on the README?
`.org` should be `.txt` because it's a plain text file...

**Comment by bb2020** [comment]
It is not plain text by the way. Org-mode is rendered by Github, similar to Markdown. It is documented [here](https://github.com/github/markup).

**Comment by bb2020** [comment]
Is Markdown the only accepted format?

**Comment by TriMoon** [comment]
> @bb2020 
> It is not plain text by the way. Org-mode is rendered by Github, similar to Markdown. It is documented [here](https://github.com/github/markup).
> Is Markdown the only accepted format?

First time i hear about `org` mode, no idea if markdown is the **only** accepted format but it is the most used one for sure... :wink:

**Comment by bb2020** [comment]
Yeah, that's for sure. `org-mode` is the awesome Emacs note taking format. As this plugin modifies zsh Emacs bindings, `org` is more relative to the context.

**Comment by mcornella** [comment]
Please use Markdown for consistency and document what each key binding does.

**Comment by bb2020** [comment]
Done. Actions of the key bindings are unchanged. It tries to modify clipboard or cutbuffer while executing the same action.

**Comment by mcornella** [comment]
This is not as easy to understand as you think it is. A little background into what a kill-ring or cutbuffer are would go a long way for this plugin to be used. Plus, I know the key bindings are the same as the default (only adding the text to the clipboard), but it's always a good idea to describe what they do. A Markdown table would be great, for example:
```markdown
| Key binding | Description                                       |
|-------------|---------------------------------------------------|
| CTRL+K      | Cuts the line and puts it in the system clipboard |
```

**Comment by bb2020** [comment]
Done with the table.

**Review by 53jk1 — APPROVED** [review]

**Comment by bb2020** [comment]
Any updates on this getting merged?

**Comment by bb2020** [comment]
Any updates on this getting merged?
Ping @mcornella

**Pull request closed without merging**
