### PR TITLE
Add zsh-interactive-cd

### PR DESCRIPTION
**Pull request by changyuheng**
[zsh-interactive-cd](https://github.com/changyuheng/zsh-interactive-cd) is a fish like interactive tab completion plugin for `cd`.

demo

### CODE REVIEW

**Comment by fianreebonz** [comment]
Wah love to wait this one merge

**Comment by slavaGanzin** [comment]
@changyuheng @fianreebonz 

Give a try: https://github.com/junegunn/fzf

**Comment by changyuheng** [comment]
@slavaGanzin This plugin is built on top of fzf

**Comment by svanharmelen** [comment]
Would love this as well...

**Comment by mcornella** [comment]
Pulled in 3ec04997.

I removed the LICENSE (MIT, same as OMZ) and the gif which added 1.4MB to the repository. Instead, I uploaded it to the first post of this PR and linked it from there. I also fixed the README a bit.

Sorry for taking so long!

**Pull request closed without merging**
