### PR TITLE
Followup to #5299 much more dynamic completion for angular cli

### PR DESCRIPTION
**Pull request by catull**
This PR updates the completion for Angular CLI.

### CODE REVIEW

**Comment by dianjuar** [comment]
Hi. I was going to make a pull request like this, but your PR has a best approach using `angular-cli` directly.
Congrats.

I was just going to create the plugin by hand with the output of `ng completion --zsh`.
I saw two problems...
> I have angular-cli version `1.0.0-beta.28.3`

## 1. I think there is a bug on `ng completion`, 
because when you introduce `ng completion --zsh` it returns all the zsh commands for the plugin and this little mensaje 
> The option '--zsh' is not registered with the completion command. Run `ng completion --help` for a list of supported options.

image

Telling that the --zsh is not supported, when it is.
#### So I think when your plugin uses  `ng completion --zsh` the _error_ `The option '--zsh' is not registered with...` could be added in the code and maybe it will crash...

## 2. The angular-cli npm package soon will be deprecated... The `ng` command itself warns about it.

>As a forewarning, we are moving the CLI npm package to "@angular/cli" with the next release,
which will only support Node 6.9 and greater. This package will be officially deprecated
shortly after.
>To disable this warning use "ng set --global warnings.packageDeprecation=false".

image

#### Have you noticed this? Do you have a plan?

**Comment by catull** [comment]
Hello @dianjuar 

## 1. warning on `--zsh` being invalid

I have `@angular/cli` version 1.0.0-rc.2.
I don't see the warning regarding `--zsh` not being a recognised option.

Can you update your `@angular/cli` version ?


## 2. deprecation of angular-cli

As a consequence, you must switch from `angular-cli` to `@angular/cli`
- `npm uninstall -g angular/cli`
- `npm cache clean`
- `npm install -g @angular/cli`

I am confident, that you solve most of the issues you identified.

The PR is not finished yet.

It all depends on contributing to `@angular/cli` for the completion feature.
I plan to contribute a change to produce better completion output for zsh.

My goal is that the oh-my-zsh plugin for `@angular/cli` will become a simple

```bash
      eval `ng --completion -z -s`
```

`-s` would be for a **short** output, such as 

```bash
_ng_completion () {
  local words cword opts
  read -Ac words
  read -cn cword
  let cword-=1

  case $words[cword] in
    ng | help)
		  opts='--version -v b build completion doc e e2e eject g generate get help l lint new s serve server set t test v version xi18n' ;;
    b | build)
		  opts='--aot --app --base-href --deploy-url --environment --extract-css --i18n-file --i18n-format --locale --output-hashing --output-path --poll --progress --sourcemap --stats-json --target --vendor-chunk --verbose --watch -a -aot -bh -d -e -ec -i18nFile -i18nFormat -locale -oh -op -poll -pr -sm -statsJson -t -v -vc -w' ;;
    completion)
		  opts='--all --bash --zsh -a -b -z' ;;
...
    xi18n)
		  opts='--app --i18n-format --locale --out-file --output-path --progress --verbose -a -f -l -of -op -progress -verbose' ;;
    *)
		  opts='' ;;
  esac

  setopt shwordsplit
  reply=($opts)
  unset shwordsplit
}
```

**Comment by dianjuar** [comment]
**Thank you so much**... I was following an old guide to learn `angular-cli` that didn't use `@angular/cli`.
Even my old version told me what to do but I didn't know what that `@` means, something special I thought.

Everything that I mentioned was resolved using your instructions. 

> - `npm uninstall -g angular-cli`
> - `npm cache clean`
> - `npm install -g @angular/cli`

**Comment by catull** [comment]
The '@' is a new convention specific for angular _modules_ that started with TypeScript definitons shifting from DefinitelyType to `@types/PACKAGE`.

I believe this naming scheme was picked in analogy of the "@types/PACKAGE" to get TypeScript definition for `npm` module "PACKAGE", such as `chai`, `node`, `webpack` etc.

You see it in package.json of `@angular/cli`:

dependencies has
- **"@angular/compiler"**: ">=2.3.1 <5.0.0 || >=4.0.0-beta <5.0.0",
- **"@angular/compiler-cli"**: ">=2.3.1 <5.0.0 || >=4.0.0-beta <5.0.0",
- **"@angular/core"**: ">=2.3.1 <5.0.0 || >=4.0.0-beta <5.0.0",
- **"@angular/tsc-wrapped"**: ">=0.5.0 <5.0.0 || >=4.0.0-beta <5.0.0",

devDependencies has
- **"@angular/cli"**: "^1.0.0-rc.2",

**Comment by xxxtonixxx** [comment]
> The completion command has been removed as the functionality no longer aligns with this version.

https://github.com/angular/angular-cli/issues/11043

> We would prefer that someone else maintains a Oh-my-Zsh plugin or some shell script that works better.

https://github.com/angular/angular-cli/issues/10238#issuecomment-380674150

some workaround? :confused:

**Comment by catull** [comment]
@xxxtonixxx True, I created a PR which is under review, but will likely not be accepted: https://github.com/angular/angular-cli/pull/11565.

**Comment by mcornella** [comment]
The `ng completion` command [was removed in v6](https://github.com/angular/angular-cli/releases/tag/v6.0.0).

**Pull request closed without merging**
