### PR TITLE
feat(mongo-atlas): add completion for atlas

### PR DESCRIPTION
**Pull request by serrovsky**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

- Add MongoDB atlas cli as a plugin

## Other comments:

...

### CODE REVIEW

**Review by carlosala — CHANGES_REQUESTED** [review]
It looks like several projects on github with a bunch of stars are called alias. Maybe another name (such as `mongo-atlas` maybe?) would be better!

**Comment by serrovsky** [comment]
Plugins renamed

**Review by serrovsky — COMMENTED** [review]
Plugin renamed

**Comment by carlosala** [comment]
Thanks for your contribution!

**Pull request merged**
