### PR TITLE
git: add alias for rebasing on top of origin/master

### PR DESCRIPTION
**Pull request by hikaru-shindo**
Signed-off-by: Pascal Nitsche <pascal.nitsche@cbc.de>

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

```sh
alias grbom='git rebase origin/master'
```

## Other comments:

This adds the ability to rebase on a master branch not merged locally. This avoids the need to:

* switch to master
* pull the changes in
* switch back to my branch
* do the actual rebase

to just 

* gfa (git fetch --all)
* grbom

### CODE REVIEW

**Review by makusu2 — COMMENTED** [review]
How about `git pull --rebase origin "$(git_main_branch)"`?

Uses `git_main_branch`, which is preferred over a hardcoded "master" (although it looks like this PR was created when everything used "master"...)

Also removes the `gfa` step, so that's nice.

**Comment by makusu2** [comment]
> rebasing shouldn't fetch - that'll fail if you don't have a network

Yeah, but these are convenience aliases. They're not meant to replace all `git` usage in every special case. I looked up a PR for a command for rebasing off remote main, and I found this, which seems to be written by someone with the exact same desire.

Maybe there's some philosophies on this repo that I'm not familiar with and you are, but it feels to me that the aliases provided here are meant to reduce typing. If someone doesn't have a network, which is absolutely possible, they'll have to use a different method of rebasing. Isn't that pretty fair?

**Comment by SimenB** [comment]
`grb` is `git rebase`, not `git pull`. You probably want `gupom` or something (`gup` is `git pull --rebase`)

**Comment by makusu2** [comment]
> `grb` is `git rebase`, not `git pull`. You probably want `gupom` or something (`gup` is `git pull --rebase`)

Ahh, that makes sense! Thanks for the clarification :+1:

**Pull request closed without merging**
