### PR TITLE
fix(git)!: remove `-b` from `blame` alias

### PR DESCRIPTION
**Pull request by adamchainz**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

Remove the `-b` from the `gbl` alias for `git blame`.

The [`-b` option](https://git-scm.com/docs/git-blame#Documentation/git-blame.txt--b) makes Git show no SHA for “boundary commits”, that is, commits at the start of the requested range. When no commit range is specified, that means the initial commit.

For example, in one of my projects, I created the `.editorconfig` file in the initial commit. A vanilla `git blame` on that file shows:

```
$ git blame .editorconfig
^d7a14a1 (Adam Johnson 2022-12-08 13:41:33 +0000  1) # http://editorconfig.org
^d7a14a1 (Adam Johnson 2022-12-08 13:41:33 +0000  2)
^d7a14a1 (Adam Johnson 2022-12-08 13:41:33 +0000  3) root = true
^d7a14a1 (Adam Johnson 2022-12-08 13:41:33 +0000  4)
...
```

`d7a14a1` is the abbreviated SHA for the initial commit in the project, and the `^` prefix indicates it as the boundary commit.

Adding `-b` changes the output to:

```
$ git blame -b .editorconfig | cat
         (Adam Johnson 2022-12-08 13:41:33 +0000  1) # http://editorconfig.org
         (Adam Johnson 2022-12-08 13:41:33 +0000  2)
         (Adam Johnson 2022-12-08 13:41:33 +0000  3) root = true
         (Adam Johnson 2022-12-08 13:41:33 +0000  4)
```

The commit SHA is gone for all lines untouched since the initial commit, although the author name and date remain.

IMO, this is confusing to those who haven’t got deep knowledge of `git blame`.

oh-my-zsh added `-b` with the `gbl` alias in #2790, copied out of #2433, without discussion of the options. I propose removing it. Advanced Git users can enable the behaviour globally if they like with the [`blame.blankBoundary` option](https://git-scm.com/docs/git-blame#Documentation/git-blame.txt-blameblankBoundary):

```
git config --global blame.blankBoundary true
```

### CODE REVIEW

**Comment by adamchainz** [comment]
@carlosala would you be able to review this one and #11869 ? Also I’m writing a book about Git which features oh-my-zsh’s plugin. If you would like to beta-read it, I’m sure you’d have some valuable feedback.

**Comment by carlosala** [comment]
Hi Adam, thanks for your contribution! I agree with your change, let's do it. Could you please update it accordingly in the README?
Thanks!

**Comment by carlosala** [comment]
I'd be interested on reading your book, feel free to contact me for that purpose!

**Comment by adamchainz** [comment]
> Hi Adam, thanks for your contribution! I agree with your change, let's do it. Could you please update it accordingly in the README?

Done.

> I'd be interested on reading your book, feel free to contact me for that purpose!

Thanks, I’ve emailed you.

**Comment by carlosala** [comment]
Thanks for your contribution!

**Pull request merged**
