### PR TITLE
feat(aws)!: improve `aws_change_access_key`

### PR DESCRIPTION
**Pull request by grimm26**
Add improvements to aws_change_access_key to catch more error conditions
and give more useful feedback.
Offer to deactivate the old access key after the new one is
generated and in place.

### CODE REVIEW

**Comment by grimm26** [comment]
@maksyms can I get some eyes on this?

**Review by maksyms — APPROVED** [review]
I don't use this functionality, but the changes look good to me.
One thing to note: THIS BREAKS AWS CLI v1 COMPATIBILITY.

@mcornella good to merge IMHO.

**Comment by grimm26** [comment]
@mcornella @maksyms any chance of this getting merged any time soon?

**Comment by carlosala** [comment]
@grimm26 hi! As this change breaks the compatibility with aws cli v1, could we have that info in the readme, that this plugin only allows the usage with aws cli v2?
Thanks!

**Comment by carlosala** [comment]
Thanks for your contribution!

**Pull request merged**
