### PR TITLE
fix(ssh-agent): add identity only if identity exists

### PR DESCRIPTION
**Pull request by zikoengxi**
## Standards checklist:

- [X] The PR title is descriptive.
- [X] The PR doesn't replicate another PR which is already open.
- [X] I have read the contribution guide and followed all the instructions.
- [X] The code follows the code style guide detailed in the wiki.
- [X] The code is mine or it's from somewhere with an MIT-compatible license.
- [X] The code is efficient, to the best of my ability, and does not waste computer resources.
- [X] The code is stable and I have tested it myself, to the best of my abilities.
- [ ] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

Check if the identity exists.

### CODE REVIEW

**Comment by mcornella** [comment]
Does this fix an existing issue? If so, can you provide a link or reproduction steps?

**Comment by zikoengxi** [comment]
> Does this fix an existing issue? If so, can you provide a link or reproduction steps?

if the identity

**Comment by zikoengxi** [comment]
> Does this fix an existing issue? If so, can you provide a link or reproduction steps?

If the identities are set up via zstyle, the non-existing identities are not checked. When loading the non-existing identity, `ssh-keygen -lf "$file"` will raise an exception: `ssh-keygen: /root/.ssh/$file: No such file or directory`.

**Comment by mcornella** [comment]
Thanks, that makes sense. It's been a while since I wrote the plugin so the refresher was nice. Thanks for the contribution!

**Pull request merged**
