### PR TITLE
fix: fixed gl alias

### PR DESCRIPTION
**Pull request by bhushan**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- fix: fixed wrong alias for gl

### CODE REVIEW

**Review by jmeridth — APPROVED** [review]

**Comment by carlosala** [comment]
`gl` has been `git pull` for a long time in the mindset of people, we shouldn't change that, it's so breaking.
But thanks for your contribution! 😉

**Comment by rwmitchell** [comment]
Just to be clear, we’re opposed to fixing bad past decisions?

git has too many options to have aliases to be mnemonic for everyone, best to remove all git aliases and let each person assign the ones that works for them.

**Comment by carlosala** [comment]
I don't know why should that be a bad decision. `git pull` is one of the most used commands every day, I feel like having an alias just composed by two letters to it is a great decision. Despite that, we can discuss about that if it's really a common feeling 👌🏻

**Comment by rwmitchell** [comment]
Use:
gu for git pull
gp for git push

**Comment by bhushan** [comment]
@carlosala do you agree to fixing it to `alias gl="git log"` ?

**Comment by carlosala** [comment]
I kinda understand your point, but I think that, at the end, this may raise other issues related to changing one basic alias of `git`. Let's ask @mcornella, what do you think about?

**Comment by rwmitchell** [comment]
CA,

The current 'gl' alias for 'git pull' is non-obvious, whereas 'gl' for 'git log' is.  Using 'gl' for pull was a bad decision from the beginning and not even consistent with the other aliases in the same plugin.

So it really comes down do this - do think you've already reached max omz/git plugin users and hence it is more important to cater to those (and assuming they also mentally unable to  adapt) or the new omz/git users to come is a larger group and it is more important to set things right now.

Is it time ti discard omz or does it have a long future?

**Pull request closed without merging**
