### PR TITLE
feat(web-search): add chatgpt

### PR DESCRIPTION
**Pull request by heytulsiprasad**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

- Add search with chatgpt --> "https://chat.openai.com?q=";
- Add new aliases in README.md ohmyzsh/plugins/web-search/README.md

## Other comments:

ChatGPT like LLMs are a great developer resource while building stuff and I've been using it since a long time to debug stuff, would be great to have an util in the CLI as well.

We can do other LLMs as well like perplexity but not sure if they support search through query. 

Also it'll work with `!!` operator to search about last query using chatgpt (which works for all the other alias as well)
...

### CODE REVIEW

**Review by carlosala — CHANGES_REQUESTED** [review]
It seems to work as well with `https://chatgpt.com/?q=`. I'd go for this one since it seems to be the recommended URL now.

**Review by carlosala — APPROVED** [review]
LGTM! 🚀

**Comment by carlosala** [comment]
Thanks for your contribution!

**Comment by heytulsiprasad** [comment]
Wow that was fast! ⚡ 

Keep up the good work @carlosala 💜

**Pull request merged**
