### PR TITLE
Update aliases in rails.zsh.plugin

### PR DESCRIPTION
**Pull request by alec-c4**
Update aliases in rails.zsh.plugin because of rake commands deprecation.

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.

## Changes:

- replace old rake-commands commands with new rails-commands
- move old rake-commands to the legacy zone with r-prefix. For example 'rake routes' is moved to rrr instead of rr. 

## Other comments:

...

### CODE REVIEW

**Review by Archish27 — APPROVED** [review]
LGTM 🚀

**Comment by mcornella** [comment]
Can you link to relevant documentation? Which versions are impacted by this. Also, this should be documented in the README, and possibly put behind a setting.

**Comment by alec-c4** [comment]
@mcornella sure! You can check official [rails guides](https://guides.rubyonrails.org/command_line.html)

**Comment by choosen** [comment]
again similar PR to : https://github.com/ohmyzsh/ohmyzsh/pull/8975/files

**Comment by carlosala** [comment]
> Can you link to relevant documentation? Which versions are impacted by this? Also, this should be documented in the README, and possibly put behind a setting.

Hi Alexey, could you please revise this things that Marc suggested?
Thanks!

**Comment by alec-c4** [comment]
@carlosala https://guides.rubyonrails.org/v5.2/command_line.html#bin-rails regarding this document - rails 5+ (current version is 7.0.2.2)

**Comment by carlosala** [comment]
Ok, looks great to merge. Could you update the documentation in the plugin's README?

**Pull request closed without merging**
