### PR TITLE
Add option for classic green logo text on upgrade

### PR DESCRIPTION
**Pull request by gildartsirc**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [ ] The code follows the code style guide detailed in the wiki.
  - It doesn't, but neither does the code around my insertion. I matched the local style.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Adds an option to use the classic green logo text to match one of the sticker options.

### CODE REVIEW

**Comment by mcornella** [comment]
Why, no love for the rainbow version? I don't really want to add yet another setting for this.

**Comment by gildartsirc** [comment]
Just prefer the green color. And it matches one of the sticker designs that is sold. Which was the reasoning behind changing it to a rainbow in the first place as far as I can tell.

If adding another option is a no-go, I can deal with it obviously. Just thought I would add the option.

**Comment by mcornella** [comment]
I can't accept this sorry, thanks for contributing!

**Comment by timka** [comment]
For those who still want the classic green it's safe to just change the logo printing part in `~/.oh-my-zsh/tools/upgrade.sh` by replacing $RAINBOW with $GREEN.

**Pull request closed without merging**
