### PR TITLE
Made some Grammatic correction

### PR DESCRIPTION
**Pull request by josephmathai10**
## Standards checklist:

- [ ] The PR title is descriptive.
- [ ] The PR doesn't replicate another PR which is already open.
- [ ] I have read the contribution guide and followed all the instructions.
- [ ] The code follows the code style guide detailed in the wiki.
- [ ] The code is mine or it's from somewhere with an MIT-compatible license.
- [ ] The code is efficient, to the best of my ability, and does not waste computer resources.
- [ ] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- [...]

## Other comments:

...

### CODE REVIEW

**Comment by josephmathai10** [comment]
Excuse me, I was just trying to help you and is this how you thank me. By marking it spam. If you dont need it then just close the request.

**Comment by mcornella** [comment]
The way it is written is correct. Installation problems is correct. `@ohmyzsh on Twitter` is correct. Your PR is invalid, useless, and it costs me time to triage. You're the 4th person to open a spam PR. I hope you reconsider your ways to obtain the Hacktoberfest t-shirt and start considering maintainers time as valuable.

**Comment by josephmathai10** [comment]
> The way it is written is correct. Installation problems is correct. `@ohmyzsh on Twitter` is correct. Your PR is invalid, useless, and it costs me time to triage. You're the 4th person to open a spam PR. I hope you reconsider your ways to obtain the Hacktoberfest t-shirt and start considering maintainers time as valuable.

I am not here to attain tshirt i already have more than 7 accepted commits. I am here to help people correct error and if its not valid for your program. Then just close it.  How does this became a spam.

**Comment by mcornella** [comment]
I don't know how many commits you've made, I just know this PR wasn't useful and we're in the middle of Hacktoberfest so I have to consider this as another PR for Hacktoberfest. As a maintainer I have a duty to weed out these kinds of PRs and mark them as invalid when they don't pass a minimum standard. If you already have the required commits I suggest you stop making more PRs like this one or you'll get banned from Hacktoberfest. Good day sir

**Pull request closed without merging**
