### PR TITLE
feat(golang): add aliases for  utility

### PR DESCRIPTION
**Pull request by 180909**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Added aliases for go mod download, go mod graph, go mod init, go mod tidy and go mod vendor

## Other comments:

...

### CODE REVIEW

**Review by jmeridth — CHANGES_REQUESTED** [review]
You need to update the README file too

**Review by jmeridth — APPROVED** [review]

**Comment by 180909** [comment]
ping?

**Comment by carlosala** [comment]
Hi! We are developing a brand new alias policy where we are going to be more "strict" in how we accept aliases, due to the massive amount of them that we have in the project. One of the points is that we are going to accept one generic alias instead of several specific ones. In this case, `go mod` would be the generic one and `go mod download`, for example, the specific one. You can check that policy (is still being finished) [here](https://github.com/ohmyzsh/ohmyzsh/pull/11045).
Thanks for your contribution!

**Comment by 180909** [comment]
Thanks review. I will close this pr.

**Comment by carlosala** [comment]
Thanks for your contribution 😉

**Pull request closed without merging**
