### PR TITLE
feat(npm): add `npmrd` alias

### PR DESCRIPTION
**Pull request by KozmikNano**
## Standards checklist:

- [X] The PR title is descriptive.
- [X] The PR doesn't replicate another PR which is already open.
- [X] I have read the contribution guide and followed all the instructions.
- [X] The code follows the code style guide detailed in the wiki.
- [X] The code is mine or it's from somewhere with an MIT-compatible license.
- [X] The code is efficient, to the best of my ability, and does not waste computer resources.
- [X] The code is stable and I have tested it myself, to the best of my abilities.
- [X] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

- Add an npmRD alias in the npm plugin to use `npm run dev`

## Other comments:

Many developers use `npm run dev` to test their code. If an alias for `npm test` exists, then `npm run dev` should also exist.

### CODE REVIEW

**Review by carlosala — COMMENTED** [review]
Nice one! do you mind if we change it with `npmrd`?

**Comment by KozmikNano** [comment]
> Nice one! do you mind if we change it with `npmrd`?

Not at all, I have made the change. 😃

**Comment by carlosala** [comment]
Could you change that also in the readme?

**Comment by carlosala** [comment]
Thanks for your contribution!

**Comment by KozmikNano** [comment]
> Thanks for your contribution!

Thanks for merging!

**Pull request merged**
