### PR TITLE
Add venv helper functions

### PR DESCRIPTION
**Pull request by InCogNiTo124**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Add `mkv` function that creates a virtual environment using built-in `venv` module in Python Standard Library. The name of the virtual environment can be specified bit it is `venv` by default.
- Add `vrun` function that automatically activates a virtual environment. The name can be secified, but it is `venv` by default.

## Other comments

none

### CODE REVIEW

**Review by lodenrogue — APPROVED** [review]
I created something similar to this: https://github.com/lodenrogue/mkenv

Nice to see the functionality being added to zsh as a plugin.

**Comment by InCogNiTo124** [comment]
> I created something similar to this: https://github.com/lodenrogue/mkenv
> 
> Nice to see the functionality being added to zsh as a plugin.

yeah, it is very similar
I found my functions really helpful so I figured the community would also appreciate them :smiley:

**Comment by InCogNiTo124** [comment]
@mcornella have you taken a look? What do you think?

**Comment by InCogNiTo124** [comment]
Request for reviews

**Review by CleverLettuce — APPROVED** [review]

**Comment by InCogNiTo124** [comment]
Bump

**Comment by mcornella** [comment]
Thanks!

**Pull request closed without merging**
