### PR TITLE
[git plugin] Add gcsa alias for git commit -sa

### LINKED ISSUE #8689: [git plugin] Add gcsa alias for git commit -sa
**Is your feature request related to a particular plugin or theme? If so, specify it.**
git plugin

**Is your feature request related to a problem? Please describe.**
No I would like to add an alias for git commit -sa (I always use it and there's no way to do so with current aliases)

**Describe the solution you'd like**
Add `gcsa` alias for `git commit -sa`.

### PR DESCRIPTION
**Pull request by davideferre**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Added gcsa alias for git commit -sa

### CODE REVIEW

**Comment by mcornella** [comment]
The PR title is absolutely not descriptive, opening an issue minutes before making a PR is redundant, and you didn't explain what the alias does (even though I can google it, it's common courtesy to explain stuff).

**Comment by davideferre** [comment]
> The PR title is absolutely not descriptive, opening an issue minutes before making a PR is redundant, and you didn't explain what the alias does (even though I can google it, it's common courtesy to explain stuff).

My bad, I've read the contributing file and I understood that an issue is required for opening a PR, sorry.

**Comment by mcornella** [comment]
Can you point me to where in the contributing file it says that? Because I'd like to clarify it.

**Comment by davideferre** [comment]
> Can you point me to where in the contributing file it says that? Because I'd like to clarify it.

Maybe you have to clarify that is not necessary to open an issue for submitting a PR for a new feature/suggestion in _Reporting Issues->You have a suggestion_ and/or in _Submitting Pull Requests->You have an addition_.

**Review by 53jk1 — APPROVED** [review]

**Comment by adamchainz** [comment]
#8881 added `gcas` which does the same as suggested here, so this PR can be closed @carlosala .

**Comment by carlosala** [comment]
Closing then, thanks for the point!

**Pull request closed without merging**
