### PR TITLE
feat(macports): add commands to get list of updated ports

### PR DESCRIPTION
**Pull request by emcrisostomo**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Commands are provided to search with the following criteria:

* `pli`: check for updates of installed ports
* `plm`: check for updates of ports maintained by the specified list ids.

## Other comments:

...

### CODE REVIEW

**Comment by emcrisostomo** [comment]
Gentle reminder.

**Comment by emcrisostomo** [comment]
Am I knocking on the wrong door?

**Comment by bartekpacia** [comment]
Hi @emcrisostomo, sorry for the __late__ response.
Thank you for this contribution, I mark it as "to merge".

**Comment by emcrisostomo** [comment]
No worries, thanks @bartekpacia

**Review by 53jk1 — APPROVED** [review]

**Comment by mcornella** [comment]
Thanks Enrico!

**Pull request merged**
