### PR TITLE
fix: automatically create completion for `cargo` and `rustup` plugins

### PR DESCRIPTION
**Pull request by carlosala**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:
`rustup` and `cargo` plugins were using a completion file without considering the version of them.
I created functions to get the completion correctly.

## Other comments:
I think that this two plugins should be just one, as everybody who uses `cargo` needs `rustup` to install it.

Thanks!

### CODE REVIEW

**Comment by carlosala** [comment]
Hi @mcornella!
It's ready to merge!
Thanks!

**Comment by carlosala** [comment]
Hey @mcornella, is there any problem with the PR?
Thanks sir!

**Comment by mcornella** [comment]
Thanks! Apologies for the delay!

**Comment by carlosala** [comment]
> Thanks! Apologies for the delay!

No worries! Thanks to you!

**Pull request merged**
