### PR TITLE
feat(kubectl): add aliases for job management

### PR DESCRIPTION
**Pull request by vitulrana**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR that is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Added alias for Get, Edit, Describe and Delete for Kubernetes Job Objects

## Other comments:

...

### CODE REVIEW

**Comment by vitulrana** [comment]
@robbyrussell Please help promote this small change

**Comment by vitulrana** [comment]
@TheTechRobo Please help promote this small change

**Comment by nisiyong** [comment]
Why still NOT merge this PR? I just almost create the same PR.
Please merge this ASAP, we indeed need this. 
@mcornella @larson-carter @carlosala

**Review by larson-carter — APPROVED** [review]
Sorry about this review taking so long... I had this written on a piece of paper long back, stating it was ready to merge. 

CC: @mcornella

**Comment by nisiyong** [comment]
@larson-carter Thanks for reviewing that, hope it will be merged ASAP. 😃

**Comment by nisiyong** [comment]
@larson-carter Could you merge this? It's been a long wait.

**Comment by vitulrana** [comment]
@larson-carter Can we merge this ?

**Comment by nisiyong** [comment]
> @larson-carter Can we merge this ?

@larson-carter @mcornella It should be merged.

**Pull request merged**
