### PR TITLE
archlinux: add aliases for paru

### PR DESCRIPTION
**Pull request by kattjevfel**
##  Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Adds alises for [paru](https://github.com/Morganamilo/paru)

## Other comments:

99% copied from yay since it's based on it

### CODE REVIEW

**Comment by nowshed-imran** [comment]
+1 for this. Paru is THE alternative of Yay now.

**Comment by nowshed-imran** [comment]
@mcornella @robbyrussell @larson-carter 
Sorry for the uninvited tag. Can anyone merge this? Paru is a leading AUR helper now for Archlinux.

**Comment by nevack** [comment]
@kattjevfel Can you rebase this PR and fix conflicts?

**Comment by Morganamilo** [comment]
It looks like some one just copy pasted this from yay assuming all the flags are the same. Some of the descriptions are also wrong.

**Comment by kattjevfel** [comment]
I've stopped using both oh-my-zsh and paru for a long time now, so I can't really update this PR to be correct anymore, sorry.

**Pull request closed without merging**
