### PR TITLE
Add plugin for ROS framework

### PR DESCRIPTION
**Pull request by migermain**
Prompt integration of master status;
Master URI and ROS_IP management;
Catkin workspace management.

### CODE REVIEW

**Comment by nickswalker** [comment]
This looks great! I hope it eventually gets merged in...

**Comment by Aryan-jaiswal** [comment]
How do I integrate this plugin with zsh ?There is some error with the _ros.cache_ file?

**Comment by mcornella** [comment]
Can you add a README?

**Comment by mcornella** [comment]
Ping @migermain

**Comment by robbyrussell** [comment]
Going to close this. Should someone like to have this merged, please include a README along with the ride. Thanks in advance!

**Pull request closed without merging**
