### PR TITLE
 feat(git) Add alias gswr => git switch --recurse-submodule

### PR DESCRIPTION
**Pull request by owngr**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- added an alias alias gswr='git switch --recurse-submodules'  as git checkout --recurse-submodules already has an alias, this would help to switch branches containing submodules without having to use git checkout or deinit/init

### CODE REVIEW

**Comment by fmalcher** [comment]
Can you please also add this new command to the readme? Thanks 😊

**Comment by Olivierwenger** [comment]
@fmalcher 
Command has been added to the readme :)

**Comment by esemeniuc** [comment]
Would love to see this merged!

**Comment by adamchainz** [comment]
If you enable [`submodule.recurse`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-submodulerecurse) in your Git configuration, all commands will act as if `--recurse-submodules` is provided. That sounds preferable to me over adding extra aliases that pass the option.

**Comment by carlosala** [comment]
Good point Adam. Closing, modifying people's config rather than the whole shell framework makes sense.

**Pull request closed without merging**
