### PR TITLE
Add podman support

### PR DESCRIPTION
**Pull request by agilob**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Add official podman autocomplete https://github.com/ohmyzsh/ohmyzsh/issues/7489

### CODE REVIEW

**Review by 53jk1 — APPROVED** [review]

**Comment by agilob** [comment]
Any plans to merge it? @53jk1 @mcornella ? Can I close this PR if you're not going to merge it?

**Comment by mcornella** [comment]
Maybe a better solution would be to run [`podman completion zsh`](https://github.com/containers/podman/blob/master/docs/source/markdown/podman-completion.1.md#zsh) and cache that, like the npm plugin does. That way we don't need to update this every time there's an upstream change.

**Comment by 53jk1** [comment]
I'm not a collaborator, sorry.

**Comment by Avamander** [comment]
@agilob what do you think of mcornella's proposal?

**Pull request closed without merging**
